// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.

package blog

import (
	"github.com/jryannel/sqlb"
	"time"
)

type authorColumns struct {
	ID        sqlb.Col[string]
	OrgID     sqlb.Col[string]
	Email     sqlb.TextCol[string]
	Name      sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// AuthorCols are the typed columns of authors.
// Hidden columns are omitted: a predicate against one should not compile.
var AuthorCols = authorColumns{
	ID:        sqlb.Typed[string]("id"),
	OrgID:     sqlb.Typed[string]("org_id"),
	Email:     sqlb.TextColumn[string]("email"),
	Name:      sqlb.TextColumn[string]("name"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// AuthorUpdate is a typed update statement for authors.
type AuthorUpdate struct {
	stmt *sqlb.Update[Author]
}

// UpdateAuthor starts a typed update.
func UpdateAuthor() *AuthorUpdate {
	return &AuthorUpdate{stmt: sqlb.UpdateRows[Author]()}
}

// SetOrgID sets org_id.
func (u *AuthorUpdate) SetOrgID(v string) *AuthorUpdate {
	u.stmt.Set("org_id", v)
	return u
}

// SetEmail sets email.
func (u *AuthorUpdate) SetEmail(v string) *AuthorUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetName sets name.
func (u *AuthorUpdate) SetName(v string) *AuthorUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetPasswordHash sets password_hash.
func (u *AuthorUpdate) SetPasswordHash(v string) *AuthorUpdate {
	u.stmt.Set("password_hash", v)
	return u
}

// Where narrows the affected rows.
func (u *AuthorUpdate) Where(preds ...sqlb.Pred) *AuthorUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *AuthorUpdate) Stmt() *sqlb.Update[Author] { return u.stmt }

type orgColumns struct {
	ID        sqlb.Col[string]
	Name      sqlb.TextCol[string]
	Slug      sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// OrgCols are the typed columns of orgs.
var OrgCols = orgColumns{
	ID:        sqlb.Typed[string]("id"),
	Name:      sqlb.TextColumn[string]("name"),
	Slug:      sqlb.TextColumn[string]("slug"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// OrgUpdate is a typed update statement for orgs.
type OrgUpdate struct {
	stmt *sqlb.Update[Org]
}

// UpdateOrg starts a typed update.
func UpdateOrg() *OrgUpdate {
	return &OrgUpdate{stmt: sqlb.UpdateRows[Org]()}
}

// SetName sets name.
func (u *OrgUpdate) SetName(v string) *OrgUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetSlug sets slug.
func (u *OrgUpdate) SetSlug(v string) *OrgUpdate {
	u.stmt.Set("slug", v)
	return u
}

// Where narrows the affected rows.
func (u *OrgUpdate) Where(preds ...sqlb.Pred) *OrgUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *OrgUpdate) Stmt() *sqlb.Update[Org] { return u.stmt }

type postColumns struct {
	ID          sqlb.Col[string]
	OrgID       sqlb.Col[string]
	AuthorID    sqlb.Col[string]
	Title       sqlb.TextCol[string]
	Body        sqlb.TextCol[string]
	Status      sqlb.Col[PostStatus]
	ViewCount   sqlb.Col[int64]
	PublishedAt sqlb.Col[time.Time]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
	DeletedAt   sqlb.Col[time.Time]
}

// PostCols are the typed columns of posts.
var PostCols = postColumns{
	ID:          sqlb.Typed[string]("id"),
	OrgID:       sqlb.Typed[string]("org_id"),
	AuthorID:    sqlb.Typed[string]("author_id"),
	Title:       sqlb.TextColumn[string]("title"),
	Body:        sqlb.TextColumn[string]("body"),
	Status:      sqlb.Typed[PostStatus]("status"),
	ViewCount:   sqlb.Typed[int64]("view_count"),
	PublishedAt: sqlb.Typed[time.Time]("published_at"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
	DeletedAt:   sqlb.Typed[time.Time]("deleted_at"),
}

// PostUpdate is a typed update statement for posts.
type PostUpdate struct {
	stmt *sqlb.Update[Post]
}

// UpdatePost starts a typed update.
func UpdatePost() *PostUpdate {
	return &PostUpdate{stmt: sqlb.UpdateRows[Post]()}
}

// SetOrgID sets org_id.
func (u *PostUpdate) SetOrgID(v string) *PostUpdate {
	u.stmt.Set("org_id", v)
	return u
}

// SetAuthorID sets author_id.
func (u *PostUpdate) SetAuthorID(v string) *PostUpdate {
	u.stmt.Set("author_id", v)
	return u
}

// SetTitle sets title.
func (u *PostUpdate) SetTitle(v string) *PostUpdate {
	u.stmt.Set("title", v)
	return u
}

// SetBody sets body.
func (u *PostUpdate) SetBody(v string) *PostUpdate {
	u.stmt.Set("body", v)
	return u
}

// SetStatus sets status.
func (u *PostUpdate) SetStatus(v PostStatus) *PostUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetPublishedAt sets published_at.
func (u *PostUpdate) SetPublishedAt(v *time.Time) *PostUpdate {
	u.stmt.Set("published_at", v)
	return u
}

// Where narrows the affected rows.
func (u *PostUpdate) Where(preds ...sqlb.Pred) *PostUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *PostUpdate) Stmt() *sqlb.Update[Post] { return u.stmt }
