// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID           string
	OrgID        string
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

// A tenant. Every other table is scoped to one.
type Org struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// A blog post.
type Post struct {
	ID          string
	OrgID       string
	AuthorID    string
	Title       string
	Body        string
	Status      string
	ViewCount   int64
	PublishedAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}
