// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Author struct {
	ID           string
	OrgID        string
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// A tenant. Every other table is scoped to one.
type Org struct {
	ID        string
	Name      string
	Slug      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

// A blog post.
type Post struct {
	ID          string
	OrgID       string
	AuthorID    string
	Title       string
	Body        string
	Status      string
	ViewCount   int64
	PublishedAt sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}
