// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"
)

const authorLeaderboard = `-- name: AuthorLeaderboard :many

SELECT
    a.id,
    a.name,
    a.org_id,
    count(p.id) AS published_posts,
    rank() OVER (PARTITION BY a.org_id ORDER BY count(p.id) DESC) AS org_rank
FROM authors a
LEFT JOIN posts p
    ON p.author_id = a.id
    AND p.status = 'published'
    AND p.deleted_at IS NULL
GROUP BY a.id, a.name, a.org_id
ORDER BY a.org_id, org_rank
`

type AuthorLeaderboardRow struct {
	ID             string
	Name           string
	OrgID          string
	PublishedPosts int64
	OrgRank        int64
}

// These are deliberately the queries sqlb is bad at.
//
// sqlb's non-goal is static analytical SQL: a window function or a recursive
// CTE goes through sqlb.Raw, which is an escape hatch rather than a feature
// (ADR-0009). sqlc types both at compile time, which is its whole guarantee.
// So they live here, and the filterable list endpoints live in sqlb.
// A window function: rank authors within their org by published posts. Nothing
// about this benefits from being expressible as a runtime filter.
func (q *Queries) AuthorLeaderboard(ctx context.Context) ([]AuthorLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, authorLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorLeaderboardRow
	for rows.Next() {
		var i AuthorLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.PublishedPosts,
			&i.OrgRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, org_id, email, name, password_hash, created_at, updated_at FROM authors WHERE id = $1
`

// A plain lookup, included only so the generated Author struct exists for the
// adoption test to point sqlb.Describe at.
func (q *Queries) GetAuthor(ctx context.Context, id string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const postViewsByStatus = `-- name: PostViewsByStatus :many
SELECT
    status,
    count(*) AS post_count,
    sum(view_count)::bigint AS total_views
FROM posts
WHERE org_id = $1
  AND deleted_at IS NULL
GROUP BY status
ORDER BY status
`

type PostViewsByStatusRow struct {
	Status     string
	PostCount  int64
	TotalViews int64
}

// A grouped aggregate over one org. sqlb can express this with Collect, but the
// result shape is not the table shape, so the typed guarantee is worth more
// here than the runtime filterability sqlb trades it for.
func (q *Queries) PostViewsByStatus(ctx context.Context, orgID string) ([]PostViewsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, postViewsByStatus, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostViewsByStatusRow
	for rows.Next() {
		var i PostViewsByStatusRow
		if err := rows.Scan(&i.Status, &i.PostCount, &i.TotalViews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
