// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authorLeaderboard = `-- name: AuthorLeaderboard :many

SELECT
    a.id,
    a.name,
    a.org_id,
    count(p.id) AS published_posts,
    rank() OVER (PARTITION BY a.org_id ORDER BY count(p.id) DESC) AS org_rank
FROM authors a
LEFT JOIN posts p
    ON p.author_id = a.id
    AND p.status = 'published'
    AND p.deleted_at IS NULL
GROUP BY a.id, a.name, a.org_id
ORDER BY a.org_id, org_rank
`

type AuthorLeaderboardRow struct {
	ID             string
	Name           string
	OrgID          string
	PublishedPosts int64
	OrgRank        int64
}

// These are deliberately the queries sqlb is bad at.
//
// sqlb's non-goal is static analytical SQL: a window function or a recursive
// CTE goes through sqlb.Raw, which is an escape hatch rather than a feature
// (ADR-0009). sqlc types both at compile time, which is its whole guarantee.
// So they live here, and the filterable list endpoints live in sqlb.
// A window function: rank authors within their org by published posts. Nothing
// about this benefits from being expressible as a runtime filter.
func (q *Queries) AuthorLeaderboard(ctx context.Context) ([]AuthorLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, authorLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorLeaderboardRow
	for rows.Next() {
		var i AuthorLeaderboardRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrgID,
			&i.PublishedPosts,
			&i.OrgRank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, org_id, email, name, password_hash, created_at, updated_at FROM authors WHERE id = $1
`

// A plain lookup, included only so the generated Author struct exists for the
// adoption test to point sqlb.Describe at.
func (q *Queries) GetAuthor(ctx context.Context, id string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, org_id, author_id, title, body, status, view_count, published_at, created_at, updated_at, deleted_at FROM posts
WHERE org_id = $1
  AND deleted_at IS NULL
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::bigint IS NULL OR view_count >= $3::bigint)
  AND ($4::text IS NULL OR title ILIKE '%' || $4::text || '%')
ORDER BY published_at DESC
LIMIT $5
`

type ListPostsParams struct {
	OrgID     string
	Status    pgtype.Text
	MinViews  pgtype.Int8
	Search    pgtype.Text
	PageLimit int32
}

// The exception, and the one query here that is NOT what sqlc is good at.
//
// This is stage 1 of docs/refactoring-from-sqlc.md: a filterable list endpoint
// written the only way static SQL can express one. Every optional filter
// becomes an arm that is always sent and usually means nothing, which is the
// documented sqlc workaround rather than a strawman — see comparisons.md.
//
// It is here to be replaced, not to be imitated. stage1.go calls it, stage2.go
// through stage4.go do the same job, and refactor_test.go holds all four to the
// same answers.
//
// What the shape costs, beyond reading badly:
//
//   - Three predicates reach Postgres on every request, each guarded by a NULL
//     check the planner has to see through. Stage 2 sends only what was asked.
//   - The sort is baked in. `ORDER BY published_at DESC` cannot become
//     `ORDER BY view_count ASC` without a second copy of the whole query, so a
//     column the UI can sort by is a query, and n columns times two directions
//     is 2n of them.
//   - Nothing here says which columns a *client* may filter on. That decision
//     lives in whatever handler assembles these parameters, so it is reviewable
//     only by reading that handler — where ADR-0006 puts it in the schema.
func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]Post, error) {
	rows, err := q.db.Query(ctx, listPosts,
		arg.OrgID,
		arg.Status,
		arg.MinViews,
		arg.Search,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.AuthorID,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.ViewCount,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const postViewsByStatus = `-- name: PostViewsByStatus :many
SELECT
    status,
    count(*) AS post_count,
    sum(view_count)::bigint AS total_views
FROM posts
WHERE org_id = $1
  AND deleted_at IS NULL
GROUP BY status
ORDER BY status
`

type PostViewsByStatusRow struct {
	Status     string
	PostCount  int64
	TotalViews int64
}

// A grouped aggregate over one org. sqlb can express this with Collect, but the
// result shape is not the table shape, so the typed guarantee is worth more
// here than the runtime filterability sqlb trades it for.
func (q *Queries) PostViewsByStatus(ctx context.Context, orgID string) ([]PostViewsByStatusRow, error) {
	rows, err := q.db.Query(ctx, postViewsByStatus, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostViewsByStatusRow
	for rows.Next() {
		var i PostViewsByStatusRow
		if err := rows.Scan(&i.Status, &i.PostCount, &i.TotalViews); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
