// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.
//
// The typed client for this schema: row types, request parameters, the encoder
// for the filter grammar, transport functions and cache keys.
//
// It imports nothing. The transport is injected, because session storage,
// token refresh and redirect-on-401 are the application's and are not
// derivable from a schema — the same seam the server takes by mounting onto a
// router the application built.
//
// Property names are the wire spelling, which is snake_case. Camel-casing
// would need a runtime mapping layer between the response and the caller, and
// the point of a generated client is that there is nothing there.
//
// ADR-0028.

// ------------------------------------------------------------------- runtime

/** A capped set of expanded child rows. `has_more` reports truncation, which a
 * bare array could not, so a caller reading twenty of two hundred can tell. */
export interface Collection<T> {
  items: T[];
  has_more: boolean;
}

/** The body of every list response: a collection, plus where in the walk it is.
 *
 * It extends Collection rather than restating it, because an expansion returns
 * a strict subset of these fields and two hand-written shapes would be free to
 * drift. */
export interface Page<T> extends Collection<T> {
  page: number;
  per_page: number;
  /** The position to resume from, present whenever a next page exists. Prefer it
   * to `page`: it costs the same at any depth and cannot skip or repeat a row
   * when the table is written to mid-walk. */
  next_cursor?: string;
  /** Total matching rows, present only when `count: 'exact'` was asked for. */
  total?: number;
}

/** One rejected parameter or field. */
export interface ProblemDetail {
  message: string;
  /** Where the problem is, e.g. `query.sort`. */
  location?: string;
  value?: unknown;
  /** What would have been accepted instead, where the set is finite. This is the
   * half of an error that turns a dead end into a fix, and it is why the client
   * carries an error type at all. */
  allowed?: string[];
}

/** The RFC 9457 problem document every rejection returns. */
export interface Problem {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  errors?: ProblemDetail[];
}

/** Narrows an unknown error body to a Problem. */
export function isProblem(value: unknown): value is Problem {
  if (typeof value !== 'object' || value === null) return false;
  const p = value as Problem;
  return typeof p.status === 'number' || Array.isArray(p.errors);
}

/** The allowed values a rejection named for one parameter, e.g.
 * `allowedFor(problem, 'query.sort')`. */
export function allowedFor(problem: Problem, location: string): string[] {
  return problem.errors?.find((e) => e.location === location)?.allowed ?? [];
}

/** One request, as the generated functions describe it. */
export interface ApiRequest {
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
  /** Path from the API root, already encoded, e.g. `/tasks/1`. */
  path: string;
  /** Encoded query string without the leading `?`. */
  query?: string;
  body?: unknown;
  signal?: AbortSignal;
}

/**
 * The application's request function.
 *
 * Everything not derivable from the schema lives behind this: the base URL,
 * the auth header, refresh, retry, and what a 401 does. A minimal one:
 *
 *     const request: Transport = async ({ method, path, query, body, signal }) => {
 *       const res = await fetch(`${base}${path}${query ? '?' + query : ''}`, {
 *         method,
 *         headers: { ...(body ? { 'content-type': 'application/json' } : {}), ...auth() },
 *         body: body === undefined ? undefined : JSON.stringify(body),
 *         signal,
 *       });
 *       if (!res.ok) throw await res.json();
 *       return res.status === 204 ? (undefined as never) : res.json();
 *     };
 */
export type Transport = <T>(request: ApiRequest) => Promise<T>;

/** Operators every column type accepts. */
export interface Comparison<V> {
  eq?: V;
  ne?: V;
  gt?: V;
  gte?: V;
  lt?: V;
  lte?: V;
  in?: readonly V[];
  nin?: readonly V[];
  between?: readonly [V, V];
}

/** Null tests, offered only by nullable columns. */
export interface NullCheck {
  isnull?: boolean;
  notnull?: boolean;
}

/** Pattern operators, offered only by text columns. */
export interface TextMatch {
  like?: string;
  ilike?: string;
  /** Case-insensitive substring. The value is escaped, so `50%` matches that
   * literal string rather than everything. */
  contains?: string;
  startswith?: string;
  endswith?: string;
}

/** One column's filter: a bare value for equality, or an operator object. */
export type Cond<V, Extra = unknown> = V | (Comparison<V> & Extra);

type Scalar = string | number | boolean | Date;

function encodeScalar(v: Scalar): string {
  return v instanceof Date ? v.toISOString() : String(v);
}

/** A member of a comma-separated list is quoted when it carries a comma or a
 * quote, which is how the server's parser reads it back whole. */
function encodeMember(v: Scalar): string {
  const s = encodeScalar(v);
  return /[,"]/.test(s) ? '"' + s.replace(/"/g, '\\"') + '"' : s;
}

function appendCond(out: URLSearchParams, column: string, cond: unknown): void {
  if (cond === undefined) return;
  // A bare null is read as a null test rather than as an equality against NULL,
  // which is not a comparison SQL would answer true to anyway.
  if (cond === null) {
    out.append(column, 'isnull');
    return;
  }
  if (typeof cond !== 'object' || cond instanceof Date) {
    out.append(column, 'eq.' + encodeScalar(cond as Scalar));
    return;
  }
  // Repeating a parameter conjoins its conditions, so an object with two
  // operators becomes two parameters rather than one compound value.
  for (const [op, value] of Object.entries(cond as Record<string, unknown>)) {
    if (value === undefined || value === null) continue;
    switch (op) {
      case 'isnull':
      case 'notnull':
        if (value) out.append(column, op);
        break;
      case 'in':
      case 'nin':
        out.append(column, op + '.' + (value as Scalar[]).map(encodeMember).join(','));
        break;
      case 'between': {
        const [lo, hi] = value as [Scalar, Scalar];
        out.append(column, 'between.' + encodeMember(lo) + ',' + encodeMember(hi));
        break;
      }
      default:
        out.append(column, op + '.' + encodeScalar(value as Scalar));
    }
  }
}

/** The shape encodeListQuery reads. Each resource's params type is one of
 * these with its columns and operators pinned. */
export interface ListQuery {
  where?: Record<string, unknown>;
  search?: string;
  sort?: string | readonly string[];
  select?: readonly string[];
  expand?: readonly string[];
  page?: number;
  per_page?: number;
  cursor?: string;
  count?: 'exact';
  params?: Record<string, string | readonly string[]>;
}

/**
 * Encodes list parameters into the server's query grammar.
 *
 * This is the piece hand-written clients open-code and get subtly wrong: the
 * operator prefixes, the repeated parameters that conjoin, and the quoting
 * inside a value list.
 */
export function encodeListQuery(query: ListQuery = {}): string {
  const out = new URLSearchParams();
  for (const [column, cond] of Object.entries(query.where ?? {})) appendCond(out, column, cond);
  if (query.search) out.set('search', query.search);
  if (query.sort) out.set('sort', typeof query.sort === 'string' ? query.sort : query.sort.join(','));
  if (query.select?.length) out.set('select', query.select.join(','));
  if (query.expand?.length) out.set('expand', query.expand.join(','));
  if (query.page !== undefined) out.set('page', String(query.page));
  if (query.per_page !== undefined) out.set('per_page', String(query.per_page));
  if (query.cursor !== undefined) out.set('cursor', query.cursor);
  if (query.count !== undefined) out.set('count', query.count);
  for (const [key, value] of Object.entries(query.params ?? {})) {
    for (const item of Array.isArray(value) ? value : [value as string]) out.append(key, item);
  }
  // Sorted, so that the same parameters always produce the same string — which
  // is what makes a URL comparable in a test and cacheable by a proxy.
  out.sort();
  return out.toString();
}

/** The item endpoint declares no parameters but `expand`, and rejects any
 * other, so this encoder is deliberately not the list one. */
export function encodeItemQuery(query: { expand?: readonly string[] } = {}): string {
  const out = new URLSearchParams();
  if (query.expand?.length) out.set('expand', query.expand.join(','));
  return out.toString();
}

function itemPath(collection: string, id: string | number): string {
  return collection + '/' + encodeURIComponent(String(id));
}

// --------------------------------------------------------------- comments

/** A comment on a task. */
export interface Comment {
  id: string;
  workspace_id: string;
  task_id: string;
  author_id: string;
  body: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

/**
 * The request body for creating a Comment.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface CommentCreate {
  task_id: string;
  body: string;
}

// ------------------------------------------------------------------ lists

/** A named list of tasks within a workspace. */
export interface List {
  id: string;
  workspace_id: string;
  name: string;
  description: string;
  color: string;
  position: number;
  archived: boolean;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  /** Filled in by `expand: ['tasks']`, capped at 20 rows. */
  tasks?: Collection<Task>;
}

/**
 * The request body for creating a List.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface ListCreate {
  name: string;
  description: string;
  color?: string;
  position?: number;
  archived?: boolean;
}

/**
 * The request body for patching a List.
 *
 * Every property is optional, so a request writes only the columns it
 * names. Immutable columns are absent: they are settable once, at create.
 * Sending `null` for a nullable column writes NULL; omitting it changes
 * nothing, which is the distinction the server reads off the JSON body.
 */
export interface ListPatch {
  name?: string;
  description?: string;
  color?: string;
  position?: number;
  archived?: boolean;
}

// ------------------------------------------------------------ memberships

/** The memberships.role column's value set. */
export type MembershipRole = 'owner' | 'admin' | 'member';

/** A user's membership of a workspace, and their role in it. */
export interface Membership {
  id: string;
  workspace_id: string;
  user_id: string;
  role: MembershipRole;
  created_at: string;
  updated_at: string;
}

/**
 * The request body for creating a Membership.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface MembershipCreate {
  user_id: string;
  role?: MembershipRole;
}

// ------------------------------------------------------------------ tasks

/** The tasks.status column's value set. */
export type TaskStatus = 'todo' | 'in_progress' | 'blocked' | 'done';

/** The tasks.priority column's value set. */
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';

/** A unit of work, belonging to one list. */
export interface Task {
  id: string;
  workspace_id: string;
  list_id: string;
  /** Filled in by `expand: ['list']`, absent otherwise. */
  list?: List;
  assignee_id: string | null;
  author_id: string;
  title: string;
  description: string;
  status: TaskStatus;
  priority: TaskPriority;
  due_at: string | null;
  completed_at: string | null;
  position: number;
  comment_count: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

/**
 * The request body for creating a Task.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface TaskCreate {
  list_id: string;
  assignee_id?: string | null;
  title: string;
  description: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  due_at?: string | null;
  position?: number;
}

/**
 * The request body for patching a Task.
 *
 * Every property is optional, so a request writes only the columns it
 * names. Immutable columns are absent: they are settable once, at create.
 * Sending `null` for a nullable column writes NULL; omitting it changes
 * nothing, which is the distinction the server reads off the JSON body.
 */
export interface TaskPatch {
  list_id?: string;
  assignee_id?: string | null;
  title?: string;
  description?: string;
  status?: TaskStatus;
  priority?: TaskPriority;
  due_at?: string | null;
  position?: number;
}

// ------------------------------------------------------------------ users

/** A row of users. */
export interface User {
  id: string;
  email: string;
  name: string;
  created_at: string;
  updated_at: string;
}

// ------------------------------------------------------------- workspaces

/** A tenant. Lists, tasks and comments all belong to exactly one. */
export interface Workspace {
  id: string;
  name: string;
  slug: string;
  created_at: string;
  updated_at: string;
}

// -------------------------------------------------------------- /comments

/** Columns `select` may name. The primary key is always returned. */
export type CommentColumn =
  | 'id'
  | 'workspace_id'
  | 'task_id'
  | 'author_id'
  | 'body'
  | 'created_at'
  | 'updated_at'
  | 'deleted_at';

/** Sortable columns, with their descending forms. */
export type CommentSort = 'created_at' | '-created_at' | 'updated_at' | '-updated_at';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type CommentWhere = {
  id?: Cond<string>;
  workspace_id?: Cond<string>;
  task_id?: Cond<string>;
  author_id?: Cond<string>;
  body?: Cond<string, TextMatch>;
};

/** Parameters for `GET /comments`. */
export interface CommentListParams<S extends CommentColumn = CommentColumn> {
  where?: CommentWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: CommentSort | readonly CommentSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /comments/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export type CommentGetParams = Record<string, never>;

/**
 * A Comment as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type CommentRow<S extends CommentColumn = CommentColumn> =
  Pick<Comment, S | 'id'>;

/** `GET /comments` — the filtered, sorted, paged collection. */
export function listComments<S extends CommentColumn = CommentColumn>(
  request: Transport,
  params: CommentListParams<S> = {},
  signal?: AbortSignal,
): Promise<Page<CommentRow<S>>> {
  return request({ method: 'GET', path: '/comments', query: encodeListQuery(params), signal });
}

/** `GET /comments/{id}` — one row by primary key. */
export function getComment(
  request: Transport,
  id: string | number,
  params: CommentGetParams = {},
  signal?: AbortSignal,
): Promise<CommentRow<CommentColumn>> {
  return request({ method: 'GET', path: itemPath('/comments', id), query: encodeItemQuery(params), signal });
}

/** `POST /comments` — create a row. */
export function createComment(request: Transport, body: CommentCreate, signal?: AbortSignal): Promise<Comment> {
  return request({ method: 'POST', path: '/comments', body, signal });
}

/**
 * Cache keys for /comments. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const commentKeys = {
  all: () => ['comments'] as const,
  lists: () => ['comments', 'list'] as const,
  list: (params: unknown = {}) => ['comments', 'list', params] as const,
  infinite: (params: unknown = {}) => ['comments', 'infinite', params] as const,
  details: () => ['comments', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['comments', 'detail', String(id), params] as const,
};

// ----------------------------------------------------------------- /lists

/** Columns `select` may name. The primary key is always returned. */
export type ListColumn =
  | 'id'
  | 'workspace_id'
  | 'name'
  | 'description'
  | 'color'
  | 'position'
  | 'archived'
  | 'created_at'
  | 'updated_at'
  | 'deleted_at';

/** Sortable columns, with their descending forms. */
export type ListSort =
  | 'name'
  | '-name'
  | 'position'
  | '-position'
  | 'archived'
  | '-archived'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/** Relations `expand` may name. */
export type ListExpand = 'tasks';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type ListWhere = {
  id?: Cond<string>;
  workspace_id?: Cond<string>;
  name?: Cond<string, TextMatch>;
  description?: Cond<string, TextMatch>;
  color?: Cond<string, TextMatch>;
  archived?: Cond<boolean>;
};

/** Parameters for `GET /lists`. */
export interface ListListParams<S extends ListColumn = ListColumn, E extends ListExpand = never> {
  where?: ListWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: ListSort | readonly ListSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  expand?: readonly E[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /lists/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export interface ListGetParams<E extends ListExpand = never> {
  expand?: readonly E[];
}

/**
 * A List as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type ListRow<S extends ListColumn = ListColumn, E extends ListExpand = never> =
  Pick<List, S | 'id'>
  & ('tasks' extends E ? { tasks: Collection<Task> } : unknown);

/** `GET /lists` — the filtered, sorted, paged collection. */
export function listLists<S extends ListColumn = ListColumn, E extends ListExpand = never>(
  request: Transport,
  params: ListListParams<S, E> = {},
  signal?: AbortSignal,
): Promise<Page<ListRow<S, E>>> {
  return request({ method: 'GET', path: '/lists', query: encodeListQuery(params), signal });
}

/** `GET /lists/{id}` — one row by primary key. */
export function getList<E extends ListExpand = never>(
  request: Transport,
  id: string | number,
  params: ListGetParams<E> = {},
  signal?: AbortSignal,
): Promise<ListRow<ListColumn, E>> {
  return request({ method: 'GET', path: itemPath('/lists', id), query: encodeItemQuery(params), signal });
}

/** `POST /lists` — create a row. */
export function createList(request: Transport, body: ListCreate, signal?: AbortSignal): Promise<List> {
  return request({ method: 'POST', path: '/lists', body, signal });
}

/** `PATCH /lists/{id}` — write the columns the body names, and no others. */
export function updateList(request: Transport, id: string | number, body: ListPatch, signal?: AbortSignal): Promise<List> {
  return request({ method: 'PATCH', path: itemPath('/lists', id), body, signal });
}

/**
 * Cache keys for /lists. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const listKeys = {
  all: () => ['lists'] as const,
  lists: () => ['lists', 'list'] as const,
  list: (params: unknown = {}) => ['lists', 'list', params] as const,
  infinite: (params: unknown = {}) => ['lists', 'infinite', params] as const,
  details: () => ['lists', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['lists', 'detail', String(id), params] as const,
};

// ----------------------------------------------------------- /memberships

/** Columns `select` may name. The primary key is always returned. */
export type MembershipColumn =
  | 'id'
  | 'workspace_id'
  | 'user_id'
  | 'role'
  | 'created_at'
  | 'updated_at';

/** Sortable columns, with their descending forms. */
export type MembershipSort =
  | 'role'
  | '-role'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type MembershipWhere = {
  id?: Cond<string>;
  workspace_id?: Cond<string>;
  user_id?: Cond<string>;
  role?: Cond<MembershipRole>;
};

/** Parameters for `GET /memberships`. */
export interface MembershipListParams<S extends MembershipColumn = MembershipColumn> {
  where?: MembershipWhere;
  /** Ordering, most significant first. */
  sort?: MembershipSort | readonly MembershipSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /memberships/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export type MembershipGetParams = Record<string, never>;

/**
 * A Membership as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type MembershipRow<S extends MembershipColumn = MembershipColumn> =
  Pick<Membership, S | 'id'>;

/** `GET /memberships` — the filtered, sorted, paged collection. */
export function listMemberships<S extends MembershipColumn = MembershipColumn>(
  request: Transport,
  params: MembershipListParams<S> = {},
  signal?: AbortSignal,
): Promise<Page<MembershipRow<S>>> {
  return request({ method: 'GET', path: '/memberships', query: encodeListQuery(params), signal });
}

/** `GET /memberships/{id}` — one row by primary key. */
export function getMembership(
  request: Transport,
  id: string | number,
  params: MembershipGetParams = {},
  signal?: AbortSignal,
): Promise<MembershipRow<MembershipColumn>> {
  return request({ method: 'GET', path: itemPath('/memberships', id), query: encodeItemQuery(params), signal });
}

/** `POST /memberships` — create a row. */
export function createMembership(request: Transport, body: MembershipCreate, signal?: AbortSignal): Promise<Membership> {
  return request({ method: 'POST', path: '/memberships', body, signal });
}

/** `DELETE /memberships/{id}`. */
export function deleteMembership(request: Transport, id: string | number, signal?: AbortSignal): Promise<void> {
  return request({ method: 'DELETE', path: itemPath('/memberships', id), signal });
}

/**
 * Cache keys for /memberships. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const membershipKeys = {
  all: () => ['memberships'] as const,
  lists: () => ['memberships', 'list'] as const,
  list: (params: unknown = {}) => ['memberships', 'list', params] as const,
  infinite: (params: unknown = {}) => ['memberships', 'infinite', params] as const,
  details: () => ['memberships', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['memberships', 'detail', String(id), params] as const,
};

// ----------------------------------------------------------------- /tasks

/** Columns `select` may name. The primary key is always returned. */
export type TaskColumn =
  | 'id'
  | 'workspace_id'
  | 'list_id'
  | 'assignee_id'
  | 'author_id'
  | 'title'
  | 'description'
  | 'status'
  | 'priority'
  | 'due_at'
  | 'completed_at'
  | 'position'
  | 'comment_count'
  | 'created_at'
  | 'updated_at'
  | 'deleted_at';

/** Sortable columns, with their descending forms. */
export type TaskSort =
  | 'title'
  | '-title'
  | 'status'
  | '-status'
  | 'priority'
  | '-priority'
  | 'due_at'
  | '-due_at'
  | 'completed_at'
  | '-completed_at'
  | 'position'
  | '-position'
  | 'comment_count'
  | '-comment_count'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/** Relations `expand` may name. */
export type TaskExpand = 'list';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type TaskWhere = {
  id?: Cond<string>;
  workspace_id?: Cond<string>;
  list_id?: Cond<string>;
  assignee_id?: Cond<string, NullCheck>;
  title?: Cond<string, TextMatch>;
  description?: Cond<string, TextMatch>;
  status?: Cond<TaskStatus>;
  priority?: Cond<TaskPriority>;
  due_at?: Cond<string | Date, NullCheck>;
  completed_at?: Cond<string | Date, NullCheck>;
  comment_count?: Cond<number>;
};

/** Parameters for `GET /tasks`. */
export interface TaskListParams<S extends TaskColumn = TaskColumn, E extends TaskExpand = never> {
  where?: TaskWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: TaskSort | readonly TaskSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  expand?: readonly E[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /tasks/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export interface TaskGetParams<E extends TaskExpand = never> {
  expand?: readonly E[];
}

/**
 * A Task as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type TaskRow<S extends TaskColumn = TaskColumn, E extends TaskExpand = never> =
  Pick<Task, S | 'id'>
  & ('list' extends E ? { list: List } : unknown);

/** `GET /tasks` — the filtered, sorted, paged collection. */
export function listTasks<S extends TaskColumn = TaskColumn, E extends TaskExpand = never>(
  request: Transport,
  params: TaskListParams<S, E> = {},
  signal?: AbortSignal,
): Promise<Page<TaskRow<S, E>>> {
  return request({ method: 'GET', path: '/tasks', query: encodeListQuery(params), signal });
}

/** `GET /tasks/{id}` — one row by primary key. */
export function getTask<E extends TaskExpand = never>(
  request: Transport,
  id: string | number,
  params: TaskGetParams<E> = {},
  signal?: AbortSignal,
): Promise<TaskRow<TaskColumn, E>> {
  return request({ method: 'GET', path: itemPath('/tasks', id), query: encodeItemQuery(params), signal });
}

/** `POST /tasks` — create a row. */
export function createTask(request: Transport, body: TaskCreate, signal?: AbortSignal): Promise<Task> {
  return request({ method: 'POST', path: '/tasks', body, signal });
}

/** `PATCH /tasks/{id}` — write the columns the body names, and no others. */
export function updateTask(request: Transport, id: string | number, body: TaskPatch, signal?: AbortSignal): Promise<Task> {
  return request({ method: 'PATCH', path: itemPath('/tasks', id), body, signal });
}

/**
 * Cache keys for /tasks. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const taskKeys = {
  all: () => ['tasks'] as const,
  lists: () => ['tasks', 'list'] as const,
  list: (params: unknown = {}) => ['tasks', 'list', params] as const,
  infinite: (params: unknown = {}) => ['tasks', 'infinite', params] as const,
  details: () => ['tasks', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['tasks', 'detail', String(id), params] as const,
};

// ----------------------------------------------------------------- /users

/** Columns `select` may name. The primary key is always returned. */
export type UserColumn =
  | 'id'
  | 'email'
  | 'name'
  | 'created_at'
  | 'updated_at';

/** Sortable columns, with their descending forms. */
export type UserSort =
  | 'name'
  | '-name'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type UserWhere = {
  id?: Cond<string>;
  email?: Cond<string, TextMatch>;
  name?: Cond<string, TextMatch>;
};

/** Parameters for `GET /users`. */
export interface UserListParams<S extends UserColumn = UserColumn> {
  where?: UserWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: UserSort | readonly UserSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /users/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export type UserGetParams = Record<string, never>;

/**
 * A User as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type UserRow<S extends UserColumn = UserColumn> =
  Pick<User, S | 'id'>;

/** `GET /users` — the filtered, sorted, paged collection. */
export function listUsers<S extends UserColumn = UserColumn>(
  request: Transport,
  params: UserListParams<S> = {},
  signal?: AbortSignal,
): Promise<Page<UserRow<S>>> {
  return request({ method: 'GET', path: '/users', query: encodeListQuery(params), signal });
}

/** `GET /users/{id}` — one row by primary key. */
export function getUser(
  request: Transport,
  id: string | number,
  params: UserGetParams = {},
  signal?: AbortSignal,
): Promise<UserRow<UserColumn>> {
  return request({ method: 'GET', path: itemPath('/users', id), query: encodeItemQuery(params), signal });
}

/**
 * Cache keys for /users. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const userKeys = {
  all: () => ['users'] as const,
  lists: () => ['users', 'list'] as const,
  list: (params: unknown = {}) => ['users', 'list', params] as const,
  infinite: (params: unknown = {}) => ['users', 'infinite', params] as const,
  details: () => ['users', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['users', 'detail', String(id), params] as const,
};

// ------------------------------------------------------------ /workspaces

/** Columns `select` may name. The primary key is always returned. */
export type WorkspaceColumn =
  | 'id'
  | 'name'
  | 'slug'
  | 'created_at'
  | 'updated_at';

/** Sortable columns, with their descending forms. */
export type WorkspaceSort =
  | 'name'
  | '-name'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type WorkspaceWhere = {
  id?: Cond<string>;
  name?: Cond<string, TextMatch>;
  slug?: Cond<string, TextMatch>;
};

/** Parameters for `GET /workspaces`. */
export interface WorkspaceListParams<S extends WorkspaceColumn = WorkspaceColumn> {
  where?: WorkspaceWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: WorkspaceSort | readonly WorkspaceSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /workspaces/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export type WorkspaceGetParams = Record<string, never>;

/**
 * A Workspace as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type WorkspaceRow<S extends WorkspaceColumn = WorkspaceColumn> =
  Pick<Workspace, S | 'id'>;

/** `GET /workspaces` — the filtered, sorted, paged collection. */
export function listWorkspaces<S extends WorkspaceColumn = WorkspaceColumn>(
  request: Transport,
  params: WorkspaceListParams<S> = {},
  signal?: AbortSignal,
): Promise<Page<WorkspaceRow<S>>> {
  return request({ method: 'GET', path: '/workspaces', query: encodeListQuery(params), signal });
}

/** `GET /workspaces/{id}` — one row by primary key. */
export function getWorkspace(
  request: Transport,
  id: string | number,
  params: WorkspaceGetParams = {},
  signal?: AbortSignal,
): Promise<WorkspaceRow<WorkspaceColumn>> {
  return request({ method: 'GET', path: itemPath('/workspaces', id), query: encodeItemQuery(params), signal });
}

/**
 * Cache keys for /workspaces. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const workspaceKeys = {
  all: () => ['workspaces'] as const,
  lists: () => ['workspaces', 'list'] as const,
  list: (params: unknown = {}) => ['workspaces', 'list', params] as const,
  infinite: (params: unknown = {}) => ['workspaces', 'infinite', params] as const,
  details: () => ['workspaces', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['workspaces', 'detail', String(id), params] as const,
};

// ------------------------------------------------------------ change feed

/**
 * Key factories by table name, for a subscriber that receives a table and a
 * row key and has to decide what to refetch.
 */
export const keysByTable = {
  comments: commentKeys,
  lists: listKeys,
  memberships: membershipKeys,
  tasks: taskKeys,
  users: userKeys,
  workspaces: workspaceKeys,
} as const;

export type TableName = keyof typeof keysByTable;
