// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.
//
// The part of the client that does not depend on any schema: the response
// envelopes, the problem document, the transport signature and the encoder for
// the filter grammar.
//
// It is a file of its own so that an application with more than one generated
// module has one copy rather than N — one Page, one Problem, one Transport to
// wire — and so a shared pager or error boundary can be written once. A client
// re-exports everything here, so importing it from the client keeps working
// (ADR-0028, issue #110).
//
// It imports nothing, and it is derived from nothing schema-specific: two
// projects generating it produce the same bytes.

// ------------------------------------------------------------------- runtime

/** A capped set of expanded child rows. `has_more` reports truncation, which a
 * bare array could not, so a caller reading twenty of two hundred can tell. */
export interface Collection<T> {
  items: T[];
  has_more: boolean;
}

/** The body of every list response: a collection, plus where in the walk it is.
 *
 * It extends Collection rather than restating it, because an expansion returns
 * a strict subset of these fields and two hand-written shapes would be free to
 * drift. */
export interface Page<T> extends Collection<T> {
  page: number;
  per_page: number;
  /** The position to resume from, present whenever a next page exists. Prefer it
   * to `page`: it costs the same at any depth and cannot skip or repeat a row
   * when the table is written to mid-walk. */
  next_cursor?: string;
  /** Total matching rows, present only when `count: 'exact'` was asked for. */
  total?: number;
}

/** One rejected parameter or field. */
export interface ProblemDetail {
  message: string;
  /** Where the problem is, e.g. `query.sort`. */
  location?: string;
  value?: unknown;
  /** What would have been accepted instead, where the set is finite. This is the
   * half of an error that turns a dead end into a fix, and it is why the client
   * carries an error type at all. */
  allowed?: string[];
}

/** The RFC 9457 problem document every rejection returns. */
export interface Problem {
  type?: string;
  title?: string;
  status?: number;
  detail?: string;
  errors?: ProblemDetail[];
}

/** Narrows an unknown error body to a Problem. */
export function isProblem(value: unknown): value is Problem {
  if (typeof value !== 'object' || value === null) return false;
  const p = value as Problem;
  return typeof p.status === 'number' || Array.isArray(p.errors);
}

/** The allowed values a rejection named for one parameter, e.g.
 * `allowedFor(problem, 'query.sort')`. */
export function allowedFor(problem: Problem, location: string): string[] {
  return problem.errors?.find((e) => e.location === location)?.allowed ?? [];
}

/** One request, as the generated functions describe it. */
export interface ApiRequest {
  method: 'GET' | 'POST' | 'PATCH' | 'DELETE';
  /** Path from the API root, already encoded, e.g. `/tasks/1`. */
  path: string;
  /** Encoded query string without the leading `?`. */
  query?: string;
  body?: unknown;
  signal?: AbortSignal;
}

/**
 * The application's request function.
 *
 * Everything not derivable from the schema lives behind this: the base URL,
 * the auth header, refresh, retry, and what a 401 does. A minimal one:
 *
 *     const request: Transport = async ({ method, path, query, body, signal }) => {
 *       const res = await fetch(`${base}${path}${query ? '?' + query : ''}`, {
 *         method,
 *         headers: { ...(body ? { 'content-type': 'application/json' } : {}), ...auth() },
 *         body: body === undefined ? undefined : JSON.stringify(body),
 *         signal,
 *       });
 *       if (!res.ok) throw await res.json();
 *       return res.status === 204 ? (undefined as never) : res.json();
 *     };
 */
export type Transport = <T>(request: ApiRequest) => Promise<T>;

/** Operators every column type accepts. */
export interface Comparison<V> {
  eq?: V;
  ne?: V;
  gt?: V;
  gte?: V;
  lt?: V;
  lte?: V;
  in?: readonly V[];
  nin?: readonly V[];
  between?: readonly [V, V];
}

/** Null tests, offered only by nullable columns. */
export interface NullCheck {
  isnull?: boolean;
  notnull?: boolean;
}

/** Pattern operators, offered only by text columns. */
export interface TextMatch {
  like?: string;
  ilike?: string;
  /** Case-insensitive substring. The value is escaped, so `50%` matches that
   * literal string rather than everything. */
  contains?: string;
  startswith?: string;
  endswith?: string;
}

/** Containment operators, offered only by array columns. The substring
 * operator is absent on purpose: it belongs to text, and one name meaning two
 * things depending on the column would put back the ambiguity this client
 * exists to remove. */
export interface ArrayComparison<E> {
  /** The whole array, compared element by element. */
  eq?: readonly E[];
  ne?: readonly E[];
  /** The array contains this element. */
  has?: E;
  /** The array shares at least one element with these. */
  hasany?: readonly E[];
  /** The array contains all of these. */
  hasall?: readonly E[];
  /** The array does not contain this element.
   *
   * The `n`-prefixed operators are negations, not complements: a row whose
   * column is null matches neither `has` nor `nhas`. Pair one with
   * `isnull` when the null rows should be included. */
  nhas?: E;
  /** The array shares no element with these. */
  nhasany?: readonly E[];
  /** The array is missing at least one of these. */
  nhasall?: readonly E[];
}

/** One column's filter: a bare value for equality, or an operator object. */
export type Cond<V, Extra = unknown> = V | (Comparison<V> & Extra);

/** One array column's filter: a bare array for whole-array equality, or an
 * operator object. */
export type ArrayCond<E, Extra = unknown> = readonly E[] | (ArrayComparison<E> & Extra);

type Scalar = string | number | boolean | Date;

function encodeScalar(v: Scalar): string {
  return v instanceof Date ? v.toISOString() : String(v);
}

/** A member of a comma-separated list is quoted when it carries a comma or a
 * quote, which is how the server's parser reads it back whole. */
function encodeMember(v: Scalar): string {
  const s = encodeScalar(v);
  return /[,"]/.test(s) ? '"' + s.replace(/"/g, '\\"') + '"' : s;
}

function appendCond(out: URLSearchParams, column: string, cond: unknown): void {
  if (cond === undefined) return;
  // A bare null is read as a null test rather than as an equality against NULL,
  // which is not a comparison SQL would answer true to anyway.
  if (cond === null) {
    out.append(column, 'isnull');
    return;
  }
  // A bare array is a whole-array equality, the same way a bare scalar is a
  // scalar one. It is checked before the object branch because an array is an
  // object.
  if (Array.isArray(cond)) {
    out.append(column, 'eq.' + (cond as Scalar[]).map(encodeMember).join(','));
    return;
  }
  if (typeof cond !== 'object' || cond instanceof Date) {
    out.append(column, 'eq.' + encodeScalar(cond as Scalar));
    return;
  }
  // Repeating a parameter conjoins its conditions, so an object with two
  // operators becomes two parameters rather than one compound value.
  for (const [op, value] of Object.entries(cond as Record<string, unknown>)) {
    if (value === undefined || value === null) continue;
    switch (op) {
      case 'isnull':
      case 'notnull':
        if (value) out.append(column, op);
        break;
      case 'in':
      case 'nin':
      case 'hasany':
      case 'hasall':
      case 'nhasany':
      case 'nhasall':
        out.append(column, op + '.' + (value as Scalar[]).map(encodeMember).join(','));
        break;
      case 'between': {
        const [lo, hi] = value as [Scalar, Scalar];
        out.append(column, 'between.' + encodeMember(lo) + ',' + encodeMember(hi));
        break;
      }
      default:
        // eq and ne against an array column carry the whole array.
        if (Array.isArray(value)) {
          out.append(column, op + '.' + (value as Scalar[]).map(encodeMember).join(','));
          break;
        }
        out.append(column, op + '.' + encodeScalar(value as Scalar));
    }
  }
}

/** The shape encodeListQuery reads. Each resource's params type is one of
 * these with its columns and operators pinned. */
export interface ListQuery {
  where?: Record<string, unknown>;
  search?: string;
  sort?: string | readonly string[];
  select?: readonly string[];
  expand?: readonly string[];
  page?: number;
  per_page?: number;
  cursor?: string;
  count?: 'exact';
  params?: Record<string, string | readonly string[]>;
}

/**
 * Encodes list parameters into the server's query grammar.
 *
 * This is the piece hand-written clients open-code and get subtly wrong: the
 * operator prefixes, the repeated parameters that conjoin, and the quoting
 * inside a value list.
 */
export function encodeListQuery(query: ListQuery = {}): string {
  const out = new URLSearchParams();
  for (const [column, cond] of Object.entries(query.where ?? {})) appendCond(out, column, cond);
  if (query.search) out.set('search', query.search);
  if (query.sort) out.set('sort', typeof query.sort === 'string' ? query.sort : query.sort.join(','));
  if (query.select?.length) out.set('select', query.select.join(','));
  if (query.expand?.length) out.set('expand', query.expand.join(','));
  if (query.page !== undefined) out.set('page', String(query.page));
  if (query.per_page !== undefined) out.set('per_page', String(query.per_page));
  if (query.cursor !== undefined) out.set('cursor', query.cursor);
  if (query.count !== undefined) out.set('count', query.count);
  for (const [key, value] of Object.entries(query.params ?? {})) {
    for (const item of Array.isArray(value) ? value : [value as string]) out.append(key, item);
  }
  // Sorted, so that the same parameters always produce the same string — which
  // is what makes a URL comparable in a test and cacheable by a proxy.
  out.sort();
  return out.toString();
}

/** The item endpoint declares no parameters but `expand`, and rejects any
 * other, so this encoder is deliberately not the list one. */
export function encodeItemQuery(query: { expand?: readonly string[] } = {}): string {
  const out = new URLSearchParams();
  if (query.expand?.length) out.set('expand', query.expand.join(','));
  return out.toString();
}

/** The path of one row: the collection, then the id, encoded.
 *
 * Exported because the per-schema client calls it, and it is the same helper
 * the Go client exports as ItemPath. */
export function itemPath(collection: string, id: string | number): string {
  return collection + '/' + encodeURIComponent(String(id));
}
