// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.

package cli

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// ------------------------------------------------------------------- runtime

// Request is one call to the API, as the generated commands describe it.
type Request struct {
	Method string
	// Path is measured from the API root and already encoded, e.g. "/tasks/6b1e".
	Path string
	// Query is the source of the query string. Repeating a key conjoins filter
	// conditions, which is why this is url.Values rather than a map of strings.
	Query url.Values
	// Body is marshalled as JSON when it is not nil.
	Body any
}

// Transport issues one request and returns the decoded response body, or nil
// where the response carried none.
//
// Everything the schema cannot derive lives behind this: the base URL, the
// credential, retry, and what a 401 does. Client implements one over net/http,
// and setting Client.Transport replaces it — which is the seam to use for a
// test that must not open a socket, or for a caller whose auth is a signature
// rather than a bearer token.
type Transport func(ctx context.Context, req Request) (json.RawMessage, error)

// Client is the configuration a schema cannot supply. The root command binds
// its fields to persistent flags.
type Client struct {
	// BaseURL is the root of the API, without a trailing slash.
	BaseURL string
	// Token is sent as an Authorization: Bearer header when it is set.
	Token string
	// Timeout bounds a single request. Zero means no timeout.
	Timeout time.Duration
	// Compact writes each response on one line rather than indenting it.
	Compact bool
	// Verbose logs each request's method and URL to Stderr.
	Verbose bool

	// HTTP is the client the built-in transport issues requests through.
	// Leaving it nil builds one from Timeout.
	HTTP *http.Client
	// Transport replaces the built-in one entirely. Set it and BaseURL, Token,
	// Timeout and HTTP are yours to honour or ignore.
	//
	// Do is still reachable, and does not consult this field, so wrapping the
	// built-in transport rather than replacing it is a closure that ends in a
	// call to it:
	//
	//	c.Transport = func(ctx context.Context, req Request) (json.RawMessage, error) {
	//	    req.Query.Set("trace", traceID(ctx))
	//	    return c.Do(ctx, req)
	//	}
	Transport Transport
	// Stderr receives verbose logging. Defaults to os.Stderr.
	Stderr io.Writer
}

// maxResponseBytes caps what one response may occupy in memory. A page is
// bounded by the resource's ceiling, so reaching this means something upstream
// is not the API this client was generated against.
const maxResponseBytes = 64 << 20

func (c *Client) stderr() io.Writer {
	if c.Stderr != nil {
		return c.Stderr
	}
	return os.Stderr
}

func (c *Client) transport() Transport {
	if c.Transport != nil {
		return c.Transport
	}
	return c.Do
}

// Do is the built-in transport, over net/http.
//
// It is exported so that a caller replacing Transport can still delegate to
// it; it does not consult Transport itself, so doing so cannot recurse.
func (c *Client) Do(ctx context.Context, req Request) (json.RawMessage, error) {
	base := strings.TrimSuffix(c.BaseURL, "/")
	if base == "" {
		return nil, errors.New("no API address: pass --base-url")
	}
	u := base + req.Path
	if len(req.Query) > 0 {
		// Encode sorts by key, so the same flags always produce the same URL —
		// which is what makes a request comparable in a log and cacheable by a
		// proxy in front of the API.
		u += "?" + req.Query.Encode()
	}

	var payload io.Reader
	if req.Body != nil {
		raw, err := json.Marshal(req.Body)
		if err != nil {
			return nil, fmt.Errorf("encoding the request body: %w", err)
		}
		payload = bytes.NewReader(raw)
	}

	r, err := http.NewRequestWithContext(ctx, req.Method, u, payload)
	if err != nil {
		return nil, err
	}
	r.Header.Set("Accept", "application/json")
	if req.Body != nil {
		r.Header.Set("Content-Type", "application/json")
	}
	if c.Token != "" {
		r.Header.Set("Authorization", "Bearer "+c.Token)
	}
	if c.Verbose {
		fmt.Fprintln(c.stderr(), req.Method, u)
	}

	client := c.HTTP
	if client == nil {
		client = &http.Client{Timeout: c.Timeout}
	}
	resp, err := client.Do(r)
	if err != nil {
		return nil, err
	}
	defer func() { _ = resp.Body.Close() }()

	body, err := io.ReadAll(io.LimitReader(resp.Body, maxResponseBytes))
	if err != nil {
		return nil, fmt.Errorf("reading the response: %w", err)
	}
	if resp.StatusCode >= 400 {
		return nil, problemFrom(resp.StatusCode, body)
	}
	if resp.StatusCode == http.StatusNoContent || len(bytes.TrimSpace(body)) == 0 {
		return nil, nil
	}
	return json.RawMessage(body), nil
}

// run issues one request and writes the response to the command's stdout.
func (c *Client) run(cmd *cobra.Command, req Request, all bool) error {
	ctx := cmd.Context()
	if ctx == nil {
		ctx = context.Background()
	}

	var (
		raw json.RawMessage
		err error
	)
	if all {
		raw, err = listAll(ctx, c.transport(), req)
	} else {
		raw, err = c.transport()(ctx, req)
	}
	if err != nil {
		return err
	}
	// A delete answers 204, and there is nothing to print. Writing "null" would
	// make a shell test for emptiness fail.
	if len(raw) == 0 {
		return nil
	}
	return writeJSON(cmd.OutOrStdout(), raw, c.Compact)
}

// listAll walks a collection by cursor and returns every row as one page.
//
// This is the loop a caller writes by hand, and it pages with `?cursor=` rather
// than `?page=`: a walk that counts to its position costs more with every page
// and can read a row twice when the table is written to underneath it, which is
// exactly what a long walk makes likely.
func listAll(ctx context.Context, t Transport, req Request) (json.RawMessage, error) {
	type page struct {
		Items      []json.RawMessage `json:"items"`
		HasMore    bool              `json:"has_more"`
		NextCursor *string           `json:"next_cursor,omitempty"`
		Total      *int64            `json:"total,omitempty"`
	}

	out := page{Items: []json.RawMessage{}}
	q := cloneValues(req.Query)
	seen := map[string]bool{}

	for {
		req.Query = q
		raw, err := t(ctx, req)
		if err != nil {
			return nil, err
		}
		var p page
		if err := json.Unmarshal(raw, &p); err != nil {
			return nil, fmt.Errorf("walking the collection: the response is not a list page: %w", err)
		}
		out.Items = append(out.Items, p.Items...)
		// The total describes the whole result set rather than the page, so the
		// first response's answer is the answer.
		if out.Total == nil {
			out.Total = p.Total
		}
		if p.NextCursor == nil || *p.NextCursor == "" {
			break
		}
		// A server that answered with the cursor it was handed would otherwise
		// spin here forever, reading one page over and over.
		if seen[*p.NextCursor] {
			return nil, fmt.Errorf("the server repeated cursor %q; stopping rather than paging forever", *p.NextCursor)
		}
		seen[*p.NextCursor] = true

		q = cloneValues(q)
		q.Set("cursor", *p.NextCursor)
		// A cursor names a position, so a page number or an offset alongside it
		// is a second, contradictory answer to the same question.
		q.Del("page")
		q.Del("offset")
	}
	return json.Marshal(out)
}

func cloneValues(v url.Values) url.Values {
	out := make(url.Values, len(v))
	for k, values := range v {
		out[k] = append([]string(nil), values...)
	}
	return out
}

// writeJSON writes a response body, indented unless asked otherwise.
func writeJSON(w io.Writer, raw json.RawMessage, compact bool) error {
	var buf bytes.Buffer
	if compact {
		if err := json.Compact(&buf, raw); err != nil {
			return err
		}
	} else if err := json.Indent(&buf, raw, "", "  "); err != nil {
		return err
	}
	buf.WriteByte('\n')
	_, err := w.Write(buf.Bytes())
	return err
}

// Problem is the RFC 9457 document every rejection returns.
type Problem struct {
	Type   string `json:"type,omitempty"`
	Title  string `json:"title,omitempty"`
	Status int    `json:"status,omitempty"`
	Detail string `json:"detail,omitempty"`
	// Errors lists every problem found, not only the first, so a malformed
	// request takes one round trip to fix rather than one per mistake.
	Errors []*ProblemDetail `json:"errors,omitempty"`
}

// ProblemDetail is one rejected parameter or field.
type ProblemDetail struct {
	Message  string `json:"message"`
	Location string `json:"location,omitempty"`
	Value    any    `json:"value,omitempty"`
	// Allowed is what would have been accepted instead, where the set is
	// finite. It is the half of a rejection that turns a dead end into a fix,
	// and printing it is most of the reason this client renders errors itself
	// rather than echoing the response body.
	Allowed []string `json:"allowed,omitempty"`
}

// Error renders the document as the message the caller sees on stderr.
func (p *Problem) Error() string {
	head := p.Detail
	if head == "" {
		head = p.Title
	}
	if head == "" {
		head = "the request was rejected"
	}

	var b strings.Builder
	fmt.Fprintf(&b, "%s (HTTP %d)", head, p.Status)
	for _, d := range p.Errors {
		b.WriteString("\n  ")
		if d.Location != "" {
			b.WriteString(d.Location + ": ")
		}
		b.WriteString(d.Message)
		if len(d.Allowed) > 0 {
			fmt.Fprintf(&b, "\n    allowed: %s", strings.Join(d.Allowed, ", "))
		}
	}
	return b.String()
}

// problemFrom decodes an error response, falling back to the status line for a
// body this client did not produce — a proxy's 502 page, say.
func problemFrom(status int, body []byte) error {
	var p Problem
	if err := json.Unmarshal(body, &p); err == nil && (p.Status != 0 || p.Detail != "" || len(p.Errors) > 0) {
		if p.Status == 0 {
			p.Status = status
		}
		return &p
	}
	text := strings.TrimSpace(string(body))
	if len(text) > 512 {
		text = text[:512] + "..."
	}
	if text == "" {
		return errors.New("HTTP " + strconv.Itoa(status))
	}
	return errors.New("HTTP " + strconv.Itoa(status) + ": " + text)
}

// itemPath addresses one row. The path template is always {id} whatever the
// primary key column is called, because the URL names the resource's identity
// rather than its storage.
func itemPath(collection, id string) string {
	return collection + "/" + url.PathEscape(id)
}

// setNullFields records an explicit null for each named column.
//
// A value flag can say that a column is now empty; it cannot say that it is now
// null, and the two write different SQL. This is the command-line form of the
// presence map the generated patch body keeps for the same reason.
func setNullFields(body map[string]any, names, nullable []string) error {
	for _, name := range names {
		column := strings.ReplaceAll(name, "-", "_")
		if !containsString(nullable, column) {
			return fmt.Errorf("--set-null %s: not a nullable column of this resource; allowed: %s",
				name, strings.Join(nullable, ", "))
		}
		body[column] = nil
	}
	return nil
}

func containsString(list []string, s string) bool {
	for _, item := range list {
		if item == s {
			return true
		}
	}
	return false
}

func envOr(name, def string) string {
	if v := os.Getenv(name); v != "" {
		return v
	}
	return def
}

// orString and orDuration resolve one setting's default.
//
// Binding a flag writes its default into the variable, so a Client the caller
// configured would be overwritten by registration alone. Feeding its value in
// as the default instead gives the precedence a reader would expect: the flag
// wins over the field, the field over the environment, and the environment
// over the built-in.
func orString(configured, def string) string {
	if configured != "" {
		return configured
	}
	return def
}

func orDuration(configured, def time.Duration) time.Duration {
	if configured != 0 {
		return configured
	}
	return def
}

// normalizeFlag accepts a column's own spelling as well as the kebab-case one
// cobra conventionally uses, so a name read out of sqlb.json or out of an error
// response can be typed verbatim.
func normalizeFlag(_ *pflag.FlagSet, name string) pflag.NormalizedName {
	return pflag.NormalizedName(strings.ReplaceAll(name, "_", "-"))
}

// registerCompletion offers a fixed set of values for a flag.
//
// The error is dropped deliberately: it reports only that the flag does not
// exist, which would be a generator bug rather than a runtime condition, and
// the flag is declared one line above every call.
func registerCompletion(cmd *cobra.Command, flag string, values []string) {
	_ = cmd.RegisterFlagCompletionFunc(flag,
		func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return values, cobra.ShellCompDirectiveNoFileComp
		})
}

// New returns the root command.
//
// c carries what the schema cannot derive — the base URL, the credential, the
// timeout — and is bound to the persistent flags below. Pass nil for a client
// configured entirely from flags and the environment; pass one with Transport
// set to route every request through your own code instead.
//
//	func main() {
//	    if err := cli.New(nil).Execute(); err != nil {
//	        os.Exit(1)
//	    }
//	}
func New(c *Client) *cobra.Command {
	if c == nil {
		c = &Client{}
	}
	root := &cobra.Command{
		Use:   "taskctl",
		Short: "Command-line client for the taskctl API",
		Long: `taskctl drives the API generated from this project's sqlb schema.

Every response is written to stdout as JSON, so output pipes into jq without a
flag. Failures go to stderr and set a non-zero exit code; a rejected request
prints what the server would have accepted instead, which is usually the whole
fix.

Configuration comes from $TASKCTL_BASE_URL and $TASKCTL_TOKEN, or from --base-url
and --token.

Filtering, sorting, searching and expansion are restricted to the columns that
declared the capability, so a "list" command's --help is an exact statement of
what that resource accepts.`,
		SilenceUsage: true,
	}
	// Column names are snake_case, and cobra flags are conventionally kebab.
	// Accepting both spellings means a caller that read a column name out of
	// sqlb.json can type it verbatim.
	root.SetGlobalNormalizationFunc(normalizeFlag)

	flags := root.PersistentFlags()
	flags.StringVar(&c.BaseURL, "base-url", orString(c.BaseURL, envOr("TASKCTL_BASE_URL", "http://localhost:8080")),
		"Root of the API, without a trailing slash. Defaults to $TASKCTL_BASE_URL.")
	flags.StringVar(&c.Token, "token", orString(c.Token, os.Getenv("TASKCTL_TOKEN")),
		"Bearer token, sent as Authorization. Defaults to $TASKCTL_TOKEN, which is where it\n"+
			"belongs: a token on the command line is visible in the process list.")
	flags.DurationVar(&c.Timeout, "timeout", orDuration(c.Timeout, 30*time.Second), "Per-request timeout.")
	flags.BoolVar(&c.Compact, "compact", c.Compact,
		"Write each response as one line rather than indented.")
	flags.BoolVarP(&c.Verbose, "verbose", "v", c.Verbose,
		"Log each request's method and URL to stderr.")

	root.AddCommand(newCommentsCommand(c))
	root.AddCommand(newListsCommand(c))
	root.AddCommand(newMembershipsCommand(c))
	root.AddCommand(newTasksCommand(c))
	root.AddCommand(newUsersCommand(c))
	root.AddCommand(newWorkspacesCommand(c))
	return root
}

// ---------------------------------------------------------------- /comments

// newCommentsCommand groups the operations /comments exposes.
func newCommentsCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "comments",
		Short: "A comment on a task",
	}
	cmd.AddCommand(newCommentsListCommand(c))
	cmd.AddCommand(newCommentsGetCommand(c))
	cmd.AddCommand(newCommentsCreateCommand(c))
	return cmd
}

// newCommentsListCommand is GET /comments.
func newCommentsListCommand(c *Client) *cobra.Command {
	var (
		filterID          []string
		filterWorkspaceID []string
		filterTaskID      []string
		filterAuthorID    []string
		filterBody        []string
		sort              []string
		select_           []string
		search            string
		page              int
		perPage           int
		count             bool
		cursor            string
		all               bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List comments",
		Long: `A comment on a task.

GET /comments

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl comments list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl comments list --body contains.something

  # Ordered, and projected down to the columns about to be read
  taskctl comments list --sort -created_at --select id,workspace_id

  # Every matching row, walked by cursor rather than by page number
  taskctl comments list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterWorkspaceID {
				q.Add("workspace_id", v)
			}
			for _, v := range filterTaskID {
				q.Add("task_id", v)
			}
			for _, v := range filterAuthorID {
				q.Add("author_id", v)
			}
			for _, v := range filterBody {
				q.Add("body", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return c.run(cmd, Request{Method: http.MethodGet, Path: "/comments", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterWorkspaceID, "workspace-id", nil,
		`Filter on workspace_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterTaskID, "task-id", nil,
		`Filter on task_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterAuthorID, "author-id", nil,
		`Filter on author_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterBody, "body", nil,
		`Filter on body, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, workspace_id, task_id, author_id, body, created_at, updated_at, deleted_at.`)
	registerCompletion(cmd, "select", []string{"id", "workspace_id", "task_id", "author_id", "body", "created_at", "updated_at", "deleted_at"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across body.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newCommentsGetCommand is GET /comments/{id}.
func newCommentsGetCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one comment by primary key",
		Long: `GET /comments/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: "  taskctl comments get <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			return c.run(cmd, Request{Method: http.MethodGet, Path: itemPath("/comments", args[0]), Query: q}, false)
		},
	}
	return cmd
}

// newCommentsCreateCommand is Post /comments.
func newCommentsCreateCommand(c *Client) *cobra.Command {
	var (
		valTaskID string
		valBody   string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one comment",
		Args:  cobra.NoArgs,
		Long: `POST /comments

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl comments create --task-id <task_id> --body '<body>'",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("task-id") {
				body["task_id"] = valTaskID
			}
			if cmd.Flags().Changed("body") {
				body["body"] = valBody
			}
			return c.run(cmd, Request{Method: http.MethodPost, Path: "/comments", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valTaskID, "task-id", "",
		"UUID. References tasks. Required.")
	_ = cmd.MarkFlagRequired("task-id")
	flags.StringVar(&valBody, "body", "",
		"Required.")
	_ = cmd.MarkFlagRequired("body")
	return cmd
}

// ------------------------------------------------------------------- /lists

// newListsCommand groups the operations /lists exposes.
func newListsCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "lists",
		Short: "A named list of tasks within a workspace",
	}
	cmd.AddCommand(newListsListCommand(c))
	cmd.AddCommand(newListsGetCommand(c))
	cmd.AddCommand(newListsCreateCommand(c))
	cmd.AddCommand(newListsUpdateCommand(c))
	return cmd
}

// newListsListCommand is GET /lists.
func newListsListCommand(c *Client) *cobra.Command {
	var (
		filterID          []string
		filterWorkspaceID []string
		filterName        []string
		filterDescription []string
		filterColor       []string
		filterArchived    []string
		sort              []string
		select_           []string
		expand            []string
		search            string
		page              int
		perPage           int
		count             bool
		cursor            string
		all               bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List lists",
		Long: `A named list of tasks within a workspace.

GET /lists

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl lists list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl lists list --name contains.something

  # Ordered, and projected down to the columns about to be read
  taskctl lists list --sort -name --select id,workspace_id

  # Every matching row, walked by cursor rather than by page number
  taskctl lists list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterWorkspaceID {
				q.Add("workspace_id", v)
			}
			for _, v := range filterName {
				q.Add("name", v)
			}
			for _, v := range filterDescription {
				q.Add("description", v)
			}
			for _, v := range filterColor {
				q.Add("color", v)
			}
			for _, v := range filterArchived {
				q.Add("archived", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return c.run(cmd, Request{Method: http.MethodGet, Path: "/lists", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterWorkspaceID, "workspace-id", nil,
		`Filter on workspace_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterName, "name", nil,
		`Filter on name, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterDescription, "description", nil,
		`Filter on description, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterColor, "color", nil,
		`Filter on color, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterArchived, "archived", nil,
		`Filter on archived, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: name, position, archived, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"name", "-name", "position", "-position", "archived", "-archived", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, workspace_id, name, description, color, position, archived, created_at, updated_at, deleted_at.`)
	registerCompletion(cmd, "select", []string{"id", "workspace_id", "name", "description", "color", "position", "archived", "created_at", "updated_at", "deleted_at"})
	flags.StringSliceVar(&expand, "expand", nil,
		"Relations to embed in each row. Relations: tasks.")
	registerCompletion(cmd, "expand", []string{"tasks"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across name, description.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newListsGetCommand is GET /lists/{id}.
func newListsGetCommand(c *Client) *cobra.Command {
	var expand []string
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one list by primary key",
		Long: `GET /lists/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: `  taskctl lists get <id>

  # With tasks embedded, in one request
  taskctl lists get <id> --expand tasks`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			return c.run(cmd, Request{Method: http.MethodGet, Path: itemPath("/lists", args[0]), Query: q}, false)
		},
	}
	cmd.Flags().StringSliceVar(&expand, "expand", nil,
		"Relations to embed. Relations: tasks.")
	registerCompletion(cmd, "expand", []string{"tasks"})
	return cmd
}

// newListsCreateCommand is Post /lists.
func newListsCreateCommand(c *Client) *cobra.Command {
	var (
		valName        string
		valDescription string
		valColor       string
		valPosition    int32
		valArchived    bool
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one list",
		Args:  cobra.NoArgs,
		Long: `POST /lists

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl lists create --name '<name>' --description '<description>'",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("name") {
				body["name"] = valName
			}
			if cmd.Flags().Changed("description") {
				body["description"] = valDescription
			}
			if cmd.Flags().Changed("color") {
				body["color"] = valColor
			}
			if cmd.Flags().Changed("position") {
				body["position"] = valPosition
			}
			if cmd.Flags().Changed("archived") {
				body["archived"] = valArchived
			}
			return c.run(cmd, Request{Method: http.MethodPost, Path: "/lists", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valName, "name", "",
		"Required.")
	_ = cmd.MarkFlagRequired("name")
	flags.StringVar(&valDescription, "description", "",
		"Required.")
	_ = cmd.MarkFlagRequired("description")
	flags.StringVar(&valColor, "color", "",
		"Optional; left out, the database supplies its default.")
	flags.Int32Var(&valPosition, "position", 0,
		"Optional; left out, the database supplies its default.")
	flags.BoolVar(&valArchived, "archived", false,
		"Optional; left out, the database supplies its default.")
	return cmd
}

// newListsUpdateCommand is Patch /lists/{id}.
func newListsUpdateCommand(c *Client) *cobra.Command {
	var (
		valName        string
		valDescription string
		valColor       string
		valPosition    int32
		valArchived    bool
	)
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update one list by primary key",
		Args:  cobra.ExactArgs(1),
		Long: `PATCH /lists/{id}

Only the flags you pass are sent, so an update writes the columns it names and
no others — which is also why a flag left out and a flag set to an empty value
mean different things. Immutable columns have no flag here: they are settable
once, at create.`,
		Example: "  taskctl lists update <id> --name '<name>'",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("name") {
				body["name"] = valName
			}
			if cmd.Flags().Changed("description") {
				body["description"] = valDescription
			}
			if cmd.Flags().Changed("color") {
				body["color"] = valColor
			}
			if cmd.Flags().Changed("position") {
				body["position"] = valPosition
			}
			if cmd.Flags().Changed("archived") {
				body["archived"] = valArchived
			}
			if len(body) == 0 {
				return errors.New("nothing to update: pass at least one field flag")
			}
			return c.run(cmd, Request{Method: http.MethodPatch, Path: itemPath("/lists", args[0]), Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valName, "name", "",
		"Sets name.")
	flags.StringVar(&valDescription, "description", "",
		"Sets description.")
	flags.StringVar(&valColor, "color", "",
		"Sets color.")
	flags.Int32Var(&valPosition, "position", 0,
		"Sets position.")
	flags.BoolVar(&valArchived, "archived", false,
		"Sets archived.")
	return cmd
}

// ------------------------------------------------------------- /memberships

// newMembershipsCommand groups the operations /memberships exposes.
func newMembershipsCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "memberships",
		Short: "A user's membership of a workspace, and their role in it",
	}
	cmd.AddCommand(newMembershipsListCommand(c))
	cmd.AddCommand(newMembershipsGetCommand(c))
	cmd.AddCommand(newMembershipsCreateCommand(c))
	cmd.AddCommand(newMembershipsDeleteCommand(c))
	return cmd
}

// newMembershipsListCommand is GET /memberships.
func newMembershipsListCommand(c *Client) *cobra.Command {
	var (
		filterID          []string
		filterWorkspaceID []string
		filterUserID      []string
		filterRole        []string
		sort              []string
		select_           []string
		page              int
		perPage           int
		count             bool
		cursor            string
		all               bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List memberships",
		Long: `A user's membership of a workspace, and their role in it.

GET /memberships

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl memberships list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl memberships list --role eq.owner

  # Ordered, and projected down to the columns about to be read
  taskctl memberships list --sort -role --select id,workspace_id

  # Every matching row, walked by cursor rather than by page number
  taskctl memberships list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterWorkspaceID {
				q.Add("workspace_id", v)
			}
			for _, v := range filterUserID {
				q.Add("user_id", v)
			}
			for _, v := range filterRole {
				q.Add("role", v)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return c.run(cmd, Request{Method: http.MethodGet, Path: "/memberships", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterWorkspaceID, "workspace-id", nil,
		`Filter on workspace_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterUserID, "user-id", nil,
		`Filter on user_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterRole, "role", nil,
		`Filter on role, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.
Values: owner, admin, member.`)
	registerCompletion(cmd, "role", []string{"owner", "admin", "member", "eq.owner", "eq.admin", "eq.member"})
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: role, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"role", "-role", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, workspace_id, user_id, role, created_at, updated_at.`)
	registerCompletion(cmd, "select", []string{"id", "workspace_id", "user_id", "role", "created_at", "updated_at"})
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newMembershipsGetCommand is GET /memberships/{id}.
func newMembershipsGetCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one membership by primary key",
		Long: `GET /memberships/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: "  taskctl memberships get <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			return c.run(cmd, Request{Method: http.MethodGet, Path: itemPath("/memberships", args[0]), Query: q}, false)
		},
	}
	return cmd
}

// newMembershipsCreateCommand is Post /memberships.
func newMembershipsCreateCommand(c *Client) *cobra.Command {
	var (
		valUserID string
		valRole   string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one membership",
		Args:  cobra.NoArgs,
		Long: `POST /memberships

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl memberships create --user-id <user_id>",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = valUserID
			}
			if cmd.Flags().Changed("role") {
				body["role"] = valRole
			}
			return c.run(cmd, Request{Method: http.MethodPost, Path: "/memberships", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valUserID, "user-id", "",
		"UUID. References users. Required.")
	_ = cmd.MarkFlagRequired("user-id")
	flags.StringVar(&valRole, "role", "",
		"One of: owner, admin, member. Optional; left out, the database supplies its default.")
	registerCompletion(cmd, "role", []string{"owner", "admin", "member"})
	return cmd
}

// newMembershipsDeleteCommand is DELETE /memberships/{id}.
func newMembershipsDeleteCommand(c *Client) *cobra.Command {
	return &cobra.Command{
		Use:   "delete <id>",
		Short: "Delete one membership by primary key",
		Long: `DELETE /memberships/{id}

A successful delete writes nothing: the response carries no body, so there is
nothing to print.`,
		Example: "  taskctl memberships delete <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return c.run(cmd, Request{Method: http.MethodDelete, Path: itemPath("/memberships", args[0])}, false)
		},
	}
}

// ------------------------------------------------------------------- /tasks

// newTasksCommand groups the operations /tasks exposes.
func newTasksCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tasks",
		Short: "A unit of work, belonging to one list",
	}
	cmd.AddCommand(newTasksListCommand(c))
	cmd.AddCommand(newTasksGetCommand(c))
	cmd.AddCommand(newTasksCreateCommand(c))
	cmd.AddCommand(newTasksUpdateCommand(c))
	return cmd
}

// newTasksListCommand is GET /tasks.
func newTasksListCommand(c *Client) *cobra.Command {
	var (
		filterID           []string
		filterWorkspaceID  []string
		filterListID       []string
		filterAssigneeID   []string
		filterTitle        []string
		filterDescription  []string
		filterLabels       []string
		filterStatus       []string
		filterPriority     []string
		filterDueAt        []string
		filterCompletedAt  []string
		filterCommentCount []string
		sort               []string
		select_            []string
		expand             []string
		search             string
		page               int
		perPage            int
		count              bool
		cursor             string
		all                bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List tasks",
		Long: `A unit of work, belonging to one list.

GET /tasks

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl tasks list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl tasks list --status eq.todo

  # Ordered, and projected down to the columns about to be read
  taskctl tasks list --sort -title --select id,workspace_id

  # Every matching row, walked by cursor rather than by page number
  taskctl tasks list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterWorkspaceID {
				q.Add("workspace_id", v)
			}
			for _, v := range filterListID {
				q.Add("list_id", v)
			}
			for _, v := range filterAssigneeID {
				q.Add("assignee_id", v)
			}
			for _, v := range filterTitle {
				q.Add("title", v)
			}
			for _, v := range filterDescription {
				q.Add("description", v)
			}
			for _, v := range filterLabels {
				q.Add("labels", v)
			}
			for _, v := range filterStatus {
				q.Add("status", v)
			}
			for _, v := range filterPriority {
				q.Add("priority", v)
			}
			for _, v := range filterDueAt {
				q.Add("due_at", v)
			}
			for _, v := range filterCompletedAt {
				q.Add("completed_at", v)
			}
			for _, v := range filterCommentCount {
				q.Add("comment_count", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return c.run(cmd, Request{Method: http.MethodGet, Path: "/tasks", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterWorkspaceID, "workspace-id", nil,
		`Filter on workspace_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterListID, "list-id", nil,
		`Filter on list_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterAssigneeID, "assignee-id", nil,
		`Filter on assignee_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, isnull, notnull, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterTitle, "title", nil,
		`Filter on title, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterDescription, "description", nil,
		`Filter on description, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterLabels, "labels", nil,
		`Free-form labels. Filter with has, hasany or hasall.
Filter on labels, an array column: written operator.value, or a bare
comma-separated list for whole-array equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, has, hasany, hasall.`)
	flags.StringArrayVar(&filterStatus, "status", nil,
		`Filter on status, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.
Values: todo, in_progress, blocked, done.`)
	registerCompletion(cmd, "status", []string{"todo", "in_progress", "blocked", "done", "eq.todo", "eq.in_progress", "eq.blocked", "eq.done"})
	flags.StringArrayVar(&filterPriority, "priority", nil,
		`Filter on priority, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.
Values: low, medium, high, urgent.`)
	registerCompletion(cmd, "priority", []string{"low", "medium", "high", "urgent", "eq.low", "eq.medium", "eq.high", "eq.urgent"})
	flags.StringArrayVar(&filterDueAt, "due-at", nil,
		`Filter on due_at, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, isnull, notnull.`)
	flags.StringArrayVar(&filterCompletedAt, "completed-at", nil,
		`Filter on completed_at, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, isnull, notnull.`)
	flags.StringArrayVar(&filterCommentCount, "comment-count", nil,
		`Filter on comment_count, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: title, status, priority, due_at, completed_at, position, comment_count, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"title", "-title", "status", "-status", "priority", "-priority", "due_at", "-due_at", "completed_at", "-completed_at", "position", "-position", "comment_count", "-comment_count", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, workspace_id, list_id, assignee_id, author_id, title, description, labels, status, priority, due_at, completed_at, position, comment_count, created_at, updated_at, deleted_at.`)
	registerCompletion(cmd, "select", []string{"id", "workspace_id", "list_id", "assignee_id", "author_id", "title", "description", "labels", "status", "priority", "due_at", "completed_at", "position", "comment_count", "created_at", "updated_at", "deleted_at"})
	flags.StringSliceVar(&expand, "expand", nil,
		"Relations to embed in each row. Relations: list.")
	registerCompletion(cmd, "expand", []string{"list"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across title, description.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newTasksGetCommand is GET /tasks/{id}.
func newTasksGetCommand(c *Client) *cobra.Command {
	var expand []string
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one task by primary key",
		Long: `GET /tasks/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: `  taskctl tasks get <id>

  # With list embedded, in one request
  taskctl tasks get <id> --expand list`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			return c.run(cmd, Request{Method: http.MethodGet, Path: itemPath("/tasks", args[0]), Query: q}, false)
		},
	}
	cmd.Flags().StringSliceVar(&expand, "expand", nil,
		"Relations to embed. Relations: list.")
	registerCompletion(cmd, "expand", []string{"list"})
	return cmd
}

// newTasksCreateCommand is Post /tasks.
func newTasksCreateCommand(c *Client) *cobra.Command {
	var (
		valListID      string
		valAssigneeID  string
		valTitle       string
		valDescription string
		valLabels      string
		valStatus      string
		valPriority    string
		valDueAt       string
		valPosition    int32
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one task",
		Args:  cobra.NoArgs,
		Long: `POST /tasks

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl tasks create --list-id <list_id> --title '<title>' --description '<description>'",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("list-id") {
				body["list_id"] = valListID
			}
			if cmd.Flags().Changed("assignee-id") {
				body["assignee_id"] = valAssigneeID
			}
			if cmd.Flags().Changed("title") {
				body["title"] = valTitle
			}
			if cmd.Flags().Changed("description") {
				body["description"] = valDescription
			}
			if cmd.Flags().Changed("labels") {
				body["labels"] = valLabels
			}
			if cmd.Flags().Changed("status") {
				body["status"] = valStatus
			}
			if cmd.Flags().Changed("priority") {
				body["priority"] = valPriority
			}
			if cmd.Flags().Changed("due-at") {
				body["due_at"] = valDueAt
			}
			if cmd.Flags().Changed("position") {
				body["position"] = valPosition
			}
			return c.run(cmd, Request{Method: http.MethodPost, Path: "/tasks", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valListID, "list-id", "",
		"UUID. References lists. Required.")
	_ = cmd.MarkFlagRequired("list-id")
	flags.StringVar(&valAssigneeID, "assignee-id", "",
		"UUID. References users. Optional; left out, the column is null.")
	flags.StringVar(&valTitle, "title", "",
		"Required.")
	_ = cmd.MarkFlagRequired("title")
	flags.StringVar(&valDescription, "description", "",
		"Required.")
	_ = cmd.MarkFlagRequired("description")
	flags.StringVar(&valLabels, "labels", "",
		"Free-form labels. Filter with has, hasany or hasall. Optional; left out, the database supplies its default.")
	flags.StringVar(&valStatus, "status", "",
		"One of: todo, in_progress, blocked, done. Optional; left out, the database supplies its default.")
	registerCompletion(cmd, "status", []string{"todo", "in_progress", "blocked", "done"})
	flags.StringVar(&valPriority, "priority", "",
		"One of: low, medium, high, urgent. Optional; left out, the database supplies its default.")
	registerCompletion(cmd, "priority", []string{"low", "medium", "high", "urgent"})
	flags.StringVar(&valDueAt, "due-at", "",
		"RFC 3339 timestamp, e.g. 2026-07-28T09:00:00Z. Optional; left out, the column is null.")
	flags.Int32Var(&valPosition, "position", 0,
		"Optional; left out, the database supplies its default.")
	return cmd
}

// newTasksUpdateCommand is Patch /tasks/{id}.
func newTasksUpdateCommand(c *Client) *cobra.Command {
	var (
		valListID      string
		valAssigneeID  string
		valTitle       string
		valDescription string
		valLabels      string
		valStatus      string
		valPriority    string
		valDueAt       string
		valPosition    int32
		setNull        []string
	)
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update one task by primary key",
		Args:  cobra.ExactArgs(1),
		Long: `PATCH /tasks/{id}

Only the flags you pass are sent, so an update writes the columns it names and
no others — which is also why a flag left out and a flag set to an empty value
mean different things. Immutable columns have no flag here: they are settable
once, at create.`,
		Example: `  taskctl tasks update <id> --status todo

  # Back to null, which no value flag can say
  taskctl tasks update <id> --set-null assignee_id`,
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("list-id") {
				body["list_id"] = valListID
			}
			if cmd.Flags().Changed("assignee-id") {
				body["assignee_id"] = valAssigneeID
			}
			if cmd.Flags().Changed("title") {
				body["title"] = valTitle
			}
			if cmd.Flags().Changed("description") {
				body["description"] = valDescription
			}
			if cmd.Flags().Changed("labels") {
				body["labels"] = valLabels
			}
			if cmd.Flags().Changed("status") {
				body["status"] = valStatus
			}
			if cmd.Flags().Changed("priority") {
				body["priority"] = valPriority
			}
			if cmd.Flags().Changed("due-at") {
				body["due_at"] = valDueAt
			}
			if cmd.Flags().Changed("position") {
				body["position"] = valPosition
			}
			if err := setNullFields(body, setNull, []string{"assignee_id", "due_at"}); err != nil {
				return err
			}
			if len(body) == 0 {
				return errors.New("nothing to update: pass at least one field flag")
			}
			return c.run(cmd, Request{Method: http.MethodPatch, Path: itemPath("/tasks", args[0]), Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valListID, "list-id", "",
		"UUID. References lists.")
	flags.StringVar(&valAssigneeID, "assignee-id", "",
		"UUID. References users.")
	flags.StringVar(&valTitle, "title", "",
		"Sets title.")
	flags.StringVar(&valDescription, "description", "",
		"Sets description.")
	flags.StringVar(&valLabels, "labels", "",
		"Free-form labels. Filter with has, hasany or hasall.")
	flags.StringVar(&valStatus, "status", "",
		"One of: todo, in_progress, blocked, done.")
	registerCompletion(cmd, "status", []string{"todo", "in_progress", "blocked", "done"})
	flags.StringVar(&valPriority, "priority", "",
		"One of: low, medium, high, urgent.")
	registerCompletion(cmd, "priority", []string{"low", "medium", "high", "urgent"})
	flags.StringVar(&valDueAt, "due-at", "",
		"RFC 3339 timestamp, e.g. 2026-07-28T09:00:00Z.")
	flags.Int32Var(&valPosition, "position", 0,
		"Sets position.")
	flags.StringArrayVar(&setNull, "set-null", nil,
		`Set a column to null, which no value flag can express. Repeatable.
Columns: assignee_id, due_at.`)
	registerCompletion(cmd, "set-null", []string{"assignee_id", "due_at"})
	return cmd
}

// ------------------------------------------------------------------- /users

// newUsersCommand groups the operations /users exposes.
func newUsersCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Work with users",
	}
	cmd.AddCommand(newUsersListCommand(c))
	cmd.AddCommand(newUsersGetCommand(c))
	return cmd
}

// newUsersListCommand is GET /users.
func newUsersListCommand(c *Client) *cobra.Command {
	var (
		filterID    []string
		filterEmail []string
		filterName  []string
		sort        []string
		select_     []string
		search      string
		page        int
		perPage     int
		count       bool
		cursor      string
		all         bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List users",
		Long: `GET /users

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl users list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl users list --email contains.something

  # Ordered, and projected down to the columns about to be read
  taskctl users list --sort -name --select id,email

  # Every matching row, walked by cursor rather than by page number
  taskctl users list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterEmail {
				q.Add("email", v)
			}
			for _, v := range filterName {
				q.Add("name", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return c.run(cmd, Request{Method: http.MethodGet, Path: "/users", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterEmail, "email", nil,
		`Filter on email, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterName, "name", nil,
		`Filter on name, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: name, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"name", "-name", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, email, name, created_at, updated_at.`)
	registerCompletion(cmd, "select", []string{"id", "email", "name", "created_at", "updated_at"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across email, name.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newUsersGetCommand is GET /users/{id}.
func newUsersGetCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one user by primary key",
		Long: `GET /users/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: "  taskctl users get <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			return c.run(cmd, Request{Method: http.MethodGet, Path: itemPath("/users", args[0]), Query: q}, false)
		},
	}
	return cmd
}

// -------------------------------------------------------------- /workspaces

// newWorkspacesCommand groups the operations /workspaces exposes.
func newWorkspacesCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "workspaces",
		Short: "A tenant. Lists, tasks and comments all belong to exactly one",
	}
	cmd.AddCommand(newWorkspacesListCommand(c))
	cmd.AddCommand(newWorkspacesGetCommand(c))
	return cmd
}

// newWorkspacesListCommand is GET /workspaces.
func newWorkspacesListCommand(c *Client) *cobra.Command {
	var (
		filterID   []string
		filterName []string
		filterSlug []string
		sort       []string
		select_    []string
		search     string
		page       int
		perPage    int
		count      bool
		cursor     string
		all        bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List workspaces",
		Long: `A tenant. Lists, tasks and comments all belong to exactly one.

GET /workspaces

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl workspaces list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl workspaces list --name contains.something

  # Ordered, and projected down to the columns about to be read
  taskctl workspaces list --sort -name --select id,name

  # Every matching row, walked by cursor rather than by page number
  taskctl workspaces list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterName {
				q.Add("name", v)
			}
			for _, v := range filterSlug {
				q.Add("slug", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return c.run(cmd, Request{Method: http.MethodGet, Path: "/workspaces", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterName, "name", nil,
		`Filter on name, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterSlug, "slug", nil,
		`Filter on slug, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: name, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"name", "-name", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, name, slug, created_at, updated_at.`)
	registerCompletion(cmd, "select", []string{"id", "name", "slug", "created_at", "updated_at"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across name.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newWorkspacesGetCommand is GET /workspaces/{id}.
func newWorkspacesGetCommand(c *Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one workspace by primary key",
		Long: `GET /workspaces/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: "  taskctl workspaces get <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			return c.run(cmd, Request{Method: http.MethodGet, Path: itemPath("/workspaces", args[0]), Query: q}, false)
		},
	}
	return cmd
}
