-- Generated by sqlb. Review before applying.

-- +goose Up
-- create table comments
-- +goose StatementBegin
CREATE TABLE "comments" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "workspace_id" uuid NOT NULL,
    "task_id" uuid NOT NULL,
    "author_id" uuid NOT NULL,
    "body" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz,
    CONSTRAINT "comments_pkey" PRIMARY KEY ("id")
);
COMMENT ON TABLE "comments" IS 'A comment on a task.';
-- +goose StatementEnd
-- create table lists
-- +goose StatementBegin
CREATE TABLE "lists" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "workspace_id" uuid NOT NULL,
    "name" text NOT NULL,
    "description" text NOT NULL,
    "color" text NOT NULL DEFAULT '#6b7280',
    "position" integer NOT NULL DEFAULT 0,
    "archived" boolean NOT NULL DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz,
    CONSTRAINT "lists_pkey" PRIMARY KEY ("id")
);
COMMENT ON TABLE "lists" IS 'A named list of tasks within a workspace.';
-- +goose StatementEnd
-- create table memberships
-- +goose StatementBegin
CREATE TABLE "memberships" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "workspace_id" uuid NOT NULL,
    "user_id" uuid NOT NULL,
    "role" text NOT NULL DEFAULT 'member',
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "memberships_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "memberships_role_check" CHECK ("role" IN ('owner', 'admin', 'member'))
);
COMMENT ON TABLE "memberships" IS 'A user''s membership of a workspace, and their role in it.';
-- +goose StatementEnd
-- create table tasks
-- +goose StatementBegin
CREATE TABLE "tasks" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "workspace_id" uuid NOT NULL,
    "list_id" uuid NOT NULL,
    "assignee_id" uuid,
    "author_id" uuid NOT NULL,
    "title" text NOT NULL,
    "description" text NOT NULL,
    "status" text NOT NULL DEFAULT 'todo',
    "priority" text NOT NULL DEFAULT 'medium',
    "due_at" timestamptz,
    "completed_at" timestamptz,
    "position" integer NOT NULL DEFAULT 0,
    "comment_count" integer NOT NULL DEFAULT 0,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    "deleted_at" timestamptz,
    CONSTRAINT "tasks_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "tasks_status_check" CHECK ("status" IN ('todo', 'in_progress', 'blocked', 'done')),
    CONSTRAINT "tasks_priority_check" CHECK ("priority" IN ('low', 'medium', 'high', 'urgent')),
    CONSTRAINT "done_tasks_have_a_completion_time" CHECK (status <> 'done' OR completed_at IS NOT NULL)
);
COMMENT ON TABLE "tasks" IS 'A unit of work, belonging to one list.';
-- +goose StatementEnd
-- create table users
CREATE TABLE "users" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "email" text NOT NULL,
    "name" text NOT NULL,
    "password_hash" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "users_email_key" UNIQUE ("email")
);
-- create table workspaces
-- +goose StatementBegin
CREATE TABLE "workspaces" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "name" text NOT NULL,
    "slug" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "workspaces_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "workspaces_slug_key" UNIQUE ("slug")
);
COMMENT ON TABLE "workspaces" IS 'A tenant. Lists, tasks and comments all belong to exactly one.';
-- +goose StatementEnd
-- add foreign key comments_workspace_id_fkey
ALTER TABLE "comments" ADD CONSTRAINT "comments_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") ON DELETE CASCADE;
-- add foreign key comments_task_id_fkey
ALTER TABLE "comments" ADD CONSTRAINT "comments_task_id_fkey" FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") ON DELETE CASCADE;
-- add foreign key comments_author_id_fkey
ALTER TABLE "comments" ADD CONSTRAINT "comments_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE RESTRICT;
-- add foreign key lists_workspace_id_fkey
ALTER TABLE "lists" ADD CONSTRAINT "lists_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") ON DELETE CASCADE;
-- add foreign key memberships_workspace_id_fkey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") ON DELETE CASCADE;
-- add foreign key memberships_user_id_fkey
ALTER TABLE "memberships" ADD CONSTRAINT "memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
-- add foreign key tasks_workspace_id_fkey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_workspace_id_fkey" FOREIGN KEY ("workspace_id") REFERENCES "workspaces" ("id") ON DELETE CASCADE;
-- add foreign key tasks_list_id_fkey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_list_id_fkey" FOREIGN KEY ("list_id") REFERENCES "lists" ("id") ON DELETE CASCADE;
-- add foreign key tasks_assignee_id_fkey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_assignee_id_fkey" FOREIGN KEY ("assignee_id") REFERENCES "users" ("id") ON DELETE SET NULL;
-- add foreign key tasks_author_id_fkey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_author_id_fkey" FOREIGN KEY ("author_id") REFERENCES "users" ("id") ON DELETE RESTRICT;
-- index comments_task_id_created_at_idx
CREATE INDEX "comments_task_id_created_at_idx" ON "comments" ("task_id", "created_at");
-- index lists_workspace_id_archived_idx
CREATE INDEX "lists_workspace_id_archived_idx" ON "lists" ("workspace_id", "archived");
-- index lists_workspace_id_id_uniq
CREATE UNIQUE INDEX "lists_workspace_id_id_uniq" ON "lists" ("workspace_id", "id");
-- index lists_workspace_id_name_uniq
CREATE UNIQUE INDEX "lists_workspace_id_name_uniq" ON "lists" ("workspace_id", "name");
-- index memberships_workspace_id_user_id_uniq
CREATE UNIQUE INDEX "memberships_workspace_id_user_id_uniq" ON "memberships" ("workspace_id", "user_id");
-- index tasks_assignee_id_idx
CREATE INDEX "tasks_assignee_id_idx" ON "tasks" ("assignee_id");
-- index tasks_due_at_idx
CREATE INDEX "tasks_due_at_idx" ON "tasks" ("due_at");
-- index tasks_list_id_position_idx
CREATE INDEX "tasks_list_id_position_idx" ON "tasks" ("list_id", "position");
-- index tasks_workspace_id_id_uniq
CREATE UNIQUE INDEX "tasks_workspace_id_id_uniq" ON "tasks" ("workspace_id", "id");
-- index tasks_workspace_id_status_idx
CREATE INDEX "tasks_workspace_id_status_idx" ON "tasks" ("workspace_id", "status");

-- +goose Down
DROP INDEX "tasks_workspace_id_status_idx";
DROP INDEX "tasks_workspace_id_id_uniq";
DROP INDEX "tasks_list_id_position_idx";
DROP INDEX "tasks_due_at_idx";
DROP INDEX "tasks_assignee_id_idx";
DROP INDEX "memberships_workspace_id_user_id_uniq";
DROP INDEX "lists_workspace_id_name_uniq";
DROP INDEX "lists_workspace_id_id_uniq";
DROP INDEX "lists_workspace_id_archived_idx";
DROP INDEX "comments_task_id_created_at_idx";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_author_id_fkey";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_assignee_id_fkey";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_list_id_fkey";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_workspace_id_fkey";
ALTER TABLE "memberships" DROP CONSTRAINT "memberships_user_id_fkey";
ALTER TABLE "memberships" DROP CONSTRAINT "memberships_workspace_id_fkey";
ALTER TABLE "lists" DROP CONSTRAINT "lists_workspace_id_fkey";
ALTER TABLE "comments" DROP CONSTRAINT "comments_author_id_fkey";
ALTER TABLE "comments" DROP CONSTRAINT "comments_task_id_fkey";
ALTER TABLE "comments" DROP CONSTRAINT "comments_workspace_id_fkey";
DROP TABLE "workspaces";
DROP TABLE "users";
DROP TABLE "tasks";
DROP TABLE "memberships";
DROP TABLE "lists";
DROP TABLE "comments";
