-- Generated by sqlb. Review before applying.

-- +goose Up
-- updated_at is set by its column default at insert and by nothing at all
--   afterwards. A trigger is the only place this can live where every writer
--   is covered: an application that sets it in Go misses the migration that
--   backfills a column, and the psql session somebody used to fix a row at
--   3am.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;
-- +goose StatementEnd
CREATE TRIGGER workspaces_touch_updated_at BEFORE UPDATE ON "workspaces"
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER users_touch_updated_at BEFORE UPDATE ON "users"
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER memberships_touch_updated_at BEFORE UPDATE ON "memberships"
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER lists_touch_updated_at BEFORE UPDATE ON "lists"
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER tasks_touch_updated_at BEFORE UPDATE ON "tasks"
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER comments_touch_updated_at BEFORE UPDATE ON "comments"
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
-- tasks.completed_at is ReadOnly in the schema, so no request can set it,
--   and the check constraint done_tasks_have_a_completion_time requires it
--   whenever status is 'done'. Something has to reconcile the two, and it
--   has to see the new row rather than the old one — which a BEFORE
--   trigger does and a hook cannot: a BeforeUpdate hook is handed the
--   statement, not the resulting row, so it cannot know what status is about
--   to become.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION tasks_sync_completed_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status = 'done' AND NEW.completed_at IS NULL THEN
        NEW.completed_at := now();
    ELSIF NEW.status <> 'done' THEN
        NEW.completed_at := NULL;
    END IF;
    RETURN NEW;
END;
$$;
-- +goose StatementEnd
CREATE TRIGGER tasks_sync_completed_at BEFORE INSERT OR UPDATE ON "tasks"
    FOR EACH ROW EXECUTE FUNCTION tasks_sync_completed_at();
-- A task may only belong to a list in its own workspace. This is the
--   constraint the hooks approximate and the database can actually
--   guarantee.
ALTER TABLE "tasks"
    ADD CONSTRAINT "tasks_list_in_same_workspace"
    FOREIGN KEY ("workspace_id", "list_id")
    REFERENCES "lists" ("workspace_id", "id") ON DELETE CASCADE;
-- The same, for comments and the task they hang off.
ALTER TABLE "comments"
    ADD CONSTRAINT "comments_task_in_same_workspace"
    FOREIGN KEY ("workspace_id", "task_id")
    REFERENCES "tasks" ("workspace_id", "id") ON DELETE CASCADE;

-- +goose Down
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS "comments_task_in_same_workspace";
ALTER TABLE "tasks" DROP CONSTRAINT IF EXISTS "tasks_list_in_same_workspace";
DROP TRIGGER IF EXISTS tasks_sync_completed_at ON "tasks";
DROP FUNCTION IF EXISTS tasks_sync_completed_at();
DROP TRIGGER IF EXISTS comments_touch_updated_at ON "comments";
DROP TRIGGER IF EXISTS tasks_touch_updated_at ON "tasks";
DROP TRIGGER IF EXISTS lists_touch_updated_at ON "lists";
DROP TRIGGER IF EXISTS memberships_touch_updated_at ON "memberships";
DROP TRIGGER IF EXISTS users_touch_updated_at ON "users";
DROP TRIGGER IF EXISTS workspaces_touch_updated_at ON "workspaces";
DROP FUNCTION IF EXISTS touch_updated_at();
