-- +goose NO TRANSACTION
-- Index changes cannot run inside a transaction, so this file is not
-- wrapped in one. It contains only index changes for that reason.
-- Generated by sqlb. Review before applying.

-- +goose Up
-- index tasks_labels_idx
CREATE INDEX CONCURRENTLY "tasks_labels_idx" ON "tasks" USING gin ("labels");

-- +goose Down
DROP INDEX CONCURRENTLY "tasks_labels_idx";
