-- Generated by sqlb. Review before applying.

-- +goose Up
-- create table profiles
-- +goose StatementBegin
CREATE TABLE "profiles" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "user_id" uuid NOT NULL,
    "bio" text,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "profiles_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "profiles_user_id_key" UNIQUE ("user_id")
);
COMMENT ON TABLE "profiles" IS 'A user''s extended profile. One-to-one with users: user_id is unique.';
-- +goose StatementEnd
-- add foreign key profiles_user_id_fkey
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

-- +goose Down
ALTER TABLE "profiles" DROP CONSTRAINT "profiles_user_id_fkey";
DROP TABLE "profiles";
