-- Generated by sqlb. Review before applying.

-- +goose Up
-- add column tasks.labels
-- +goose StatementBegin
ALTER TABLE "tasks" ADD COLUMN "labels" text[] NOT NULL DEFAULT '{}';
COMMENT ON COLUMN "tasks"."labels" IS 'Free-form labels. Filter with has, hasany or hasall.';
-- +goose StatementEnd

-- +goose Down
ALTER TABLE "tasks" DROP COLUMN "labels";
