package codegen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jryannel/sqlb/codegen"
	"github.com/jryannel/sqlb/schema"
)

func fixture() *schema.Registry {
	r := schema.NewRegistry()
	org := r.Table("orgs", schema.UUIDv7("id").PrimaryKey(), schema.Text("name"))
	r.Table("blog_entries",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("org", org).OnDelete(schema.Cascade),
		schema.Text("title").Searchable().Sortable(),
		schema.Enum("status", "draft", "published").Filterable(),
		schema.BigInt("view_count").ReadOnly(),
		schema.Timestamp("published_at").Nullable().Sortable(),
		schema.Text("secret").Hidden(),
	).Expose(schema.REST{Ops: schema.OpList, MaxPageSize: 50})
	return r
}

// contains compares ignoring runs of whitespace, because gofmt aligns struct
// fields and const blocks — assertions that encode the alignment break every
// time a longer field name is added, which trains people to loosen the test
// rather than read it.
func contains(haystack, needle string) bool {
	return strings.Contains(squash(haystack), squash(needle))
}

func squash(s string) string { return strings.Join(strings.Fields(s), " ") }

func generate(t *testing.T, r *schema.Registry) map[string]string {
	t.Helper()
	dir := t.TempDir()
	files, err := codegen.Generate(codegen.Options{Registry: r, Dir: dir, Package: "gen"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := map[string]string{}
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			t.Fatal(err)
		}
		out[filepath.Base(f)] = string(b)
	}
	return out
}

func TestGeneratedModels(t *testing.T) {
	models := generate(t, fixture())["models_gen.go"]

	for _, want := range []string{
		"// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.",
		"type BlogEntry struct {", // singularised, CamelCased
		`func (BlogEntry) TableName() string { return "blog_entries" }`,
		`OrgID string ` + "`" + `db:"org_id"`, // initialism: org_id → OrgID
		`PublishedAt *time.Time`,              // nullable → pointer
		`ViewCount int64`,
		`db:"title" json:"title" sqlb:"filter,sort,search"`, // capabilities reach the tag
		`db:"secret" json:"-" sqlb:"hidden"`,                // hidden is in the model but never on the wire
		"type BlogEntryStatus string",                       // enum type
		`BlogEntryStatusDraft BlogEntryStatus = "draft"`,
		"Status BlogEntryStatus", // column uses the enum type
	} {
		if !contains(models, want) {
			t.Errorf("models missing %q:\n%s", want, models)
		}
	}
}

func TestGeneratedColumns(t *testing.T) {
	cols := generate(t, fixture())["columns_gen.go"]

	for _, want := range []string{
		"var BlogEntryCols = blogEntryColumns{",
		"Title sqlb.TextCol[string]",       // text gets the pattern operators
		"Status sqlb.Col[BlogEntryStatus]", // enum keeps its type
		"ViewCount sqlb.Col[int64]",        // an integer does not get them
		"PublishedAt sqlb.Col[time.Time]",  // nullable compares to the base type
		`sqlb.TextColumn[string]("title")`,
	} {
		if !contains(cols, want) {
			t.Errorf("columns missing %q:\n%s", want, cols)
		}
	}
	// A hidden column must not be reachable from a predicate: it has no entry
	// in the column set, so no comparison against it compiles.
	//
	// It does still get a setter. Hidden gates reads — filters, sorts,
	// projections and responses — not writes, because a password hash has to
	// stay writable from Go. The facade is the read surface; the update
	// wrapper is the write surface.
	set := cols[strings.Index(cols, "type blogEntryColumns"):strings.Index(cols, "type BlogEntryUpdate")]
	if contains(set, "Secret") || contains(set, `"secret"`) {
		t.Errorf("a hidden column leaked into the column set:\n%s", set)
	}
	if !contains(cols, "SetSecret(v string)") {
		t.Error("a hidden column should still be writable from Go")
	}
}

func TestGeneratedUpdateSkipsOnlyThePrimaryKey(t *testing.T) {
	cols := generate(t, fixture())["columns_gen.go"]

	if !contains(cols, "func (u *BlogEntryUpdate) SetTitle(v string) *BlogEntryUpdate {") {
		t.Errorf("expected a typed setter for title:\n%s", cols)
	}
	if !contains(cols, "SetStatus(v BlogEntryStatus)") {
		t.Error("the enum setter should take the enum type")
	}
	// A ReadOnly column gets one too. ReadOnly is a REST-boundary rule, and
	// the boundary is defended there — the column is absent from the request
	// bodies. Go through the query engine is trusted, so leaving it out only
	// meant that the code which is the sole writer of view_count was the one
	// code that had to write it untyped.
	if !contains(cols, "SetViewCount(v int64)") {
		t.Errorf("a read-only column should still be writable typed from Go:\n%s", cols)
	}
	// The primary key addresses the row rather than being part of what an
	// update writes. Stmt() is the way to mean it.
	if contains(cols, "SetID(") {
		t.Error("the primary key must not get a setter")
	}
}

// Generating from a schema with a known authoring error would produce
// plausible Go that encodes the mistake, which is harder to debug than a
// refusal.
func TestGenerateRefusesAnInvalidSchema(t *testing.T) {
	r := schema.NewRegistry()
	r.Table("bad", schema.UUIDv7("id").PrimaryKey(), schema.Int("n").Searchable())

	_, err := codegen.Generate(codegen.Options{Registry: r, Dir: t.TempDir(), Package: "gen"})
	if err == nil {
		t.Fatal("generating from an invalid schema should fail")
	}
	if !strings.Contains(err.Error(), "does not validate") {
		t.Errorf("the error should say why: %v", err)
	}
}

func TestGenerateRefusesAnEmptyRegistry(t *testing.T) {
	_, err := codegen.Generate(codegen.Options{
		Registry: schema.NewRegistry(), Dir: t.TempDir(), Package: "gen",
	})
	if err == nil || !strings.Contains(err.Error(), "no tables") {
		t.Errorf("an empty registry should be reported, got: %v", err)
	}
}

// A module prefix is a storage concern: the Go type is named for the local
// name, and TableName carries the real one.
func TestModulePrefixStaysOutOfTheTypeName(t *testing.T) {
	m := schema.NewModule("billing")
	m.Table("invoices", schema.UUIDv7("id").PrimaryKey(), schema.Numeric("amount"))

	models := generate(t, m)["models_gen.go"]
	if !contains(models, "type Invoice struct {") {
		t.Errorf("type should be Invoice, not BillingInvoice:\n%s", models)
	}
	if !contains(models, `return "billing_invoices"`) {
		t.Errorf("TableName should carry the prefix:\n%s", models)
	}
}

func TestNaming(t *testing.T) {
	for in, want := range map[string]string{
		"org_id": "OrgID", "created_at": "CreatedAt", "password_hash": "PasswordHash",
		"id": "ID", "api_url": "APIURL", "uuid": "UUID",
	} {
		if got := codegen.GoName(in); got != want {
			t.Errorf("GoName(%q) = %q, want %q", in, got, want)
		}
	}
	for in, want := range map[string]string{
		"posts": "post", "categories": "category", "boxes": "box",
		"addresses": "address", "address": "address",
		"status": "status", "bonus": "bonus", // -us is not a plural
	} {
		if got := codegen.Singular(in); got != want {
			t.Errorf("Singular(%q) = %q, want %q", in, got, want)
		}
	}
}

// restFixture exposes a full CRUD resource, so the generated request bodies
// have something to differ about.
func restFixture() *schema.Registry {
	r := schema.NewRegistry()
	org := r.Table("orgs", schema.UUIDv7("id").PrimaryKey(), schema.Text("name"))
	r.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("org", org).OnDelete(schema.Cascade).Immutable(),
		schema.Text("title").Searchable().Sortable(),
		schema.Enum("status", "draft", "published").Default(schema.Value("draft")).Filterable(),
		schema.BigInt("view_count").ReadOnly(),
		schema.Timestamp("published_at").Nullable().Sortable(),
		schema.Text("secret").Hidden(),
	).Expose(schema.REST{Ops: schema.CRUD | schema.OpList, MaxPageSize: 50})
	return r
}

func TestGeneratedCreateBodyOmitsWhatAClientMayNotSet(t *testing.T) {
	src := generate(t, restFixture())["rest_gen.go"]

	for _, want := range []string{
		"type PostCreate struct {",
		`Title string ` + "`" + `json:"title"`,                            // required: no default, not nullable
		`Status *PostStatus ` + "`" + `json:"status,omitempty"`,           // defaulted → optional
		`PublishedAt *time.Time ` + "`" + `json:"published_at,omitempty"`, // nullable → optional
		"func (c PostCreate) Row() (*Post, error)",
	} {
		if !contains(src, want) {
			t.Errorf("create body missing %q:\n%s", want, src)
		}
	}
	// The primary key, a read-only column and a hidden one are all things the
	// client does not get to supply.
	body := src[strings.Index(src, "type PostCreate struct {"):strings.Index(src, "func (c PostCreate) Row()")]
	for _, forbidden := range []string{`json:"id"`, "ViewCount", "Secret"} {
		if contains(body, forbidden) {
			t.Errorf("create body should not carry %s:\n%s", forbidden, body)
		}
	}
}

// An enum column types as a string alias, which Huma documents as a plain
// string — so without the tag an invalid value passed validation, reached the
// INSERT and returned whatever the database said. The generated TypeScript
// client and CLI both enforce the value set, which left the one participant
// that has to as the only one that did not.
func TestGeneratedBodiesConstrainEnumValues(t *testing.T) {
	src := generate(t, restFixture())["rest_gen.go"]

	for _, want := range []string{
		`Status *PostStatus ` + "`" + `json:"status,omitempty" enum:"draft,published"`,
	} {
		if !contains(src, want) {
			t.Errorf("body missing the enum constraint %q:\n%s", want, src)
		}
	}
	// Both bodies, not just the create one: a patch can set a column too.
	patch := src[strings.Index(src, "type PostPatch struct {"):]
	if !contains(patch, `enum:"draft,published"`) {
		t.Errorf("patch body does not constrain the enum:\n%s", patch)
	}
	// A non-enum column must not grow the tag.
	if contains(src, `json:"title" enum:`) {
		t.Error("a plain text column should carry no enum constraint")
	}
}

func TestGeneratedPatchBodyDistinguishesAbsentFromNull(t *testing.T) {
	src := generate(t, restFixture())["rest_gen.go"]

	for _, want := range []string{
		"type PostPatch struct {",
		"present map[string]bool",
		"func (u *PostPatch) UnmarshalJSON(data []byte) error",
		"func (u PostPatch) Changes() (map[string]any, error)",
		// A nullable column that was present writes its pointer straight
		// through, so an explicit null becomes NULL.
		`out["published_at"] = u.PublishedAt`,
		// A non-nullable one rejects an explicit null rather than writing a
		// zero value that looks deliberate.
		`errors.New("title is not nullable and cannot be set to null")`,
	} {
		if !contains(src, want) {
			t.Errorf("patch body missing %q:\n%s", want, src)
		}
	}
	// An immutable column is settable once, at create, so it has no place in a
	// patch body at all.
	patch := src[strings.Index(src, "type PostPatch struct {"):strings.Index(src, "func (u *PostPatch) UnmarshalJSON")]
	if contains(patch, "OrgID") {
		t.Errorf("an immutable column should be absent from the patch body:\n%s", patch)
	}
}

func TestGeneratedRegisterMirrorsTheSchemaExposure(t *testing.T) {
	src := generate(t, restFixture())["rest_gen.go"]

	for _, want := range []string{
		"func Register(api huma.API, db sqlb.Executor) error {",
		"rest.Resource[Post, PostCreate, PostPatch](api, db, rest.Options{",
		`Path: "/posts"`,
		`Name: "post"`, // singularised, for operation IDs
		"Ops: rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpDelete | rest.OpList",
		"MaxPageSize: 50",
	} {
		if !contains(src, want) {
			t.Errorf("registration missing %q:\n%s", want, src)
		}
	}
	// orgs is not exposed, so it is not mounted.
	if contains(src, "rest.Resource[Org") {
		t.Errorf("an unexposed table should not be mounted:\n%s", src)
	}
}

// A package that exposes nothing should not acquire a dependency on huma just
// by being generated.
func TestNoRestFileWhenNothingIsExposed(t *testing.T) {
	r := schema.NewRegistry()
	r.Table("orgs", schema.UUIDv7("id").PrimaryKey(), schema.Text("name"))

	if src, present := generate(t, r)["rest_gen.go"]; present {
		t.Errorf("rest_gen.go should not be written for an unexposed schema:\n%s", src)
	}
}

// expandFixture declares one expandable reference and one that is not, so the
// tests can tell "emits a relation field" from "emits one per reference".
func expandFixture() *schema.Registry {
	r := schema.NewRegistry()
	org := r.Table("orgs", schema.UUIDv7("id").PrimaryKey(), schema.Text("name"))
	author := r.Table("authors", schema.UUIDv7("id").PrimaryKey(), schema.Text("email"))
	r.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("org", org).OnDelete(schema.Cascade),
		schema.Ref("author", author).OnDelete(schema.Restrict).Expandable(),
		schema.Text("title"),
	).Expose(schema.REST{Ops: schema.OpList})
	return r
}

// An expandable reference is two struct fields: the key stays a column, and a
// db:"-" field beside it is what the joined row is scanned into.
func TestExpandableReferenceEmitsARelationField(t *testing.T) {
	models := generate(t, expandFixture())["models_gen.go"]

	want := "Author *Author `db:\"-\" json:\"author,omitempty\" sqlb:\"expands=author_id\"`"
	if !contains(models, want) {
		t.Errorf("relation field missing:\nwant %s\ngot:\n%s", want, models)
	}
	// The key itself is untouched — it is still a column, and still the thing
	// a filter names.
	if !contains(models, "AuthorID string `db:\"author_id\" json:\"author_id\" sqlb:\"expand\"`") {
		t.Errorf("the foreign key column should be unchanged:\n%s", models)
	}
	// A reference nobody marked Expandable gets no relation field: the join is
	// opt-in, and a struct field is a promise the engine would have to keep.
	if contains(models, "Org *Org") {
		t.Errorf("a reference that is not Expandable should not get a relation field:\n%s", models)
	}
}

// The resource's Expandable list comes from the columns, so a schema cannot
// declare a relation expandable and serve a resource that refuses it.
func TestGeneratedRegisterCarriesTheExpandableRelations(t *testing.T) {
	src := generate(t, expandFixture())["rest_gen.go"]

	if !contains(src, `Expandable: []string{"author"}`) {
		t.Errorf("registration should list the expandable relation:\n%s", src)
	}
	// The relation name, not the column: ?expand=author, not ?expand=author_id.
	if contains(src, `"author_id"`) {
		t.Errorf("Expandable should name the relation, not the key column:\n%s", src)
	}
}

// A relation and a column competing for the same Go field would emit a struct
// with two identical field names. go/format parses without type-checking, so
// it would accept the file and the break would surface at the consumer's next
// build instead of here.
func TestRelationCollidingWithAColumnIsRefused(t *testing.T) {
	r := schema.NewRegistry()
	org := r.Table("orgs", schema.UUIDv7("id").PrimaryKey(), schema.Text("name"))
	r.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("org", org).Expandable(),
		schema.Text("org"), // would also be Go field Org
	)

	_, err := codegen.Generate(codegen.Options{Registry: r, Dir: t.TempDir(), Package: "gen"})
	if err == nil {
		t.Fatal("a relation colliding with a column should be refused")
	}
	if !strings.Contains(err.Error(), `relation "org" wants the Go field Org`) {
		t.Errorf("the error should name the field in contention: %v", err)
	}
}

// An ExternalRef points at a table this module does not own. The schema
// already refuses to mark one Expandable; this checks the generator does not
// invent a relation field for one anyway, which would name a Go type that
// does not exist in the package.
func TestExternalReferenceGetsNoRelationField(t *testing.T) {
	m := schema.NewModule("billing")
	m.Table("invoices",
		schema.UUIDv7("id").PrimaryKey(),
		schema.ExternalRef("tenant", "tenants.id").Filterable(),
	).Expose(schema.REST{Ops: schema.OpList})

	files := generate(t, m)
	// The reference is there as a column; what follows is about the relation
	// field it must not also grow, not about the schema failing to compile.
	if !contains(files["models_gen.go"], `db:"tenant_id"`) {
		t.Fatalf("the external reference should still be a column:\n%s", files["models_gen.go"])
	}
	if contains(files["models_gen.go"], `sqlb:"expands=tenant_id"`) {
		t.Errorf("an external reference should not become a relation:\n%s", files["models_gen.go"])
	}
	if contains(files["rest_gen.go"], "Expandable:") {
		t.Errorf("an external reference should not be advertised as expandable:\n%s", files["rest_gen.go"])
	}
}

// inverseFixture declares a reference that names its inverse and exposes it,
// and one that names an inverse and does not.
func inverseFixture() *schema.Registry {
	r := schema.NewRegistry()
	author := r.Table("authors", schema.UUIDv7("id").PrimaryKey(), schema.Text("email")).
		Expose(schema.REST{Ops: schema.OpList})
	editor := r.Table("editors", schema.UUIDv7("id").PrimaryKey()).
		Expose(schema.REST{Ops: schema.OpList})
	r.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("author", author).OnDelete(schema.Restrict).Filterable().Expandable().
			Inverse("posts").
			InverseExpandable(schema.ExpandOrder("-title"), schema.ExpandLimit(5)),
		schema.Ref("editor", editor).OnDelete(schema.Restrict).Filterable().Inverse("edited"),
		schema.Text("title"),
	).Index("author_id").Index("editor_id").Expose(schema.REST{Ops: schema.OpList})
	return r
}

// The reverse relation is declared on the referencing side and lands as a field
// on the target's struct, because the collected rows need somewhere to go.
// ADR-0022.
func TestInverseEmitsACollectionOnTheTarget(t *testing.T) {
	models := generate(t, inverseFixture())["models_gen.go"]

	want := "Posts *sqlb.Collection[Post] `db:\"-\" json:\"posts,omitempty\" sqlb:\"expands=author_id,order=-title,limit=5\"`"
	if !contains(models, want) {
		t.Errorf("collection field missing:\nwant %s\ngot:\n%s", want, models)
	}
	// The collection is the one thing here that is not a plain Go type, so the
	// file takes an import it would otherwise not need.
	if !contains(models, `"github.com/jryannel/sqlb"`) {
		t.Errorf("models importing a Collection should import sqlb:\n%s", models)
	}
	// A named but unexposed inverse emits nothing: the field exists to be
	// filled in by ?expand, and nothing can ask for that one.
	if contains(models, "Edited *sqlb.Collection") {
		t.Errorf("an inverse that was never exposed should emit no field:\n%s", models)
	}
	// And the referencing side is unchanged — the reverse costs it nothing.
	if !contains(models, "AuthorID string `db:\"author_id\" json:\"author_id\" sqlb:\"filter,expand\"`") {
		t.Errorf("the foreign key column should be unchanged:\n%s", models)
	}
}

func TestGeneratedRegisterCarriesTheInverseRelation(t *testing.T) {
	src := generate(t, inverseFixture())["rest_gen.go"]

	if !contains(src, `Expandable: []string{"posts"}`) {
		t.Errorf("the target's registration should list the reverse relation:\n%s", src)
	}
	// The referencing side keeps its own forward relation, and does not gain
	// the reverse one.
	if !contains(src, `Expandable: []string{"author"}`) {
		t.Errorf("the forward relation should be unaffected:\n%s", src)
	}
}
