// Package codegen renders a schema declaration into Go source.
//
// It is driven from a small program in the target project rather than by a CLI
// that compiles your schema behind your back, because the schema is ordinary Go
// and the simplest way to read it is to import it:
//
//	//go:generate go run ./gen
//
//	// gen/main.go
//	package main
//
//	import (
//	    _ "myapp/billing/schema"   // registers its tables
//	    "github.com/jryannel/sqlb/codegen"
//	    "github.com/jryannel/sqlb/schema"
//	)
//
//	func main() {
//	    codegen.Must(codegen.Generate(codegen.Options{
//	        Registry: schema.DefaultRegistry(),
//	        Dir:      "billing",
//	        Package:  "billing",
//	    }))
//	}
//
// Output is deterministic: tables are sorted, columns keep declaration order,
// and every file is run through go/format, so a generator bug that produces
// invalid Go fails here rather than at the consumer's next build.
package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/jryannel/sqlb/schema"
)

// Options configures a generation run.
type Options struct {
	// Registry supplies the tables. Required.
	Registry *schema.Registry
	// Dir is the output directory. Required.
	Dir string
	// Package is the package clause for generated Go. Required.
	Package string

	// ModelsFile, ColumnsFile and ManifestFile override the default names.
	// Set one to "-" to skip that artefact.
	ModelsFile   string
	ColumnsFile  string
	ManifestFile string
}

func (o Options) modelsFile() string   { return orDefault(o.ModelsFile, "models_gen.go") }
func (o Options) columnsFile() string  { return orDefault(o.ColumnsFile, "columns_gen.go") }
func (o Options) manifestFile() string { return orDefault(o.ManifestFile, "sqlb.json") }

func orDefault(v, def string) string {
	if v == "" {
		return def
	}
	return v
}

func (o Options) validate() error {
	switch {
	case o.Registry == nil:
		return fmt.Errorf("codegen: Options.Registry is required")
	case o.Dir == "":
		return fmt.Errorf("codegen: Options.Dir is required")
	case o.Package == "":
		return fmt.Errorf("codegen: Options.Package is required")
	}
	return nil
}

// Generate writes the generated files and returns their paths.
//
// The schema is validated first. Generating from a schema with a known
// authoring error would produce plausible-looking Go that encodes the mistake,
// which is harder to debug than refusing.
func Generate(opts Options) ([]string, error) {
	if err := opts.validate(); err != nil {
		return nil, err
	}
	if err := opts.Registry.Validate(); err != nil {
		return nil, fmt.Errorf("codegen: schema does not validate, refusing to generate:\n%w", err)
	}
	if len(opts.Registry.Tables()) == 0 {
		return nil, fmt.Errorf("codegen: registry has no tables (is the schema package imported for its side effects?)")
	}

	files := map[string][]byte{}

	if name := opts.modelsFile(); name != "-" {
		src, err := renderModels(opts)
		if err != nil {
			return nil, err
		}
		files[name] = src
	}
	if name := opts.columnsFile(); name != "-" {
		src, err := renderColumns(opts)
		if err != nil {
			return nil, err
		}
		files[name] = src
	}
	if name := opts.manifestFile(); name != "-" {
		src, err := opts.Registry.BuildManifest().JSON()
		if err != nil {
			return nil, err
		}
		files[name] = src
	}

	if err := os.MkdirAll(opts.Dir, 0o755); err != nil {
		return nil, err
	}
	var written []string
	for _, name := range sortedKeys(files) {
		path := filepath.Join(opts.Dir, name)
		if err := os.WriteFile(path, files[name], 0o644); err != nil {
			return nil, err
		}
		written = append(written, path)
	}
	return written, nil
}

// Must panics if generation failed, for use in a generator main where there is
// nothing useful to do with the error.
func Must(files []string, err error) []string {
	if err != nil {
		panic(err)
	}
	for _, f := range files {
		fmt.Fprintln(os.Stderr, "generated", f)
	}
	return files
}

// header is emitted at the top of every generated Go file. The exact first line
// is what `go test`, build tooling and code review conventions look for to
// recognise generated code.
func header(pkg string, imports []string) *bytes.Buffer {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n", pkg)
	if len(imports) > 0 {
		fmt.Fprintln(&b)
		if len(imports) == 1 {
			fmt.Fprintf(&b, "import %q\n", imports[0])
		} else {
			fmt.Fprintln(&b, "import (")
			for _, imp := range imports {
				fmt.Fprintf(&b, "\t%q\n", imp)
			}
			fmt.Fprintln(&b, ")")
		}
	}
	return &b
}

// gofmt formats generated source. A generator bug that produces invalid Go
// fails here, naming the file, rather than at the consumer's next build.
func gofmt(name string, src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("codegen: generated %s is not valid Go: %w\n%s", name, err, numbered(src))
	}
	return out, nil
}

// numbered renders source with line numbers, so the parse error above points
// at something a reader can find.
func numbered(src []byte) string {
	var b strings.Builder
	for i, line := range strings.Split(string(src), "\n") {
		fmt.Fprintf(&b, "%4d | %s\n", i+1, line)
	}
	return b.String()
}

func sortedKeys(m map[string][]byte) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	for i := 1; i < len(out); i++ {
		for j := i; j > 0 && out[j] < out[j-1]; j-- {
			out[j], out[j-1] = out[j-1], out[j]
		}
	}
	return out
}
