package codegen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jryannel/sqlb/codegen"
	"github.com/jryannel/sqlb/schema"
)

func fixture() *schema.Registry {
	r := schema.NewRegistry()
	org := r.Table("orgs", schema.UUIDv7("id").PrimaryKey(), schema.Text("name"))
	r.Table("blog_entries",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("org", org).OnDelete(schema.Cascade),
		schema.Text("title").Searchable().Sortable(),
		schema.Enum("status", "draft", "published").Filterable(),
		schema.BigInt("view_count").ReadOnly(),
		schema.Timestamp("published_at").Nullable().Sortable(),
		schema.Text("secret").Hidden(),
	).Expose(schema.REST{Ops: schema.OpList, MaxPageSize: 50})
	return r
}

// contains compares ignoring runs of whitespace, because gofmt aligns struct
// fields and const blocks — assertions that encode the alignment break every
// time a longer field name is added, which trains people to loosen the test
// rather than read it.
func contains(haystack, needle string) bool {
	return strings.Contains(squash(haystack), squash(needle))
}

func squash(s string) string { return strings.Join(strings.Fields(s), " ") }

func generate(t *testing.T, r *schema.Registry) map[string]string {
	t.Helper()
	dir := t.TempDir()
	files, err := codegen.Generate(codegen.Options{Registry: r, Dir: dir, Package: "gen"})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := map[string]string{}
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			t.Fatal(err)
		}
		out[filepath.Base(f)] = string(b)
	}
	return out
}

func TestGeneratedModels(t *testing.T) {
	models := generate(t, fixture())["models_gen.go"]

	for _, want := range []string{
		"// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.",
		"type BlogEntry struct {", // singularised, CamelCased
		`func (BlogEntry) TableName() string { return "blog_entries" }`,
		`OrgID string ` + "`" + `db:"org_id"`, // initialism: org_id → OrgID
		`PublishedAt *time.Time`,              // nullable → pointer
		`ViewCount int64`,
		`db:"title" sqlb:"filter,sort,search"`, // capabilities reach the tag
		`db:"secret" sqlb:"hidden"`,            // hidden is still in the model
		"type BlogEntryStatus string",          // enum type
		`BlogEntryStatusDraft BlogEntryStatus = "draft"`,
		"Status BlogEntryStatus", // column uses the enum type
	} {
		if !contains(models, want) {
			t.Errorf("models missing %q:\n%s", want, models)
		}
	}
}

func TestGeneratedColumns(t *testing.T) {
	cols := generate(t, fixture())["columns_gen.go"]

	for _, want := range []string{
		"var BlogEntryCols = blogEntryColumns{",
		"Title sqlb.TextCol[string]",       // text gets the pattern operators
		"Status sqlb.Col[BlogEntryStatus]", // enum keeps its type
		"ViewCount sqlb.Col[int64]",        // an integer does not get them
		"PublishedAt sqlb.Col[time.Time]",  // nullable compares to the base type
		`sqlb.TextColumn[string]("title")`,
	} {
		if !contains(cols, want) {
			t.Errorf("columns missing %q:\n%s", want, cols)
		}
	}
	// A hidden column must not be reachable from a predicate: it has no entry
	// in the column set, so no comparison against it compiles.
	//
	// It does still get a setter. Hidden gates reads — filters, sorts,
	// projections and responses — not writes, because a password hash has to
	// stay writable from Go. The facade is the read surface; the update
	// wrapper is the write surface.
	set := cols[strings.Index(cols, "type blogEntryColumns"):strings.Index(cols, "type BlogEntryUpdate")]
	if contains(set, "Secret") || contains(set, `"secret"`) {
		t.Errorf("a hidden column leaked into the column set:\n%s", set)
	}
	if !contains(cols, "SetSecret(v string)") {
		t.Error("a hidden column should still be writable from Go")
	}
}

func TestGeneratedUpdateSkipsReadOnlyColumns(t *testing.T) {
	cols := generate(t, fixture())["columns_gen.go"]

	if !contains(cols, "func (u *BlogEntryUpdate) SetTitle(v string) *BlogEntryUpdate {") {
		t.Errorf("expected a typed setter for title:\n%s", cols)
	}
	if !contains(cols, "SetStatus(v BlogEntryStatus)") {
		t.Error("the enum setter should take the enum type")
	}
	// id and view_count are read-only, so writing them is not offered.
	for _, unwanted := range []string{"SetID(", "SetViewCount("} {
		if contains(cols, unwanted) {
			t.Errorf("a read-only column must not get a setter: %s", unwanted)
		}
	}
}

// Generating from a schema with a known authoring error would produce
// plausible Go that encodes the mistake, which is harder to debug than a
// refusal.
func TestGenerateRefusesAnInvalidSchema(t *testing.T) {
	r := schema.NewRegistry()
	r.Table("bad", schema.UUIDv7("id").PrimaryKey(), schema.Int("n").Searchable())

	_, err := codegen.Generate(codegen.Options{Registry: r, Dir: t.TempDir(), Package: "gen"})
	if err == nil {
		t.Fatal("generating from an invalid schema should fail")
	}
	if !strings.Contains(err.Error(), "does not validate") {
		t.Errorf("the error should say why: %v", err)
	}
}

func TestGenerateRefusesAnEmptyRegistry(t *testing.T) {
	_, err := codegen.Generate(codegen.Options{
		Registry: schema.NewRegistry(), Dir: t.TempDir(), Package: "gen",
	})
	if err == nil || !strings.Contains(err.Error(), "no tables") {
		t.Errorf("an empty registry should be reported, got: %v", err)
	}
}

// A module prefix is a storage concern: the Go type is named for the local
// name, and TableName carries the real one.
func TestModulePrefixStaysOutOfTheTypeName(t *testing.T) {
	m := schema.NewModule("billing")
	m.Table("invoices", schema.UUIDv7("id").PrimaryKey(), schema.Numeric("amount"))

	models := generate(t, m)["models_gen.go"]
	if !contains(models, "type Invoice struct {") {
		t.Errorf("type should be Invoice, not BillingInvoice:\n%s", models)
	}
	if !contains(models, `return "billing_invoices"`) {
		t.Errorf("TableName should carry the prefix:\n%s", models)
	}
}

func TestNaming(t *testing.T) {
	for in, want := range map[string]string{
		"org_id": "OrgID", "created_at": "CreatedAt", "password_hash": "PasswordHash",
		"id": "ID", "api_url": "APIURL", "uuid": "UUID",
	} {
		if got := codegen.GoName(in); got != want {
			t.Errorf("GoName(%q) = %q, want %q", in, got, want)
		}
	}
	for in, want := range map[string]string{
		"posts": "post", "categories": "category", "boxes": "box",
		"addresses": "address", "address": "address",
		"status": "status", "bonus": "bonus", // -us is not a plural
	} {
		if got := codegen.Singular(in); got != want {
			t.Errorf("Singular(%q) = %q, want %q", in, got, want)
		}
	}
}
