package codegen

// `sqlb docs` is the checklist counterpart of the OpenAPI document: a single
// Markdown file, one section per exposed endpoint, meant to be committed and
// hand-edited rather than regenerated and thrown away.
//
// It works like every other verb — the driver has already linked the schema
// package in, so opts.Registry holds every exposed table, action, mutation and
// query — but it does one thing none of the other emitters do: a rerun does
// not overwrite what a human or an agent wrote. Every endpoint's notes live in
// an HTML comment pair keyed by method and path, and a rerun reads the old
// file, keeps whatever it finds under a key that still exists, and files
// anything whose endpoint disappeared under "Archived notes" instead of
// discarding it. The header prose, the endpoint list and every declared
// Summary/Description are regenerated in full every time, because those already
// have one source of truth — the schema — and diverging from it is the failure
// this file exists to prevent for everything *below* them.

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"

	"github.com/jryannel/sqlb/schema"
)

// featuresPath resolves where `sqlb docs` writes, defaulting to a file beside
// the generated code so a project that never sets FeaturesFile still works.
func featuresPath(p Project, opts Options) string {
	if p.FeaturesFile != "" {
		return p.FeaturesFile
	}
	return filepath.Join(opts.Dir, "FEATURES.md")
}

// runDocs writes the feature checklist, merging in whatever notes the file
// already carries.
func runDocs(p Project, opts Options, reg *schema.Registry, stdout, stderr io.Writer) int {
	path := featuresPath(p, opts)
	existing, err := os.ReadFile(path)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		line(stderr, err)
		return 1
	}

	out, archived := renderFeatures(reg, existing)
	if dir := filepath.Dir(path); dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			line(stderr, fmt.Errorf("could not create %s: %w", dir, err))
			return 1
		}
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		line(stderr, fmt.Errorf("could not write %s: %w", path, err))
		return 1
	}

	line(stdout, path)
	say(stderr, "sqlb: wrote %s\n", path)
	if archived > 0 {
		say(stderr, "sqlb: %d note(s) archived — their endpoint is no longer in the schema\n", archived)
	}
	return 0
}

// notesPlaceholder is what a freshly rendered endpoint carries until someone
// — a coding agent, a teammate — replaces it.
const notesPlaceholder = "_Describe what this endpoint does: request/response shape, side effects, invariants._"

// endpoint is one row a resource exposes, or one declared action, mutation or
// query — enough to render a heading and, where the schema authored one, a
// description.
type endpoint struct {
	method      string
	path        string
	kind        string // "list", "create", "action: publish", ...
	description string
}

func (e endpoint) key() string { return e.method + " " + e.path }

// renderFeatures projects a registry into the checklist, carrying forward any
// notes the existing file has for an endpoint that still exists and archiving
// the rest. It returns the archived count so the caller can report it.
func renderFeatures(reg *schema.Registry, existing []byte) ([]byte, int) {
	notes, order := parseNotes(existing)
	used := map[string]bool{}

	var b bytes.Buffer
	b.WriteString("# API Features\n\n")
	b.WriteString("Generated by `sqlb docs` from the schema. The endpoint list and every\n")
	b.WriteString("description above a notes block are derived and rewritten on every run; the\n")
	b.WriteString("notes themselves survive a rerun, matched by method and path — this is where\n")
	b.WriteString("a coding agent or a teammate records what an endpoint actually does, so the\n")
	b.WriteString("file doubles as a feature checklist against a PRD.\n")

	for _, t := range reg.Tables() {
		rest := t.Rest()
		if rest == nil {
			continue
		}
		path := rest.Path
		if path == "" {
			path = "/" + t.LocalName()
		}

		fmt.Fprintf(&b, "\n## %s — `%s`\n", t.LocalName(), path)
		if c := t.Comment(); c != "" {
			fmt.Fprintf(&b, "\n%s\n", c)
		}

		for _, ep := range crudEndpoints(path, rest.Ops) {
			used[ep.key()] = true
			writeEndpoint(&b, ep, notes[ep.key()])
		}
		for _, a := range t.Actions() {
			ep := endpoint{
				method: http.MethodPost, path: a.FullPath(path),
				kind: "action: " + a.Name, description: a.Description,
			}
			used[ep.key()] = true
			writeEndpoint(&b, ep, notes[ep.key()])
		}
		for _, m := range t.Mutations() {
			ep := endpoint{
				method: http.MethodPost, path: m.FullPath(path),
				kind: "mutation: " + m.Name, description: m.Description,
			}
			used[ep.key()] = true
			writeEndpoint(&b, ep, notes[ep.key()])
		}
		for _, q := range t.Queries() {
			ep := endpoint{
				method: http.MethodGet, path: q.FullPath(path),
				kind: "query: " + q.Name, description: q.Description,
			}
			used[ep.key()] = true
			writeEndpoint(&b, ep, notes[ep.key()])
		}
	}

	archived := 0
	var stale []string
	for _, k := range order {
		if !used[k] {
			stale = append(stale, k)
		}
	}
	if len(stale) > 0 {
		b.WriteString("\n## Archived notes\n\n")
		b.WriteString("These endpoints no longer exist in the schema. Move anything still useful\n")
		b.WriteString("above, then delete this section.\n")
		for _, k := range stale {
			archived++
			fmt.Fprintf(&b, "\n### `%s`\n\n%s\n", k, notesBlock(k, notes[k]))
		}
	}

	return b.Bytes(), archived
}

// crudEndpoints lists the routes one resource's Ops mask actually mounts,
// mirroring rest.Resource's own dispatch (rest/rest.go): OpSingleton replaces
// the item path with the bare collection path for OpUpdate and OpDelete, and
// is mutually exclusive with OpList/OpRead.
func crudEndpoints(path string, ops schema.Op) []endpoint {
	var out []endpoint
	add := func(method, p, kind string) {
		out = append(out, endpoint{method: method, path: p, kind: kind})
	}
	item := path + "/{id}"

	if ops.Has(schema.OpSingleton) {
		add(http.MethodGet, path, "singleton")
		if ops.Has(schema.OpUpdate) {
			add(http.MethodPatch, path, "update")
		}
		if ops.Has(schema.OpDelete) {
			add(http.MethodDelete, path, "delete")
		}
		return out
	}

	if ops.Has(schema.OpList) {
		add(http.MethodGet, path, "list")
	}
	if ops.Has(schema.OpCreate) {
		add(http.MethodPost, path, "create")
	}
	if ops.Has(schema.OpRead) {
		add(http.MethodGet, item, "read")
	}
	if ops.Has(schema.OpUpdate) {
		add(http.MethodPatch, item, "update")
	}
	if ops.Has(schema.OpDelete) {
		add(http.MethodDelete, item, "delete")
	}
	return out
}

func writeEndpoint(b *bytes.Buffer, ep endpoint, existingNote string) {
	fmt.Fprintf(b, "\n### `%s %s` — %s\n", ep.method, ep.path, ep.kind)
	if ep.description != "" {
		fmt.Fprintf(b, "\n%s\n", ep.description)
	}
	b.WriteString("\n" + notesBlock(ep.key(), existingNote))
}

func notesBlock(key, note string) string {
	if note == "" {
		note = notesPlaceholder
	}
	return fmt.Sprintf("<!-- sqlb:notes %s -->\n%s\n<!-- /sqlb:notes -->\n", key, note)
}

// notesRE matches one notes block, capturing the key and the body between the
// markers. (?s) makes "." match a newline, so a multi-paragraph note round-trips.
var notesRE = regexp.MustCompile(`(?s)<!-- sqlb:notes (.+?) -->\n(.*?)\n<!-- /sqlb:notes -->`)

// parseNotes reads an existing FEATURES.md and returns its notes by endpoint
// key, plus the keys in the order they appeared — which is what lets a
// rerun's archive section list stale entries in a stable order instead of
// reshuffling them on every regeneration.
func parseNotes(existing []byte) (map[string]string, []string) {
	notes := map[string]string{}
	var order []string
	for _, m := range notesRE.FindAllSubmatch(existing, -1) {
		key := string(m[1])
		if _, ok := notes[key]; !ok {
			order = append(order, key)
		}
		notes[key] = string(m[2])
	}
	return notes, order
}
