package codegen

// The agent skill: what this project's schema declares, written where an agent
// working in the repository will find it.
//
// Every other emitter here produces something a program consumes — Go, Dart,
// TypeScript, JSON. This one produces instructions, and that difference is the
// whole of why it is written the way it is (ADR-0048).
//
// # Why this is generated rather than written
//
// The thing an agent gets wrong about sqlb is not the API, which it can read.
// It is which capabilities *this project* declared: capabilities are opt-in
// (ADR-0006), so a filter on a column that never said Filterable is a 400 at
// runtime and a wasted round trip. That answer is per-project by construction,
// so a static document cannot carry it and a generated one cannot be wrong for
// long — `sqlb check` fails when this file has drifted, which is the only reason
// it is safe to write instructions into a repository at all. A skill that has
// drifted from the schema is worse than no skill, because it is confidently
// wrong about the one thing it exists to know.
//
// # Structure, not prose
//
// This emitter carries names, types, capability flags and paths. It deliberately
// does **not** carry Comment strings, and that is a trust boundary rather than a
// style choice.
//
// The schema is first-party Go, so most of what is in a registry is text the
// project's own authors wrote. `sqlb introspect` breaks that: it reads a
// column's comment off a live database and calls Field.Comment, so an adopted
// database's comments become schema comments — and an adopted database is not
// first-party source. Every other emitter passes those through to DDL and to the
// OpenAPI document safely, because DDL and an OpenAPI document are read as
// *data*. A skill is read as *instructions*, so the same string arriving here
// would be an instruction written by whoever last commented that column.
//
// Hidden columns are absent for the reason the manifest gives for omitting them:
// a name is itself information. Reading the declaration is how someone learns
// what a table holds; this file says what the wire accepts.

import (
	"fmt"
	"strings"

	"github.com/jryannel/sqlb/schema"
)

// skillName is the directory the skill lands in, and the name in its
// frontmatter. The sqlb- prefix is deliberate: this file is written into a
// directory sqlb does not own, beside skills a project wrote itself and skills
// it installed, and a collision there is a silently shadowed instruction.
const skillName = "sqlb-schema"

// renderSkill writes the project-specific agent skill.
func renderSkill(opts Options) ([]byte, error) {
	m := opts.Registry.BuildManifest()
	if err := applyOverridesToManifest(m, opts); err != nil {
		return nil, err
	}

	var exposed, internal []schema.TableManifest
	for _, t := range m.Tables {
		if t.REST != nil {
			exposed = append(exposed, t)
			continue
		}
		internal = append(internal, t)
	}

	var b strings.Builder
	skillFrontmatter(&b, m, exposed)
	skillHeading(&b, m, exposed, internal)
	skillCommands(&b, opts)
	skillWireSurface(&b, exposed)
	skillInternalTables(&b, internal)
	skillObligations(&b, m)
	skillLimits(&b)
	return []byte(b.String()), nil
}

// skillFrontmatter writes the YAML header. The description is the trigger rather
// than documentation: an agent decides whether to load this file from that one
// sentence, and "use this when working with sqlb" does not fire on "add a due
// date to invoices", which is the sentence that actually arrives. So it names
// the project's real tables.
func skillFrontmatter(b *strings.Builder, m *schema.Manifest, exposed []schema.TableManifest) {
	b.WriteString("---\n")
	fmt.Fprintf(b, "name: %s\n", skillName)

	subjects := make([]string, 0, len(m.Tables))
	for _, t := range m.Tables {
		subjects = append(subjects, t.Name)
	}

	fmt.Fprintf(b, "description: %s\n", oneLine(fmt.Sprintf(
		"Use when editing this project's sqlb schema or writing a query, filter, sort or REST "+
			"request against its tables: %s. Says which columns each resource actually accepts — "+
			"capabilities are opt-in, so anything not listed here is rejected at runtime — "+
			"and the commands to run after a schema edit. Generated from the schema declaration.",
		skillSubjects(subjects))))
	b.WriteString("---\n\n")
}

func skillHeading(b *strings.Builder, m *schema.Manifest, exposed, internal []schema.TableManifest) {
	b.WriteString("# This project's sqlb schema\n\n")

	if m.Module != "" {
		fmt.Fprintf(b, "Module `%s`. ", m.Module)
	}
	fmt.Fprintf(b, "%s declared, %s on the wire",
		count(len(m.Tables), "table"), plainCount(len(exposed)))
	if len(internal) > 0 {
		fmt.Fprintf(b, ", %s not exposed", plainCount(len(internal)))
	}
	b.WriteString(".\n\n")

	b.WriteString("**Generated by `sqlb generate` — do not edit.** `sqlb check` fails when this " +
		"file has drifted from the schema, so an edit here is reverted by the next generate " +
		"rather than kept. Change the schema declaration instead.\n\n")
}

// skillCommands writes what to run after a schema edit — the step most often
// missed, because nothing about editing a Go file suggests that four other
// artefacts now disagree with it.
func skillCommands(b *strings.Builder, opts Options) {
	b.WriteString("## After editing the schema\n\n")

	pkg := opts.SkillSchemaPackage
	if pkg == "" {
		b.WriteString("Regenerate every artefact, then write the migration that closes the gap:\n\n")
		b.WriteString("```bash\ngo generate ./...\n```\n\n")
		b.WriteString("If the schema package carries no `//go:generate` directive, name it " +
			"explicitly — `sqlb generate ./yourschema`.\n\n")
	} else {
		b.WriteString("Regenerate every artefact, then write the migration that closes the gap:\n\n")
		fmt.Fprintf(b, "```bash\nsqlb generate %s\n```\n\n", pkg)
		fmt.Fprintf(b, "```bash\nsqlb migrate -name describes_what_changed %s\n```\n\n", pkg)
	}

	b.WriteString("Generating needs no database. Writing a migration replays the committed " +
		"history into a scratch Postgres, because the trustworthy answer to \"what does the " +
		"schema look like now\" is what the migrations build rather than what a live database " +
		"drifted into.\n\n")
	b.WriteString("A schema edit is also an API edit. `sqlb impact` reports what it did to the " +
		"REST contract against the checked-in baseline, and the sharpest breaks — un-exposing a " +
		"column, dropping an operation, a rename — produce no DDL at all, so the migration diff " +
		"will not mention them.\n\n")
}

// skillWireSurface is the payload: per resource, exactly what a request may ask
// for. Anything absent is a rejection rather than an oversight, which is the
// sentence this whole file exists to make available before the 400 rather than
// after it.
func skillWireSurface(b *strings.Builder, exposed []schema.TableManifest) {
	b.WriteString("## The wire surface\n\n")

	if len(exposed) == 0 {
		b.WriteString("No table declares a REST surface, so this schema generates models and a " +
			"typed column facade and no endpoints. Queries go through the builder; there is " +
			"nothing here for a request to reach.\n\n")
		return
	}

	b.WriteString("| Resource | Path | Operations | Page size |\n|---|---|---|---|\n")
	for _, t := range exposed {
		r := t.REST
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n",
			t.Name, r.Path, joinCode(r.Operations, " "), pageSize(r))
	}
	b.WriteString("\n")

	for _, t := range exposed {
		skillResource(b, t)
	}
}

func skillResource(b *strings.Builder, t schema.TableManifest) {
	r := t.REST
	fmt.Fprintf(b, "### `%s`\n\n", t.Name)

	if t.PrimaryKey != "" {
		fmt.Fprintf(b, "Addressed by `%s`. ", t.PrimaryKey)
	}
	fmt.Fprintf(b, "`%s`\n\n", r.Path)

	rows := [][2]string{
		{"Filterable", joinCode(r.Filterable, ", ")},
		{"Sortable", joinCode(r.Sortable, ", ")},
		{"Searchable", joinCode(r.Searchable, ", ")},
		{"Expandable", joinCode(r.Expandable, ", ")},
	}
	b.WriteString("| Capability | Columns |\n|---|---|\n")
	for _, row := range rows {
		value := row[1]
		if value == "" {
			// Named rather than dropped: "nothing is sortable here" is a fact a
			// caller needs, and an absent row reads as an incomplete document.
			value = "*none*"
		}
		fmt.Fprintf(b, "| %s | %s |\n", row[0], value)
	}
	b.WriteString("\n")

	if r.MaxFilters > 0 {
		fmt.Fprintf(b, "At most %d filters per request.\n\n", r.MaxFilters)
	}

	skillEnums(b, t)

	if len(r.Actions) > 0 {
		b.WriteString("**Declared actions.** Domain verbs this resource owns. " +
			"Reaching the same outcome by PATCHing a column is the mistake these exist to " +
			"prevent — the verb owns the transition.\n\n")
		b.WriteString("| Verb | Route | Writes |\n|---|---|---|\n")
		for _, a := range r.Actions {
			fmt.Fprintf(b, "| `%s` | `%s %s` | %s |\n",
				a.Name, a.Method, a.Path, orNone(joinCode(a.Writes, ", ")))
		}
		b.WriteString("\n")
	}

	if len(t.CollectedBy) > 0 {
		b.WriteString("**Collects.** Rows of another table this one gathers, and the name " +
			"`?expand` knows them by.\n\n")
		b.WriteString("| Relation | Table | Via | Expandable |\n|---|---|---|---|\n")
		for _, inv := range t.CollectedBy {
			fmt.Fprintf(b, "| `%s` | `%s` | `%s` | %s |\n",
				inv.Name, inv.Table, inv.Column, yesNo(inv.Expandable))
		}
		b.WriteString("\n")
	}
}

// skillEnums names the values a constrained column accepts.
//
// This is the one thing the per-column table carried that belongs here rather
// than with it. Measured against twelve real application schemas, that table was
// 44–49% of the document and mostly described what a *response* holds — types,
// nullability, which columns are read-only — none of which a request has to get
// right. An enum is the exception: `?status=eq.active` against a column whose
// values are todo/in_progress/blocked/done is a rejection, and the valid list is
// not guessable from the column's name. So the values stay and the table goes.
//
// One line per constrained column, and nothing when a resource has none.
func skillEnums(b *strings.Builder, t schema.TableManifest) {
	var lines []string
	for _, c := range t.Columns {
		if len(c.Enum) == 0 {
			continue
		}
		lines = append(lines, fmt.Sprintf("`%s` is one of %s", c.Name, joinCode(c.Enum, " ")))
	}
	if len(lines) == 0 {
		return
	}
	fmt.Fprintf(b, "Values: %s.\n\n", strings.Join(lines, "; "))
}

func skillInternalTables(b *strings.Builder, internal []schema.TableManifest) {
	if len(internal) == 0 {
		return
	}
	b.WriteString("## Declared, not exposed\n\n")
	b.WriteString("These have models and typed columns but no endpoint. Reaching one means " +
		"writing a query, not calling an API — and exposing it is a schema edit with a REST " +
		"contract change attached.\n\n")
	for _, t := range internal {
		fmt.Fprintf(b, "- `%s`", t.Name)
		if t.PrimaryKey != "" {
			fmt.Fprintf(b, " — addressed by `%s`", t.PrimaryKey)
		}
		b.WriteString("\n")
	}
	b.WriteString("\n")
}

// skillObligations names the tables whose declaration is a promise the
// application has to keep. A resource that declares its rows confined does not
// mount without the hook that confines them, so this is the list of places where
// a missing registration is a refusal to start rather than a silent leak.
func skillObligations(b *strings.Builder, m *schema.Manifest) {
	type obligation struct {
		table  string
		column string
		kind   string
	}
	var obs []obligation
	for _, t := range m.Tables {
		for _, c := range t.Columns {
			if c.Scoped {
				obs = append(obs, obligation{t.Name, c.Name, "scoped"})
			}
			if c.SoftDelete {
				obs = append(obs, obligation{t.Name, c.Name, "soft-delete"})
			}
		}
	}
	if len(obs) == 0 {
		return
	}

	b.WriteString("## Obligations this schema carries\n\n")
	b.WriteString("A declaration that rows are confined is an obligation, not a comment. " +
		"These tables refuse to register without the hook that enforces them, so a missing " +
		"registration fails at mount rather than leaking rows at runtime.\n\n")
	b.WriteString("| Table | Column | Declares |\n|---|---|---|\n")
	for _, o := range obs {
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", o.table, o.column, o.kind)
	}
	b.WriteString("\n")
}

// skillLimits is the honesty section. A generated document that reads as
// complete is worse than one that reads as partial, because the reader stops
// looking at exactly the wrong moment.
func skillLimits(b *strings.Builder) {
	b.WriteString("## What this file does not say\n\n")
	b.WriteString("- **Anything absent is a rejection, not an oversight.** Capabilities are " +
		"opt-in. A column missing from `Filterable` above cannot be filtered on, and the error " +
		"names what would have been accepted — so read the list rather than guessing and " +
		"retrying.\n")
	b.WriteString("- **No descriptions or comments are carried here,** deliberately. " +
		"A column comment can arrive from an introspected database rather than from this " +
		"project's authors, and this file is read as instructions. Read the schema declaration " +
		"for what a column means.\n")
	b.WriteString("- **This is what a request may ask for, not what a table holds.** There is no " +
		"column listing here on purpose — the types, the nullability and which columns are " +
		"read-only are all in the generated models, and repeating them made this file twice as " +
		"long without making a request more likely to be accepted. The models and the " +
		"declaration are where a column's shape lives.\n")
	b.WriteString("- **Nothing here says how to write a query.** Where the builder ends and " +
		"`Raw` or hand-written SQL begins is a separate question, and the failure modes that " +
		"matter there compile and pass their tests.\n")
	b.WriteString("- **One column has one wire spelling,** derived from its name. There is no " +
		"mapping layer and no per-field override in either direction, so the column names " +
		"above are also the JSON field names.\n")
}

// Helpers. Each keeps a formatting decision in one place so that two sections
// cannot spell the same thing two ways — the generated file is compared byte for
// byte by `sqlb check`, so consistency here is correctness rather than taste.

// pageSize renders the declared ceilings, and says nothing about the ones a
// schema left to the runtime. A zero in the manifest means undeclared, and
// printing it as "0" would read as a resource that returns no rows.
func pageSize(r *schema.RESTManifest) string {
	switch {
	case r.DefaultPageSize > 0 && r.MaxPageSize > 0:
		return fmt.Sprintf("%d, max %d", r.DefaultPageSize, r.MaxPageSize)
	case r.MaxPageSize > 0:
		return fmt.Sprintf("max %d", r.MaxPageSize)
	case r.DefaultPageSize > 0:
		return fmt.Sprintf("%d", r.DefaultPageSize)
	}
	return "*default*"
}

func joinCode(items []string, sep string) string {
	if len(items) == 0 {
		return ""
	}
	quoted := make([]string, 0, len(items))
	for _, s := range items {
		quoted = append(quoted, "`"+s+"`")
	}
	return strings.Join(quoted, sep)
}

func orNone(s string) string {
	if s == "" {
		return "*none*"
	}
	return s
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}

func count(n int, noun string) string {
	if n == 1 {
		return fmt.Sprintf("1 %s", noun)
	}
	return fmt.Sprintf("%d %ss", n, noun)
}

func plainCount(n int) string { return fmt.Sprintf("%d", n) }

// skillSubjects renders the table-name list the description triggers on, bounded
// by characters as well as by count.
//
// Both bounds are load-bearing and the second was missing until a guard found it.
// The agent tooling truncates a description past a documented ceiling and simply
// does not see the tail, so a budget overrun is silent — and counting names is not
// enough, because twelve names of a module-qualified length overrun it on their
// own. maxChars leaves the surrounding sentence room inside the ceiling.
func skillSubjects(names []string) string {
	const maxNames = 12
	const maxChars = 480

	var kept []string
	used := 0
	for _, n := range names {
		if len(kept) >= maxNames || used+len(n)+2 > maxChars {
			break
		}
		kept = append(kept, n)
		used += len(n) + 2
	}
	switch {
	case len(kept) == 0:
		return "none"
	case len(kept) == len(names):
		return andList(kept)
	}
	// "a, b and 28 more" would read as though 28 more were a table. The comma
	// form is the one that does not — and it is a separate branch because
	// andList's final "and" would otherwise double up with this one.
	return fmt.Sprintf("%s, and %d more", strings.Join(kept, ", "), len(names)-len(kept))
}

// andList renders a human list: "a, b and c".
func andList(items []string) string {
	switch len(items) {
	case 0:
		return "none"
	case 1:
		return items[0]
	}
	return strings.Join(items[:len(items)-1], ", ") + " and " + items[len(items)-1]
}

// oneLine flattens whitespace, because a YAML frontmatter value spanning two
// lines is a different document than the one intended.
func oneLine(s string) string { return strings.Join(strings.Fields(s), " ") }
