package codegen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jryannel/sqlb/codegen"
	"github.com/jryannel/sqlb/schema"
)

// tsFixture is restFixture plus an expandable reference in both directions, so
// that the emitted client has something to narrow a response by.
func tsFixture() *schema.Registry {
	r := schema.NewRegistry()
	org := r.Table("orgs",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("name").Sortable(),
	).Expose(schema.REST{Ops: schema.OpRead | schema.OpList})

	r.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("org", org).OnDelete(schema.Cascade).Immutable().Filterable().
			Expandable().Inverse("posts").InverseExpandable(),
		schema.Text("title").Searchable().Sortable(),
		schema.Enum("status", "draft", "published").Default(schema.Value("draft")).Filterable(),
		schema.BigInt("view_count").ReadOnly().Filterable(),
		schema.Timestamp("published_at").Nullable().Filterable().Sortable(),
		schema.Text("secret").Hidden(),
	).Expose(schema.REST{Ops: schema.CRUD | schema.OpList, MaxPageSize: 50})
	return r
}

// generateTS returns the emitted TypeScript, keyed by file name.
func generateTS(t *testing.T, r *schema.Registry) map[string]string {
	t.Helper()
	dir := t.TempDir()
	files, err := codegen.Generate(codegen.Options{
		Registry: r, Dir: dir, Package: "gen", TSDir: "web/api",
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := map[string]string{}
	for _, f := range files {
		if filepath.Ext(f) != ".ts" {
			continue
		}
		b, err := os.ReadFile(f)
		if err != nil {
			t.Fatal(err)
		}
		out[filepath.Base(f)] = string(b)
	}
	if len(out) == 0 {
		t.Fatal("no TypeScript was emitted")
	}
	return out
}

func TestTSRowTypesFollowTheWire(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	for _, want := range []string{
		"// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.",
		"export interface Post {",
		"id: string;",
		"org_id: string;",                  // snake_case, because that is the wire spelling
		"view_count: number;",              // bigint is a JSON number
		"Values above 2^53 lose precision", // and the loss is silent, so it is stated
		"status: PostStatus;",              // enum keeps its type
		"published_at: string | null;",     // nullable, and a timestamp is a string
		"export type PostStatus = 'draft' | 'published';",
	} {
		if !contains(src, want) {
			t.Errorf("row types missing %q:\n%s", want, src)
		}
	}

	// A hidden column has no spelling here at all: not in the row, not in the
	// projection vocabulary, not as a filter. This is the same guarantee the
	// typed column facade gives Go, carried across the wire.
	for _, forbidden := range []string{"secret"} {
		if contains(src, forbidden) {
			t.Errorf("a hidden column leaked into the client:\n%s", src)
		}
	}
}

func TestTSBodiesOmitWhatAClientMayNotSet(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	create := section(t, src, "export interface PostCreate {", "\n}")
	for _, want := range []string{
		"title: string;",                // required
		"status?: PostStatus;",          // defaulted → optional
		"published_at?: string | null;", // nullable → optional, and nullable
	} {
		if !contains(create, want) {
			t.Errorf("create body missing %q:\n%s", want, create)
		}
	}
	// "{ id:" rather than "id:", which org_id would satisfy.
	for _, forbidden := range []string{"{ id:", "view_count", "secret"} {
		if contains(create, forbidden) {
			t.Errorf("create body should not carry %s:\n%s", forbidden, create)
		}
	}

	// An immutable column is settable once, at create, so the patch body has no
	// property for it — the same set the Go patch body uses.
	patch := section(t, src, "export interface PostPatch {", "\n}")
	if contains(patch, "org_id") {
		t.Errorf("an immutable column should be absent from the patch body:\n%s", patch)
	}
	if !contains(patch, "title?: string;") {
		t.Errorf("every patch property is optional:\n%s", patch)
	}
}

// The operator vocabulary per column is the thing an OpenAPI document cannot
// say, and the reason this generator exists rather than openapi-typescript.
func TestTSFilterOperatorsAreNarrowedByColumnType(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]
	where := section(t, src, "export type PostWhere = {", "\n};")

	for _, want := range []string{
		"org_id?: Cond<string>;",                         // no pattern operators
		"status?: Cond<PostStatus>;",                     // an enum compares by equality
		"view_count?: Cond<number>;",                     // nor on a number
		"published_at?: Cond<string | Date, NullCheck>;", // nullable → null tests
	} {
		if !contains(where, want) {
			t.Errorf("filter conditions missing %q:\n%s", want, where)
		}
	}
	// title is Searchable, which implies Filterable, and it is text — so it is
	// the one column that gets the pattern operators.
	if !contains(where, "title?: Cond<string, TextMatch>;") {
		t.Errorf("a text column should offer the pattern operators:\n%s", where)
	}
}

func TestTSVocabulariesComeFromCapabilities(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	sort := section(t, src, "export type PostSort =", ";")
	for _, want := range []string{"'title'", "'-title'", "'published_at'", "'-published_at'"} {
		if !contains(sort, want) {
			t.Errorf("sort union missing %s:\n%s", want, sort)
		}
	}
	// status is filterable but not sortable, so it has no spelling in ?sort.
	if contains(sort, "'status'") {
		t.Errorf("a column that did not opt in to sorting should not be sortable:\n%s", sort)
	}

	if !contains(src, "export type PostExpand = 'org';") {
		t.Errorf("the forward relation should be expandable:\n%s", src)
	}
	if !contains(src, "export type OrgExpand = 'posts';") {
		t.Errorf("the declared inverse should be expandable from the other side:\n%s", src)
	}
}

// Expansion narrows by direction: an object forward, a capped envelope back.
// Typing the reverse as a bare array would reproduce on the client the silent
// truncation the envelope exists to prevent on the server.
func TestTSExpansionKeepsTheCollectionEnvelope(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	if !contains(src, "& ('org' extends E ? { org: Org } : unknown)") {
		t.Errorf("a forward expansion should resolve to the row type:\n%s", src)
	}
	if !contains(src, "& ('posts' extends E ? { posts: Collection<Post> } : unknown)") {
		t.Errorf("a reverse expansion should keep the Collection envelope:\n%s", src)
	}
}

// The envelope itself lives in the runtime now, once per output directory
// rather than once per module (#110). The property is unchanged — Page extends
// Collection rather than restating it — only its address is.
func TestTSPageEnvelopeExtendsCollection(t *testing.T) {
	src := generateTS(t, tsFixture())["runtime.gen.ts"]
	if !contains(src, "export interface Page<T> extends Collection<T> {") {
		t.Errorf("the page envelope should extend the collection rather than restate it:\n%s", src)
	}
}

func TestTSTransportFollowsTheExposedOperations(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	for _, want := range []string{
		"export function listPosts<S extends PostColumn = PostColumn, E extends PostExpand = never>(",
		"path: '/posts', query: encodeListQuery(params)",
		"export function getPost<E extends PostExpand = never>(",
		"export function createPost(request: Transport, body: PostCreate",
		"export function updatePost(request: Transport, id: string | number, body: PostPatch",
		"export function deletePost(request: Transport, id: string | number",
	} {
		if !contains(src, want) {
			t.Errorf("transport missing %q:\n%s", want, src)
		}
	}
	// orgs expose read and list only, so nothing that writes one is emitted.
	for _, forbidden := range []string{"function createOrg", "function updateOrg", "function deleteOrg"} {
		if contains(src, forbidden) {
			t.Errorf("an unexposed operation should not be reachable: %s", forbidden)
		}
	}
	// The item endpoint declares no ?select, so the params type does not offer
	// one — a client that sends it gets a 400 from a server that rejects
	// unknown query parameters.
	get := section(t, src, "export interface PostGetParams<E extends PostExpand = never> {", "\n}")
	if contains(get, "select") {
		t.Errorf("the item endpoint has no ?select:\n%s", get)
	}
}

func TestTSKeysAreDerivedFromTheTable(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	for _, want := range []string{
		"export const postKeys = {",
		"all: () => ['posts'] as const,",
		"list: (params: unknown = {}) => ['posts', 'list', params] as const,",
		"detail: (id: string | number, params: unknown = {}) => ['posts', 'detail', String(id), params] as const,",
		// The table-keyed index is what makes a change-feed event mechanical:
		// one list, so a subscriber and a mutation handler cannot disagree.
		"export const keysByTable = {",
		"posts: postKeys,",
	} {
		if !contains(src, want) {
			t.Errorf("key factory missing %q:\n%s", want, src)
		}
	}
}

func TestTSQueriesAreTheOnlyFileThatNeedsTanStack(t *testing.T) {
	files := generateTS(t, tsFixture())
	client, queries := files["client.gen.ts"], files["queries.gen.ts"]

	// The client imports its own runtime and nothing else. That is the claim
	// worth holding: no framework, no bundler assumption, no pub package — a
	// sibling generated file is not a dependency (#110).
	for _, line := range strings.Split(client, "\n") {
		if !strings.HasPrefix(line, "import ") {
			continue
		}
		if !strings.Contains(line, "'./runtime.gen.ts'") {
			t.Errorf("the client imports something other than its runtime: %s", line)
		}
	}
	// And the runtime, which is what the client imports, imports nothing at all.
	if strings.Contains(files["runtime.gen.ts"], "import ") {
		t.Errorf("the runtime file should import nothing:\n%s", files["runtime.gen.ts"])
	}
	for _, want := range []string{
		"import { infiniteQueryOptions, queryOptions } from '@tanstack/react-query';",
		"export function postQueries(request: Transport) {",
		"queryKey: postKeys.list(params),",
		"getNextPageParam: (last) => last.next_cursor,",
		// page and cursor are two answers to where a page starts, so the
		// infinite factory owns both rather than letting a caller send one.
		"infinite: <S extends PostColumn = PostColumn, E extends PostExpand = never>(params: Omit<PostListParams<S, E>, 'page' | 'cursor'> = {}) =>",
	} {
		if !contains(queries, want) {
			t.Errorf("queries missing %q:\n%s", want, queries)
		}
	}
}

// No TSDir means no TypeScript, which is the right default for a project that
// has no TypeScript consumer.
func TestNoTypeScriptUnlessAsked(t *testing.T) {
	dir := t.TempDir()
	files, err := codegen.Generate(codegen.Options{Registry: tsFixture(), Dir: dir, Package: "gen"})
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		if filepath.Ext(f) == ".ts" {
			t.Errorf("TypeScript was emitted without TSDir: %s", f)
		}
	}
}

// A schema with no REST surface has no client to generate, and a file of empty
// factories is worse than no file.
func TestNoQueriesFileWhenNothingIsExposed(t *testing.T) {
	r := schema.NewRegistry()
	r.Table("orgs", schema.UUIDv7("id").PrimaryKey(), schema.Text("name"))

	files := generateTS(t, r)
	if _, ok := files["queries.gen.ts"]; ok {
		t.Error("an unexposed schema should not get a TanStack file")
	}
	// The row types are still worth having: a table can be read from Go and
	// still be a shape the frontend has to name.
	if !contains(files["client.gen.ts"], "export interface Org {") {
		t.Error("row types should be emitted even with nothing exposed")
	}
}

// The TypeScript is part of the committed output, so the staleness gate has to
// see it — otherwise the client silently describes a schema the server no
// longer has.
func TestCheckSeesTheTypeScript(t *testing.T) {
	dir := t.TempDir()
	opts := codegen.Options{Registry: tsFixture(), Dir: dir, Package: "gen", TSDir: "web/api"}
	if _, err := codegen.Generate(opts); err != nil {
		t.Fatal(err)
	}
	if stale, err := codegen.Check(opts); err != nil || len(stale) > 0 {
		t.Fatalf("freshly generated output should be current: %v %v", stale, err)
	}

	path := filepath.Join(dir, "web", "api", "client.gen.ts")
	if err := os.WriteFile(path, []byte("// edited by hand\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	stale, err := codegen.Check(opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(stale) != 1 || !strings.Contains(stale[0], "client.gen.ts") {
		t.Errorf("an edited client should be reported stale, got %v", stale)
	}
}

// section returns the emitted text between two markers, so an assertion about
// one declaration cannot be satisfied by a match somewhere else in the file.
func section(t *testing.T, src, from, to string) string {
	t.Helper()
	start := strings.Index(src, from)
	if start < 0 {
		t.Fatalf("%q not found in:\n%s", from, src)
	}
	rest := src[start:]
	end := strings.Index(rest, to)
	if end < 0 {
		t.Fatalf("%q not found after %q", to, from)
	}
	return rest[:end+len(to)]
}
