-- Generated by sqlb. Review before applying.

-- +goose Up
-- create table customers
-- +goose StatementBegin
CREATE TABLE "customers" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "email" text NOT NULL,
    "name" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "customers_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "customers_email_key" UNIQUE ("email")
);
COMMENT ON TABLE "customers" IS 'Whoever a ticket is on behalf of.';
-- +goose StatementEnd
-- create table tickets
-- +goose StatementBegin
CREATE TABLE "tickets" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "customer_id" uuid NOT NULL,
    "subject" varchar(80) NOT NULL,
    "body" text NOT NULL,
    "status" text NOT NULL DEFAULT 'open',
    "legacy_ref" text,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "tickets_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "tickets_status_check" CHECK ("status" IN ('open', 'pending', 'closed'))
);
COMMENT ON TABLE "tickets" IS 'One request from one customer.';
-- +goose StatementEnd
-- add foreign key tickets_customer_id_fkey
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_customer_id_fkey" FOREIGN KEY ("customer_id") REFERENCES "customers" ("id") ON DELETE CASCADE;

-- +goose Down
ALTER TABLE "tickets" DROP CONSTRAINT "tickets_customer_id_fkey";
DROP TABLE "tickets";
DROP TABLE "customers";
