-- Generated by sqlb. Review before applying.

-- +goose Up
-- create table agents
-- +goose StatementBegin
CREATE TABLE "agents" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "email" text NOT NULL,
    "name" text NOT NULL,
    "active" boolean NOT NULL DEFAULT true,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "agents_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "agents_email_key" UNIQUE ("email")
);
COMMENT ON TABLE "agents" IS 'Someone who answers tickets.';
-- +goose StatementEnd
-- add column tickets.priority
ALTER TABLE "tickets" ADD COLUMN "priority" text NOT NULL DEFAULT 'normal';
-- add constraint tickets_priority_check (existing rows must already satisfy
--   it or this fails)
-- LOCK ACCESS EXCLUSIVE: checking that every row of tickets already
--   satisfies the constraint scans the whole table with all access blocked.
--   Add it NOT VALID first, then VALIDATE CONSTRAINT in a later migration.
--   The NOT VALID add still takes a lock of its own, but holds it only for
--   as long as the catalog write takes; the validation that follows takes
--   SHARE UPDATE EXCLUSIVE, which readers and writers pass through.
--   migrate.Unblock writes that sequence for you.
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_priority_check" CHECK ("priority" IN ('low', 'normal', 'high', 'urgent'));

-- +goose Down
ALTER TABLE "tickets" DROP CONSTRAINT "tickets_priority_check";
ALTER TABLE "tickets" DROP COLUMN "priority";
DROP TABLE "agents";
