-- +goose NO TRANSACTION
-- Index changes cannot run inside a transaction, so this file is not
-- wrapped in one. It contains only index changes for that reason.
-- Generated by sqlb. Review before applying.

-- +goose Up
-- index tickets_customer_id_status_idx
CREATE INDEX CONCURRENTLY "tickets_customer_id_status_idx" ON "tickets" ("customer_id", "status");

-- +goose Down
DROP INDEX CONCURRENTLY "tickets_customer_id_status_idx";
