-- Generated by sqlb. Review before applying.

-- +goose Up
-- change type of tickets.subject from varchar(80) to text (free in this
--   direction; reversing it rewrites the table)
ALTER TABLE "tickets" ALTER COLUMN "subject" TYPE text;

-- +goose Down
ALTER TABLE "tickets" ALTER COLUMN "subject" TYPE varchar(80);
