-- Generated by sqlb. Review before applying.

-- +goose Up
-- rename customers.email to email_address
ALTER TABLE "customers" RENAME COLUMN "email" TO "email_address";
-- rename constraint customers_email_key to customers_email_address_key
ALTER TABLE "customers" RENAME CONSTRAINT "customers_email_key" TO "customers_email_address_key";
-- rename table agents to support_agents
ALTER TABLE "agents" RENAME TO "support_agents";
-- rename constraint agents_email_key to support_agents_email_key
ALTER TABLE "support_agents" RENAME CONSTRAINT "agents_email_key" TO "support_agents_email_key";
-- rename constraint agents_pkey to support_agents_pkey
ALTER TABLE "support_agents" RENAME CONSTRAINT "agents_pkey" TO "support_agents_pkey";

-- +goose Down
ALTER TABLE "support_agents" RENAME CONSTRAINT "support_agents_pkey" TO "agents_pkey";
ALTER TABLE "support_agents" RENAME CONSTRAINT "support_agents_email_key" TO "agents_email_key";
ALTER TABLE "support_agents" RENAME TO "agents";
ALTER TABLE "customers" RENAME CONSTRAINT "customers_email_address_key" TO "customers_email_key";
ALTER TABLE "customers" RENAME COLUMN "email_address" TO "email";
