-- Generated by sqlb. Review before applying.

-- +goose Up
-- drop column tickets.legacy_ref
ALTER TABLE "tickets" DROP COLUMN "legacy_ref";

-- +goose Down
ALTER TABLE "tickets" ADD COLUMN "legacy_ref" text;
