-- Generated by sqlb. Review before applying.

-- +goose Up
-- create table lists
-- +goose StatementBegin
CREATE TABLE "lists" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "name" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "lists_pkey" PRIMARY KEY ("id")
);
COMMENT ON TABLE "lists" IS 'A group of tasks.';
-- +goose StatementEnd
-- create table tasks
-- +goose StatementBegin
CREATE TABLE "tasks" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "list_id" uuid NOT NULL,
    "title" text NOT NULL,
    "status" text NOT NULL DEFAULT 'todo',
    "due_at" timestamptz,
    "completed_at" timestamptz,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "tasks_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "tasks_status_check" CHECK ("status" IN ('todo', 'done')),
    CONSTRAINT "done_tasks_have_a_completion_time" CHECK (status <> 'done' OR completed_at IS NOT NULL)
);
COMMENT ON TABLE "tasks" IS 'A unit of work, belonging to one list.';
-- +goose StatementEnd
-- add foreign key tasks_list_id_fkey
ALTER TABLE "tasks" ADD CONSTRAINT "tasks_list_id_fkey" FOREIGN KEY ("list_id") REFERENCES "lists" ("id") ON DELETE CASCADE;
-- index tasks_due_at_idx
CREATE INDEX "tasks_due_at_idx" ON "tasks" ("due_at");
-- index tasks_list_id_idx
CREATE INDEX "tasks_list_id_idx" ON "tasks" ("list_id");

-- +goose Down
DROP INDEX "tasks_list_id_idx";
DROP INDEX "tasks_due_at_idx";
ALTER TABLE "tasks" DROP CONSTRAINT "tasks_list_id_fkey";
DROP TABLE "tasks";
DROP TABLE "lists";
