// Package migrations carries tasks2's checked-in migration history and
// applies it with goose.
//
// The files are generated by `sqlb migrate` and applied by a runner sqlb has
// nothing to do with — the same split example/tasks/migrations documents.
// Embedding them means `go run ./cmd/server` against an empty database works
// with no separate step: this is the "one stop shop" a server binary that
// embeds its own migration runner buys, as opposed to a developer who has to
// know to run something else first.
package migrations

import (
	"context"
	"database/sql"
	"embed"
	"fmt"

	"github.com/pressly/goose/v3"
)

//go:embed *.sql
var files embed.FS

// Apply brings the database up to the latest migration.
//
// goose records what it has applied in its own version table, so this is safe
// to call at every start: an up-to-date database is a no-op and a fresh one is
// built from nothing. Doing it at startup suits this example's single
// instance; it does not suit a rolling deploy — see example/tasks/migrations
// for the caveat this is copied from.
func Apply(ctx context.Context, db *sql.DB) error {
	goose.SetBaseFS(files)
	if err := goose.SetDialect("postgres"); err != nil {
		return fmt.Errorf("migrations: %w", err)
	}
	if err := goose.UpContext(ctx, db, "."); err != nil {
		return fmt.Errorf("migrations: applying: %w", err)
	}
	return nil
}
