// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.

package tasks

import "time"

// Comment a comment on a task.
type Comment struct {
	ID          string     `db:"id" json:"id" sqlb:"pk,default,filter,readonly"`
	WorkspaceID string     `db:"workspace_id" json:"workspace_id" sqlb:"filter,readonly"`
	TaskID      string     `db:"task_id" json:"task_id" sqlb:"filter,immutable"`
	AuthorID    string     `db:"author_id" json:"author_id" sqlb:"filter,readonly"`
	Body        string     `db:"body" json:"body" sqlb:"filter,search"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at" sqlb:"default,sort,readonly"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at" sqlb:"default,sort,readonly"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at" sqlb:"readonly"`
}

// TableName is the table Comment maps to.
func (Comment) TableName() string { return "comments" }

// List a named list of tasks within a workspace.
type List struct {
	ID          string     `db:"id" json:"id" sqlb:"pk,default,filter,readonly"`
	WorkspaceID string     `db:"workspace_id" json:"workspace_id" sqlb:"filter,readonly"`
	Name        string     `db:"name" json:"name" sqlb:"filter,sort,search"`
	Description string     `db:"description" json:"description" sqlb:"filter,search"`
	Color       string     `db:"color" json:"color" sqlb:"default,filter"`
	Position    int32      `db:"position" json:"position" sqlb:"default,sort"`
	Archived    bool       `db:"archived" json:"archived" sqlb:"default,filter,sort"`
	CreatedAt   time.Time  `db:"created_at" json:"created_at" sqlb:"default,sort,readonly"`
	UpdatedAt   time.Time  `db:"updated_at" json:"updated_at" sqlb:"default,sort,readonly"`
	DeletedAt   *time.Time `db:"deleted_at" json:"deleted_at" sqlb:"readonly"`
}

// TableName is the table List maps to.
func (List) TableName() string { return "lists" }

// MembershipRole is the memberships.role column's value set.
type MembershipRole string

const (
	MembershipRoleOwner  MembershipRole = "owner"
	MembershipRoleAdmin  MembershipRole = "admin"
	MembershipRoleMember MembershipRole = "member"
)

// Membership a user's membership of a workspace, and their role in it.
type Membership struct {
	ID          string         `db:"id" json:"id" sqlb:"pk,default,filter,readonly"`
	WorkspaceID string         `db:"workspace_id" json:"workspace_id" sqlb:"filter,readonly"`
	UserID      string         `db:"user_id" json:"user_id" sqlb:"filter"`
	Role        MembershipRole `db:"role" json:"role" sqlb:"default,filter,sort"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at" sqlb:"default,sort,readonly"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at" sqlb:"default,sort,readonly"`
}

// TableName is the table Membership maps to.
func (Membership) TableName() string { return "memberships" }

// TaskStatus is the tasks.status column's value set.
type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusBlocked    TaskStatus = "blocked"
	TaskStatusDone       TaskStatus = "done"
)

// TaskPriority is the tasks.priority column's value set.
type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityUrgent TaskPriority = "urgent"
)

// Task a unit of work, belonging to one list.
type Task struct {
	ID           string       `db:"id" json:"id" sqlb:"pk,default,filter,readonly"`
	WorkspaceID  string       `db:"workspace_id" json:"workspace_id" sqlb:"filter,readonly"`
	ListID       string       `db:"list_id" json:"list_id" sqlb:"filter,expand"`
	List         *List        `db:"-" json:"list,omitempty" sqlb:"expands=list_id"` // filled in by ?expand=list
	AssigneeID   *string      `db:"assignee_id" json:"assignee_id" sqlb:"filter"`
	AuthorID     string       `db:"author_id" json:"author_id" sqlb:"readonly"`
	Title        string       `db:"title" json:"title" sqlb:"filter,sort,search"`
	Description  string       `db:"description" json:"description" sqlb:"filter,search"`
	Status       TaskStatus   `db:"status" json:"status" sqlb:"default,filter,sort"`
	Priority     TaskPriority `db:"priority" json:"priority" sqlb:"default,filter,sort"`
	DueAt        *time.Time   `db:"due_at" json:"due_at" sqlb:"filter,sort"`
	CompletedAt  *time.Time   `db:"completed_at" json:"completed_at" sqlb:"filter,sort,readonly"`
	Position     int32        `db:"position" json:"position" sqlb:"default,sort"`
	CommentCount int32        `db:"comment_count" json:"comment_count" sqlb:"default,filter,sort,readonly"`
	CreatedAt    time.Time    `db:"created_at" json:"created_at" sqlb:"default,sort,readonly"`
	UpdatedAt    time.Time    `db:"updated_at" json:"updated_at" sqlb:"default,sort,readonly"`
	DeletedAt    *time.Time   `db:"deleted_at" json:"deleted_at" sqlb:"readonly"`
}

// TableName is the table Task maps to.
func (Task) TableName() string { return "tasks" }

// User is a row of users.
type User struct {
	ID           string    `db:"id" json:"id" sqlb:"pk,default,filter,readonly"`
	Email        string    `db:"email" json:"email" sqlb:"filter,search"`
	Name         string    `db:"name" json:"name" sqlb:"filter,sort,search"`
	PasswordHash string    `db:"password_hash" json:"-" sqlb:"hidden"`
	CreatedAt    time.Time `db:"created_at" json:"created_at" sqlb:"default,sort,readonly"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at" sqlb:"default,sort,readonly"`
}

// TableName is the table User maps to.
func (User) TableName() string { return "users" }

// Workspace a tenant. Lists, tasks and comments all belong to exactly one.
type Workspace struct {
	ID        string    `db:"id" json:"id" sqlb:"pk,default,filter,readonly"`
	Name      string    `db:"name" json:"name" sqlb:"filter,sort,search"`
	Slug      string    `db:"slug" json:"slug" sqlb:"filter"`
	CreatedAt time.Time `db:"created_at" json:"created_at" sqlb:"default,sort,readonly"`
	UpdatedAt time.Time `db:"updated_at" json:"updated_at" sqlb:"default,sort,readonly"`
}

// TableName is the table Workspace maps to.
func (Workspace) TableName() string { return "workspaces" }
