// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.

package tasks

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/jryannel/sqlb"
	"github.com/jryannel/sqlb/rest"
)

// CommentCreate is the request body for creating a Comment.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type CommentCreate struct {
	TaskID string `json:"task_id"`
	Body   string `json:"body"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c CommentCreate) Row() (*Comment, error) {
	row := &Comment{}
	row.TaskID = c.TaskID
	row.Body = c.Body
	return row, nil
}

// ListCreate is the request body for creating a List.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type ListCreate struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Color       *string `json:"color,omitempty"`
	Position    *int32  `json:"position,omitempty"`
	Archived    *bool   `json:"archived,omitempty"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c ListCreate) Row() (*List, error) {
	row := &List{}
	row.Name = c.Name
	row.Description = c.Description
	if c.Color != nil {
		row.Color = *c.Color
	}
	if c.Position != nil {
		row.Position = *c.Position
	}
	if c.Archived != nil {
		row.Archived = *c.Archived
	}
	return row, nil
}

// ListPatch is the request body for patching a List.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type ListPatch struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
	Position    *int32  `json:"position,omitempty"`
	Archived    *bool   `json:"archived,omitempty"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"name": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *ListPatch) UnmarshalJSON(data []byte) error {
	type plain ListPatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u ListPatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["name"] {
		if u.Name == nil {
			return nil, errors.New("name is not nullable and cannot be set to null")
		}
		out["name"] = *u.Name
	}
	if u.present["description"] {
		if u.Description == nil {
			return nil, errors.New("description is not nullable and cannot be set to null")
		}
		out["description"] = *u.Description
	}
	if u.present["color"] {
		if u.Color == nil {
			return nil, errors.New("color is not nullable and cannot be set to null")
		}
		out["color"] = *u.Color
	}
	if u.present["position"] {
		if u.Position == nil {
			return nil, errors.New("position is not nullable and cannot be set to null")
		}
		out["position"] = *u.Position
	}
	if u.present["archived"] {
		if u.Archived == nil {
			return nil, errors.New("archived is not nullable and cannot be set to null")
		}
		out["archived"] = *u.Archived
	}
	return out, nil
}

// MembershipCreate is the request body for creating a Membership.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type MembershipCreate struct {
	UserID string          `json:"user_id"`
	Role   *MembershipRole `json:"role,omitempty" enum:"owner,admin,member"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c MembershipCreate) Row() (*Membership, error) {
	row := &Membership{}
	row.UserID = c.UserID
	if c.Role != nil {
		row.Role = *c.Role
	}
	return row, nil
}

// TaskCreate is the request body for creating a Task.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type TaskCreate struct {
	ListID      string        `json:"list_id"`
	AssigneeID  *string       `json:"assignee_id,omitempty"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Labels      *[]string     `json:"labels,omitempty"` // Free-form labels. Filter with has, hasany or hasall.
	Status      *TaskStatus   `json:"status,omitempty" enum:"todo,in_progress,blocked,done"`
	Priority    *TaskPriority `json:"priority,omitempty" enum:"low,medium,high,urgent"`
	DueAt       *time.Time    `json:"due_at,omitempty"`
	Position    *int32        `json:"position,omitempty"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c TaskCreate) Row() (*Task, error) {
	row := &Task{}
	row.ListID = c.ListID
	row.AssigneeID = c.AssigneeID
	row.Title = c.Title
	row.Description = c.Description
	if c.Labels != nil {
		row.Labels = *c.Labels
	}
	if c.Status != nil {
		row.Status = *c.Status
	}
	if c.Priority != nil {
		row.Priority = *c.Priority
	}
	row.DueAt = c.DueAt
	if c.Position != nil {
		row.Position = *c.Position
	}
	return row, nil
}

// TaskPatch is the request body for patching a Task.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type TaskPatch struct {
	ListID      *string       `json:"list_id,omitempty"`
	AssigneeID  *string       `json:"assignee_id,omitempty"`
	Title       *string       `json:"title,omitempty"`
	Description *string       `json:"description,omitempty"`
	Labels      *[]string     `json:"labels,omitempty"` // Free-form labels. Filter with has, hasany or hasall.
	Status      *TaskStatus   `json:"status,omitempty" enum:"todo,in_progress,blocked,done"`
	Priority    *TaskPriority `json:"priority,omitempty" enum:"low,medium,high,urgent"`
	DueAt       *time.Time    `json:"due_at,omitempty"`
	Position    *int32        `json:"position,omitempty"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"list_id": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *TaskPatch) UnmarshalJSON(data []byte) error {
	type plain TaskPatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u TaskPatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["list_id"] {
		if u.ListID == nil {
			return nil, errors.New("list_id is not nullable and cannot be set to null")
		}
		out["list_id"] = *u.ListID
	}
	if u.present["assignee_id"] {
		out["assignee_id"] = u.AssigneeID
	}
	if u.present["title"] {
		if u.Title == nil {
			return nil, errors.New("title is not nullable and cannot be set to null")
		}
		out["title"] = *u.Title
	}
	if u.present["description"] {
		if u.Description == nil {
			return nil, errors.New("description is not nullable and cannot be set to null")
		}
		out["description"] = *u.Description
	}
	if u.present["labels"] {
		if u.Labels == nil {
			return nil, errors.New("labels is not nullable and cannot be set to null")
		}
		out["labels"] = *u.Labels
	}
	if u.present["status"] {
		if u.Status == nil {
			return nil, errors.New("status is not nullable and cannot be set to null")
		}
		out["status"] = *u.Status
	}
	if u.present["priority"] {
		if u.Priority == nil {
			return nil, errors.New("priority is not nullable and cannot be set to null")
		}
		out["priority"] = *u.Priority
	}
	if u.present["due_at"] {
		out["due_at"] = u.DueAt
	}
	if u.present["position"] {
		if u.Position == nil {
			return nil, errors.New("position is not nullable and cannot be set to null")
		}
		out["position"] = *u.Position
	}
	return out, nil
}

// Register mounts every exposed resource on api.
//
// The handlers are rest.Resource, instantiated per model. Registration is
// generic rather than reflective because query hooks are keyed by type: a
// BeforeQuery hook registered on a model applies to its REST reads too, which
// is how tenant scoping stops being something each handler must remember.
func Register(api huma.API, db sqlb.Executor) error {
	if err := rest.Resource[Comment, CommentCreate, rest.None[Comment]](api, db, rest.Options{
		Path:            "/comments",
		Name:            "comment",
		Tag:             "comments",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpList,
		Description:     "A comment on a task.",
		DefaultPageSize: 50,
		MaxPageSize:     100,
	}); err != nil {
		return err
	}
	if err := rest.Resource[List, ListCreate, ListPatch](api, db, rest.Options{
		Path:            "/lists",
		Name:            "list",
		Tag:             "lists",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpList,
		Description:     "A named list of tasks within a workspace.",
		DefaultPageSize: 25,
		MaxPageSize:     100,
		Expandable:      []string{"tasks"},
	}); err != nil {
		return err
	}
	if err := rest.Resource[Membership, MembershipCreate, rest.None[Membership]](api, db, rest.Options{
		Path:            "/memberships",
		Name:            "membership",
		Tag:             "memberships",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpDelete | rest.OpList,
		Description:     "A user's membership of a workspace, and their role in it.",
		DefaultPageSize: 25,
		MaxPageSize:     100,
	}); err != nil {
		return err
	}
	if err := rest.Resource[Task, TaskCreate, TaskPatch](api, db, rest.Options{
		Path:            "/tasks",
		Name:            "task",
		Tag:             "tasks",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpList,
		Description:     "A unit of work, belonging to one list.",
		DefaultPageSize: 20,
		MaxPageSize:     100,
		MaxFilters:      12,
		Expandable:      []string{"list"},
	}); err != nil {
		return err
	}
	if err := rest.Resource[User, rest.None[User], rest.None[User]](api, db, rest.Options{
		Path:        "/users",
		Name:        "user",
		Tag:         "users",
		Ops:         rest.OpRead | rest.OpList,
		MaxPageSize: 100,
	}); err != nil {
		return err
	}
	if err := rest.Resource[Workspace, rest.None[Workspace], rest.None[Workspace]](api, db, rest.Options{
		Path:        "/workspaces",
		Name:        "workspace",
		Tag:         "workspaces",
		Ops:         rest.OpRead | rest.OpList,
		Description: "A tenant. Lists, tasks and comments all belong to exactly one.",
	}); err != nil {
		return err
	}
	return nil
}
