-- Generated by sqlb. Review before applying.

-- +goose Up
-- create table notes
-- +goose StatementBegin
CREATE TABLE "notes" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "space_id" uuid NOT NULL,
    "title" text NOT NULL,
    "body" text NOT NULL,
    "status" text NOT NULL DEFAULT 'draft',
    "pinned" boolean NOT NULL DEFAULT false,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "notes_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "notes_status_check" CHECK ("status" IN ('draft', 'published', 'archived'))
);
COMMENT ON TABLE "notes" IS 'A note, belonging to exactly one space.';
-- +goose StatementEnd
-- create table spaces
-- +goose StatementBegin
CREATE TABLE "spaces" (
    "id" uuid NOT NULL DEFAULT uuidv7(),
    "name" text NOT NULL,
    "slug" text NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT now(),
    "updated_at" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "spaces_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "spaces_slug_key" UNIQUE ("slug")
);
COMMENT ON TABLE "spaces" IS 'A tenant. Every note belongs to exactly one.';
-- +goose StatementEnd
-- add foreign key notes_space_id_fkey
ALTER TABLE "notes" ADD CONSTRAINT "notes_space_id_fkey" FOREIGN KEY ("space_id") REFERENCES "spaces" ("id") ON DELETE CASCADE;
-- index notes_space_id_status_idx
CREATE INDEX "notes_space_id_status_idx" ON "notes" ("space_id", "status");

-- +goose Down
DROP INDEX "notes_space_id_status_idx";
ALTER TABLE "notes" DROP CONSTRAINT "notes_space_id_fkey";
DROP TABLE "spaces";
DROP TABLE "notes";
