// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.
//
// The vocabulary every generated client shares: the response envelopes, the
// problem document, the transport signature and the cursor pager.
//
// It is a library of its own because Dart is nominally typed. Two clients each
// declaring Page would declare two unrelated classes, so an application with
// two modules could not pass a page from either to one widget, nor give both
// one Transport — an 'as' prefix made that compile without making it work.
// Every client exports this library, so importing a client still offers Page,
// Problem and Transport, and two clients now offer the same ones (issue #110).
//
// What is NOT here: Row and the filter-condition types. Dart privacy is per
// library, and both keep their contract with the generated code private — the
// _str/_int protocol a row view inherits, and Cond._encode. They stay with each
// client, where being duplicated costs nothing observable because nothing can
// observe them.
//
// It imports nothing — not even a pub package.

// -------------------------------------------------------------------- runtime

/// A value with a spelling on the wire.
///
/// Every generated enum implements it, so the encoder can write a filter
/// carrying a typed value without knowing which enum it is.
abstract interface class WireValue {
  /// The value as the server spells it.
  String get wire;
}

/// Thrown when a row is asked for a column the response did not carry.
///
/// Dart cannot narrow a type by a runtime projection, so this is where a
/// [select] that dropped a column is reported: at the read, naming the column
/// and the fix, rather than as a null that travels somewhere else first.
class MissingColumn implements Exception {
  /// Names the row type and the column that was absent.
  const MissingColumn(this.type, this.column);

  /// The row view that was read, e.g. Task.
  final String type;

  /// The column, in its wire spelling.
  final String column;

  @override
  String toString() =>
      'MissingColumn: $type.$column was not in the response. Add it to '
      'select, or drop select to get every column.';
}

/// Thrown when a column carries a value its generated enum does not have.
///
/// The value set grew on the server and this client predates it, so the fix is
/// to regenerate rather than to handle the value.
class UnknownEnumValue implements Exception {
  /// Names the enum and the value that was not in it.
  const UnknownEnumValue(this.type, this.value);

  /// The generated enum, e.g. TaskStatus.
  final String type;

  /// The value the server sent.
  final String value;

  @override
  String toString() =>
      'UnknownEnumValue: $type has no value $value. The schema this client '
      'was generated from is older than the server; regenerate it.';
}

/// A capped set of expanded child rows.
///
/// [hasMore] reports truncation, which a bare list could not, so a caller
/// showing twenty of two hundred can tell.
class Collection<T> {
  /// Wraps rows that are already decoded.
  const Collection({required this.items, required this.hasMore});

  /// Decodes an envelope, mapping each element with [item].
  factory Collection.fromJson(
    Map<String, dynamic> json,
    T Function(Map<String, dynamic>) item,
  ) {
    return Collection<T>(
      items: _rows(json, item),
      hasMore: json['has_more'] as bool? ?? false,
    );
  }

  /// The rows, in the order the server returned them.
  final List<T> items;

  /// Whether the server had more rows than it returned.
  final bool hasMore;
}

/// The body of every list response: a collection, plus where in the walk it is.
class Page<T> extends Collection<T> {
  /// Wraps rows that are already decoded.
  const Page({
    required super.items,
    required super.hasMore,
    required this.page,
    required this.perPage,
    this.nextCursor,
    this.total,
  });

  /// Decodes a list response, mapping each element with [item].
  factory Page.fromJson(
    Map<String, dynamic> json,
    T Function(Map<String, dynamic>) item,
  ) {
    return Page<T>(
      items: _rows(json, item),
      hasMore: json['has_more'] as bool? ?? false,
      page: (json['page'] as num?)?.toInt() ?? 1,
      perPage: (json['per_page'] as num?)?.toInt() ?? 0,
      nextCursor: json['next_cursor'] as String?,
      total: (json['total'] as num?)?.toInt(),
    );
  }

  /// The one-based page number this response is.
  final int page;

  /// The page size the server used, which may be smaller than the one asked
  /// for.
  final int perPage;

  /// Where to resume, present whenever a next page exists. Prefer it to
  /// [page]: it costs the same at any depth and cannot skip or repeat a row
  /// when the table is written to mid-walk.
  final String? nextCursor;

  /// Total matching rows, present only when countExact was asked for.
  final int? total;
}

/// One rejected parameter or field.
class ProblemDetail {
  /// Builds a detail. Decoded from a response rather than constructed, mostly.
  const ProblemDetail({
    required this.message,
    this.location,
    this.value,
    this.allowed = const [],
  });

  /// Decodes one entry of a problem document's errors array.
  factory ProblemDetail.fromJson(Map<String, dynamic> json) => ProblemDetail(
    message: json['message'] as String? ?? '',
    location: json['location'] as String?,
    value: json['value'],
    allowed: ((json['allowed'] as List<dynamic>?) ?? const [])
        .map((value) => '$value')
        .toList(growable: false),
  );

  /// What was wrong.
  final String message;

  /// Where the problem is, e.g. query.sort.
  final String? location;

  /// The value that was rejected.
  final Object? value;

  /// What would have been accepted instead, where the set is finite. This is
  /// the half of an error that turns a dead end into a fix, and it is why this
  /// type exists at all rather than a message string.
  final List<String> allowed;
}

/// The RFC 9457 problem document every rejection returns.
class Problem {
  /// Builds a problem document.
  const Problem({
    this.type,
    this.title,
    this.status,
    this.detail,
    this.errors = const [],
  });

  /// Decodes a problem document.
  factory Problem.fromJson(Map<String, dynamic> json) => Problem(
    type: json['type'] as String?,
    title: json['title'] as String?,
    status: (json['status'] as num?)?.toInt(),
    detail: json['detail'] as String?,
    errors: ((json['errors'] as List<dynamic>?) ?? const [])
        .map((value) => ProblemDetail.fromJson(value as Map<String, dynamic>))
        .toList(growable: false),
  );

  /// Narrows a decoded error body to a problem document, or null if it is not
  /// one. A transport uses this to decide whether the body it got is worth
  /// decoding.
  static Problem? tryParse(Object? body) {
    if (body is! Map<String, dynamic>) return null;
    if (body['status'] is num || body['errors'] is List) {
      return Problem.fromJson(body);
    }
    return null;
  }

  /// A URI naming the problem kind.
  final String? type;

  /// A short summary.
  final String? title;

  /// The HTTP status.
  final int? status;

  /// A longer explanation.
  final String? detail;

  /// One entry per rejected parameter or field.
  final List<ProblemDetail> errors;

  /// The values a rejection named for one parameter, e.g.
  /// allowedFor('query.sort'). Empty when the rejection named none.
  List<String> allowedFor(String location) {
    for (final error in errors) {
      if (error.location == location) return error.allowed;
    }
    return const [];
  }
}

/// One request, as the generated functions describe it.
class ApiRequest {
  /// Describes a request. Built by the generated functions, not by hand.
  const ApiRequest({
    required this.method,
    required this.path,
    this.query,
    this.body,
    this.cancel,
  });

  /// GET, POST, PATCH or DELETE.
  final String method;

  /// Path from the API root, already encoded, e.g. /tasks/1.
  final String path;

  /// Encoded query string without the leading question mark.
  final String? query;

  /// The JSON body, already reduced to maps and lists.
  final Object? body;

  /// Whatever the transport's HTTP client cancels with, passed through
  /// untouched. Dio takes a CancelToken here; a client that has no such notion
  /// ignores it. It is [Object] rather than a package type so that this file
  /// keeps its promise to import nothing.
  final Object? cancel;
}

/// The application's request function.
///
/// Everything not derivable from the schema lives behind this: the base URL,
/// the auth header, refresh, retry, offline behaviour and what a 401 does. It
/// returns the decoded JSON body, or null for a 204.
///
/// A minimal one over Dio:
///
///     final Transport transport = (request) async {
///       final response = await dio.request<Object?>(
///         request.query == null || request.query!.isEmpty
///             ? request.path
///             : '${request.path}?${request.query}',
///         options: Options(method: request.method),
///         data: request.body,
///         cancelToken: request.cancel as CancelToken?,
///       );
///       return response.data;
///     };
typedef Transport = Future<Object?> Function(ApiRequest request);

/// One term of an ordering: a sortable column, ascending or descending.
class SortTerm implements WireValue {
  /// Wraps a term the server will accept. Reach for a generated Sort enum's
  /// asc or desc rather than building one of these by hand.
  const SortTerm(this.wire);

  @override
  final String wire;
}

/// Walks a list endpoint by cursor: the shape an infinite-scrolling list needs,
/// and the arithmetic keyset pagination exists to replace.
///
/// It holds rows and a position, and nothing about how they are displayed, so
/// it drops into a Riverpod notifier, a BLoC or a StatefulWidget without
/// preferring any of them.
class CursorPager<T> {
  /// Wraps a fetch that takes the cursor to resume from, or null for the first
  /// page. The generated per-resource pagers supply one.
  CursorPager(this._fetch);

  final Future<Page<T>> Function(String? cursor) _fetch;

  /// The rows loaded so far, in order. Owned by the pager: read it, do not
  /// mutate it.
  final List<T> items = [];

  String? _cursor;
  bool _exhausted = false;
  int? _total;
  Future<void>? _inFlight;

  /// Whether another page exists. False before the first load only because
  /// nothing has been fetched yet.
  bool get hasMore => !_exhausted;

  /// Whether a fetch is in flight.
  bool get isLoading => _inFlight != null;

  /// Total matching rows, if a load asked for the count.
  int? get total => _total;

  /// Fetches the next page and appends it.
  ///
  /// Concurrent calls collapse onto the one already running, which is what a
  /// scroll listener needs: it fires on every frame near the end of the list
  /// and only the first call should reach the network.
  Future<void> loadMore() {
    final pending = _inFlight;
    if (pending != null) return pending;
    if (_exhausted) return Future<void>.value();
    final started = _load().whenComplete(() => _inFlight = null);
    _inFlight = started;
    return started;
  }

  Future<void> _load() async {
    final page = await _fetch(_cursor);
    items.addAll(page.items);
    _total = page.total ?? _total;
    _cursor = page.nextCursor;
    if (_cursor == null) _exhausted = true;
  }

  /// Discards everything loaded and starts the walk over, which is what a
  /// pull-to-refresh does.
  ///
  /// A fetch already in flight is not cancelled and its rows are still
  /// appended. Cancel it through the transport if that matters.
  void reset() {
    items.clear();
    _cursor = null;
    _exhausted = false;
    _total = null;
  }
}

// --------------------------------------------------------------------- decoding

List<T> _rows<T>(
  Map<String, dynamic> json,
  T Function(Map<String, dynamic>) item,
) {
  return ((json['items'] as List<dynamic>?) ?? const [])
      .map((value) => item(value as Map<String, dynamic>))
      .toList(growable: false);
}
